### ISSUE TITLE
CSG-2 Data fix

### ISSUE THREAD

**Issue by s3719046** [r-spacex/SpaceX-API#1010]
I believe the launch date year is wrong, should change from 2021 to 2022

https://api.spacexdata.com/v4/launches/6161d32d6db1a92bfba85359

**Comment by russelltwarwick** [comment]
This still seems to be an issue. The only correct date is "date_local": "2022-01-27T18:11:00-05:00"

date_utc and date_unix are still showing the incorrect launch date

**Comment by russelltwarwick** [comment]
date_utc is now showing the correct date but date_unix is showing date from 2021

**Comment by rliegmann** [comment]
date_unix.  is now correct.   :-)

I think problem can be closed.
