### ISSUE TITLE
Starlink 4-12 missing from DB

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#1057]
It seems like a lot of other launches are missing too. Is something going on with the manifest? 

I think the Starling launch is happening tomorrow, so would be nice to have it in asap. I would do this myself but the admins only said I could edit the manifest if I have a certain level of Karma.

**Comment by timisenman** [comment]
There are a bevy of launches in this manifest, but the API doesn't seem to be showing them at all: https://www.reddit.com/r/SpaceX/wiki/launches/manifest

**Comment by russelltwarwick** [comment]
@jakewmeyer

**Comment by timisenman** [comment]
@jakewmeyer my forever savior: please let me know if there's anything I can do to help here, like prod the admins of the subreddit.
