### ISSUE TITLE
Request for UNIX time & request fix date format in Core parts

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#106]
I've noticed that on of the cores has a wrong date format:
When running this endpoint: `GET https://api.spacexdata.com/v2/parts/cores?status=active` the original launch date-format differs. 

Also, could a `*_date_unix` time-format be added to other date related models as well, including the `cores`?

**Comment by jakewmeyer** [comment]
Looks like an issue with the date updating utility, which is adding milliseconds onto the usual UTC timestamps. Looking at fixes

**Comment by jakewmeyer** [comment]
Since the default date in javascript includes milliseconds, I'll be using this utc date format for everything now (2018-06-29T09:42:00.000Z). The formatting should be consistent now.

Working on adding unix timestamps to cores and capsules

**Comment by jakewmeyer** [comment]
Unix times added to cores and capsules 👍

**Comment by jeroenboumans** [comment]
Thanks Jake! :) 👍
