### ISSUE TITLE
Misplacing upcoming launches if sort order is set to "desc"

### ISSUE THREAD

**Issue by about-future** [r-spacex/SpaceX-API#107]
Hi guys,

When trying to get a list of all launches, using this url "https://api.spacexdata.com/v2/launches/all" and adding sort order is set as "desc", the returned list is missing all upcoming launches.
https://api.spacexdata.com/v2/launches/all?order=desc

If the sort order is set as "asc", everything is fine and returns the entire list of launches.
https://api.spacexdata.com/v2/launches/all?order=asc

Hope my feedback helps. Thank you!

**Comment by about-future** [comment]
Correction... it's not missing the upcoming launches, but on "desc" case sets them at the end of the list, even if the sort order was correctly set. Sorry for the miss information!

**Comment by jakewmeyer** [comment]
Looks like a json concatenation issue. All the lunches are there, they we just added to the bottom by default. Working on a solution

**Comment by jakewmeyer** [comment]
Fix is live 👍  Just needed to add a condition to check the order before concatenating the response

**Comment by about-future** [comment]
Thank you, Jake!
