### ISSUE TITLE
Internal Server Error when invalid parameter in request

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#108]
Endpoint related with launches response with *500 - Internal Server Error* when I send request with invalid parameter instead of *200 - Ok* and empty array.

Examples:
https://api.spacexdata.com/v2/launches?orbit=test - **200** - ok
https://api.spacexdata.com/v2/launches/all?orbit=test - **500** - internal server error

https://api.spacexdata.com/v2/launches?flight_number=100 - **200** - ok
https://api.spacexdata.com/v2/launches/upcoming?flight_number=100 - **500** - internal server error

I suppose that every request should response with 200 - Ok and empty array (or 204 - No Content) because it's easier to handle it when using API.

**Comment by jakewmeyer** [comment]
First example is an issue tied to the way all launches are combined and calculated. This is also directly related to #109 

Second example gives me 200 and an empty array, which appears normal for me

**Comment by Tearth** [comment]
Everything looks good, thanx!
