### ISSUE TITLE
Can't get launches with flight number larger than 64

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#109]
When we send request to get all launches (https://api.spacexdata.com/v2/launches/all), we see that the maximum flight number is 68. Let's try to get information about the specified launch by apply fliter flight_number:

https://api.spacexdata.com/v2/launches/all?flight_number=62 - ok
https://api.spacexdata.com/v2/launches/all?flight_number=63 - ok
https://api.spacexdata.com/v2/launches/all?flight_number=64 - ok
https://api.spacexdata.com/v2/launches/all?flight_number=65 - internal server error, should return data
https://api.spacexdata.com/v2/launches/all?flight_number=66 - internal server error, should return data
https://api.spacexdata.com/v2/launches/all?flight_number=67 - internal server error, should return data
https://api.spacexdata.com/v2/launches/all?flight_number=68 - internal server error, should return data
https://api.spacexdata.com/v2/launches/all?flight_number=69 - internal server error, should return empty array
https://api.spacexdata.com/v2/launches/all?flight_number=70 - internal server error, should return empty array

**Comment by jakewmeyer** [comment]
This issue is a result of d728fdff82eb375e15616e3c83f2428dc1f34cd4, which added a condition to check the order of results before concatenating past and upcoming launches, in order to respect the `order` query string. Rewriting to avoid this issue. Also applies to the first example in #108

**Comment by Tearth** [comment]
Nice, it seems that everything works good now. Thanx for your work!
