### ISSUE TITLE
Roadster data

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#110]
Is it possible to add data about Roadster in space? I think about:
* orbit parameters
* actual traveled distance
* current speed
* upcoming flybys next to Earth/Mars
* other important/fun info

**Comment by jakewmeyer** [comment]
Any particular schema you like?

Will probably add it under the info endpoints like -> [https://api.spacexdata.com/v2/info/roadster](https://api.spacexdata.com/v2/info/roadster)

**Comment by jakewmeyer** [comment]
Still working through some issues collecting the necessary data.

Originally tried scraping from a website with the calculated data, but scraping a SPA doesn't work well unless you use headless chrome or something like that, which feels like overkill.

Might end up having to do the math myself from the JPL data

**Comment by jakewmeyer** [comment]
Decided to use headless chrome, and it seems to work well 👍 Still adding additional data, but currently the orbital data is updated every 10min

**Comment by Tearth** [comment]
Looks pretty nice, good job. I will implement this endpoint in my library as soon as the rest of data will be added, thanx!

**Comment by jakewmeyer** [comment]
Looks like the page didn't have enough time to load in some cases. Added a 5000ms wait time to allow everything plenty of time to load, shouldn't be an issue now

**Comment by Tearth** [comment]
Yeah, now it works perfect. Thanx!
