### ISSUE TITLE
Request for Missions / Payload endpoints

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#115]
Hi @jakewmeyer,

Since payloads are more detailed now I was thinking that it would be very useful to have these endpoints:

**Missions**
```http
GET https://api.spacexdata.com/v2/missions/
GET https://api.spacexdata.com/v2/missions/#id
GET https://api.spacexdata.com/v2/missions/?payload_id=x&order=desc
```

**Payloads/Satellites** (for example, retrieve all satellites of the Iridium mission)
```http
GET https://api.spacexdata.com/v2/payloads/
GET https://api.spacexdata.com/v2/payloads/#id
GET https://api.spacexdata.com/v2/payloads/?mission_id=x&order=desc
```

Would this be an option to add to the API?

Regards,
Jeroen

**Comment by jakewmeyer** [comment]
Second one should be simple to implement.

What kind of return are you looking for from missions?

**Comment by jeroenboumans** [comment]
Hi Jake,
I think missions could return a mission object/array containing data like:
- Mission Name
- Description
- Manufacturer
- Wikipedia article, for example: the [Iridium NEXT](https://en.wikipedia.org/wiki/Iridium_satellite_constellation) mission
- (Other links like official website, reddit/official twitter user-id/name?)

Payloads can then be selected by it's mission id.
Also, could we add the _NORAD-id_ to the _payloads_, when available? For example: https://www.n2yo.com/satellite/?s=43205 with NORAD ID 43205.

**Comment by jakewmeyer** [comment]
Assuming all the Iridium launches would be under the same mission name, correct?

In situations like that, wouldn't there be more than one `payload_id` per mission?

Will definitely add the NORAD id's

**Comment by jakewmeyer** [comment]
Also, should the payloads only include previous launches? Or upcoming ones as well?

**Comment by jakewmeyer** [comment]
Initial version of payloads is live, with the following endpoints:

```http
GET https://api.spacexdata.com/v2/payloads
```
```http
GET https://api.spacexdata.com/v2/payloads/CASSIOPE
```

Both pull from past and upcoming launches. Unfortunately, these are pretty time intensive queries to run, looking at ways to speed them up a bit

**Comment by jeroenboumans** [comment]
Wow that was fast :)
> Assuming all the Iridium launches would be under the same mission name, correct?

Yes, that would be a reason to implement the **missions**-endpoint as well.
> In situations like that, wouldn't there be more than one payload_id per mission?

Yes, since payloads in launches belong to a certain mission(s) (they may overlap in the future with FH, no?).

> Will definitely add the NORAD id's

Awesome!!
> Also, should the payloads only include previous launches? Or upcoming ones as well?

I'm thinking that the **payloads**-endpoint should return all the payloads available/known in the API. Would it be possible to filter by type as well? For example only `GET` the satellites of a certain mission, like:

```http
GET https://api.spacexdata.com/v2/payloads/?payload_type =Sattelite
GET https://api.spacexdata.com/v2/payloads/CASSIOPE?payload_type=Sattelite
```

Great job so far and I really appreciate it! Can't wait to implement these!

**Comment by jakewmeyer** [comment]
> 'm thinking that the payloads-endpoint should return all the payloads available/known in the API. Would it be possible to filter by type as well? For example only GET the satellites of a certain mission, like:

Looks like Satellite was spelled wrong in the examples
```http
GET https://api.spacexdata.com/v2/payloads/?payload_type =Satellite
GET https://api.spacexdata.com/v2/payloads/CASSIOPE?payload_type=Satellite
```
Don't think the second example needs querystring support, since it would only return a single payload

First example should work, but I discovered some unexpected behavior when testing it. The query string only filters down to a document level, so it included launches that had multiple payloads like a dragon and satellite launch at the same time (Only COTS demo flight 1 so far). Should be able to just filter out the payloads that don't match the querystring criteria easily. 

As far as missions go, here's an initial schema idea with Iridium NEXT as the sample:
```json
{
  "mission_name": "Iridium NEXT",
  "mission_id": "?",
  "manufacturers": [
    "Orbital ATK"
  ],
  "payload_ids": [
    "Iridium NEXT 1",
    "Iridium NEXT 2",
    "Iridium NEXT 3",
    "Iridium NEXT 4",
    "Iridium NEXT 5",
    "Iridium NEXT 6",
    "Iridium NEXT 7"
  ],
  "wikipedia": "https://en.wikipedia.org/wiki/Iridium_satellite_constellation",
  "website": "https://www.iridiumnext.com/",
  "twitter": "https://twitter.com/IridiumBoss?lang=en",
  "description": "In 2017, Iridium began launching Iridium NEXT, a second-generation worldwide network of telecommunications satellites, consisting of 66 active satellites, with another nine in-orbit spares and six on-ground spares. These satellites will incorporate features such as data transmission that were not emphasized in the original design. The constellation will provide L-band data speeds of up to 128 kbit/s to mobile terminals, up to 1.5 Mbit/s to Iridium Pilot marine terminals, and high-speed Ka-band service of up to 8 Mbit/s to fixed/transportable terminals. The next-generation terminals and service are expected to be commercially available by the end of 2018. However, Iridium's proposed use of its next-generation satellites has raised concerns the service will harmfully interfere with GPS devices. The satellites will incorporate a secondary payload for Aireon, a space-qualified ADS-B data receiver. This is for use by air traffic control and, via FlightAware, for use by airlines. A tertiary payload on 58 satellites is a marine AIS ship-tracker receiver, for Canadian company exactEarth Ltd. Iridium can also be used to provide a data link to other satellites in space, enabling command and control of other space assets regardless of the position of ground stations and gateways."
}
```
Any idea on what to use for mission id's?

**Comment by jakewmeyer** [comment]
NORAD id's added 👍

**Comment by jakewmeyer** [comment]
@jeroenboumans 

Just a quick update:

Are we only wanting missions for things that have 2 or more launches tied together somehow? If we wanted a mission for every launch, it just becomes a parallel of the launches endpoint, with a few more links and data, which could make it harder to maintain in the future.

Other than that, the payloads endpoint should be completely done, and the preliminary work for the missions endpoint has been done as well. A few of the missions have been added too, if you want to check them out 👍

**Comment by jakewmeyer** [comment]
@jeroenboumans Is this something you want me to continue working on? Wondering because there's a lot of overlapping data, and most of it could be integrated directly into launches.

**Comment by jeroenboumans** [comment]
@jakewmeyer, if missions are just a collection of launches now it is possible to ```GET``` the same data as with a missions-endpoint. For me it'd be nice to show a list of missions routing to a list of launches in that mission. Personally I think from out an entity perspective so that was the reason I've asked for a mission entity endpoint. If this is not maintainable right now, it is okay for me if this ticket got de-prioritized.

**Comment by jakewmeyer** [comment]
Sounds good 👍

**Comment by jakewmeyer** [comment]
Couldn't this just be solved by adding a mission id field to launches, so launches under the same mission could be grouped?

**Comment by jeroenboumans** [comment]
Hi Jake, yes, this was the initial idea :) A table with missions (containing only mission data). And launches referring to it's mission via this id.

**Comment by jakewmeyer** [comment]
All missions are added, and mission id's have been added to all applicable launches.
