### ISSUE TITLE
Add static fire date and success status to all launches

### ISSUE THREAD

**Issue by jakewmeyer** [r-spacex/SpaceX-API#116]

**Comment by jakewmeyer** [comment]
Added `static_fire_date_utc` to all launches.

**Comment by jeroenboumans** [comment]
Hi @jakewmeyer, could `static_fire_date_unix` also be added to the launches? 
Thank you!

**Comment by jakewmeyer** [comment]
Added

**Comment by jeroenboumans** [comment]
Thanks @jakewmeyer ! :) 👍
