### ISSUE TITLE
Querying launches against a provided array of values

### ISSUE THREAD

**Issue by stanifert** [r-spacex/SpaceX-API#1199]
An example query is given in the [query guide](https://github.com/r-spacex/SpaceX-API/blob/master/docs/queries.md) that seems to return only launches that have a matching `date_precision` value from a provided array:
```
{
  "query": {
    "date_precision": {
      "$in": [
        "month",
        "day"
      ]
    }
  }
}
```

So would this not be the correct `query` body to return only launches that have a matching `id` value from a provided array?
```
{
  "query": {
    "id": {
      "$in": [
        "6243aea5af52800c6e91925c",
        "625828f25988f159024b9643",
        "607a34e35a906a44023e085e",
        "6161c88d6db1a92bfba85348"
      ]
    }
  }
}
```

When querying with the above `query` body, I receive the full list of launches - no exclusions or filtering.  Am I building my query wrong? Is this functionality supported?

**Comment by jakewmeyer** [comment]
Ah, I need to add a note about this little gotcha. Technically under the hood the document id is `_id`, not `id`. It gets re-written to `id` on query projection. Apologies for the confusion.

This should work:
```
{
  "query": {
    "_id": {
      "$in": [
        "6243aea5af52800c6e91925c",
        "625828f25988f159024b9643",
        "607a34e35a906a44023e085e",
        "6161c88d6db1a92bfba85348"
      ]
    }
  }
}
```

**Comment by stanifert** [comment]
@jakewmeyer Little gotcha indeed! It's working great now, thank you for the quick reply Jake!
