### ISSUE TITLE
issue with vehicles endpoint

### ISSUE THREAD

**Issue by waterskier2007** [r-spacex/SpaceX-API#12]
I am not familiar with ruby, but I am guessing that the hash merge of three dictionaries creates one large dictionary. I think you really want an array of the three objects. something like

[$falcon9, $falcon_heavy, $dragon]

but again... not super familiar with ruby

**Comment by waterskier2007** [comment]
see the change in the last commit of #11... I think that should be what you want

**Comment by jakewmeyer** [comment]
It looks like that fixed it 👍
