### ISSUE TITLE
Small patch images now have black backgrounds, no longer transparent

### ISSUE THREAD

**Issue by stanifert** [r-spacex/SpaceX-API#1200]
Launch `links/patch/small` seems to be returning patch images with black backgrounds. Seems to only be the `small` images only, `large` images remain transparent. For the Transporter-4 mission for example:

small: https://images2.imgbox.com/4e/2a/EmtXOXTB_o.jpg
large: https://images2.imgbox.com/60/d6/K6GYauvu_o.jpg

Seems to have started today, not sure if intentional?

**Comment by jakewmeyer** [comment]
Sorry, this was related to a fix for #1189, turns out the library I used was hardcoding uploads as jpeg, which killed the transparency. Should be fixed now
