### ISSUE TITLE
Getting 503 when requesting from Hetzner VPS

### ISSUE THREAD

**Issue by psidex** [r-spacex/SpaceX-API#1218]
```
simon@apollo:~$ wget https://api.spacexdata.com/v4/launches/latest
--2022-09-11 00:16:22--  https://api.spacexdata.com/v4/launches/latest
Resolving api.spacexdata.com (api.spacexdata.com)... 2606:4700:3035::ac43:b70f, 2606:4700:3032::6815:240e, 172.67.183.15, ...
Connecting to api.spacexdata.com (api.spacexdata.com)|2606:4700:3035::ac43:b70f|:443... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2022-09-11 00:16:22 ERROR 503: Service Temporarily Unavailable.
```

Requesting from my local machine I get 200 and a proper response.

On the VPS I started getting a 403 at `2022-09-04 23:15:37` (UTC), then switched to 503 at `2022-09-05 03:01:16`

I am running a Discord bot that makes ~1 request per minute in a loop (plus occsional other requests), which as far as I was aware was fine.

Seems to be the same issue as #1209? I've stopped the bot for now in hopes that Cloudflare will cool down.

If I curl I can see the same message they were getting; "api.spacexdata.com needs to review the security of your connection before proceeding"

**Comment by jakewmeyer** [comment]
Thought I reset most of the Cloudflare settings I was fiddling with, but looks like I left **Bot Fight Mode** on, I bet this was the issue. Let me know if it's still giving 503's

**Comment by psidex** [comment]
Yep 503's have stopped now, thanks!
