### ISSUE TITLE
Differentiate between JRTI(1) and JRTI(2)

### ISSUE THREAD

**Issue by sladen** [r-spacex/SpaceX-API#122]
Ideally the:

    landing_vehicle":"JRTI"

would be disambiguated to handle the difference between the two ASDS barges that have carried this name/abbreviation.

**Comment by jakewmeyer** [comment]
Wasn't aware of the previous version. I'll add `landing_vehicle_version` underneath to differentiate 👍

**Comment by sladen** [comment]
Possibly more useful would be to directly list the hull details (Marmac 301, 303, 304), eg:
  hull: {"name": "Marmac 300", "abs": 1063184, "imo": 8645612 } /* JRTI 1 */
  hull: {"name": "Marmac 303", "abs": 1245062 } /* JRTI 2 */
  hull: {"name": "Marmac 304", "abs": 1247500 } /* OCISLY */
  hull: {"name": "Mr. Steven", "abs: 1249191, "imo": 9744465, "mmsi": 9744465 } /* Mr. Steven */

* https://www.reddit.com/r/spacex/wiki/asds

has additional information, including which tug boats/support ships handled each recovery attempt.

**Comment by jakewmeyer** [comment]
I like the hull idea, also been planning on adding more details about the vessels to the api in their own endpoint.

**Comment by jakewmeyer** [comment]
Just a quick update:

All ship data has been added, and a script was added to keep speed, course, status, and coordinates updated every 10 min. The schema for each ship is as follows:

[https://api.spacexdata.com/v3/ships/MRSTEVEN](https://api.spacexdata.com/v3/ships/MRSTEVEN)

```json
{
  "ship_id": "MRSTEVEN",
  "ship_name": "MR STEVEN",
  "ship_model": null,
  "ship_type": "High Speed Craft",
  "roles": [
    "Fairing Recovery"
  ],
  "active": true,
  "imo": 9744465,
  "mmsi": 338358000,
  "abs": 1249191,
  "class": 15252765,
  "weight_lbs": 992000,
  "weight_kg": 449964,
  "year_built": 2015,
  "home_port": "Port of Los Angeles",
  "status": "Stopped",
  "speed_kn": 0,
  "course_deg": null,
  "position": {
    "latitude": 33.73138,
    "longitude": -118.2712
  },
  "successful_landings": null,
  "attempted_landings": null,
  "missions": [
    "KoreaSat 5A",
    "Paz / Starlink Demo",
    "Iridium NEXT Mission 4",
    "Iridium NEXT Mission 6",
    "Iridium NEXT Mission 7"
  ]
}
```

Let me know if you have any other suggestions for additional data, or any corrections. Still trying to decide the best way to link this data to launches. Thinking about adding some sort of ships array field, with the ship id's of all involved for the entire launch.

**Comment by jakewmeyer** [comment]
This feature has been fully implemented now. Each launch has the following array:
```json
  "ships": [
    "HAWK",
    "OCISLY"
  ]
```
This lists the ship_id's of every ship involved in a launch. For more details about each ship, see the ships endpoint => [https://api.spacexdata.com/v3/ships](https://api.spacexdata.com/v3/ships)

This is added in the v3 endpoints which are live currently, but will be officially released and documented when v3 is released in a week or so.
