### ISSUE TITLE
Add API description

### ISSUE THREAD

**Issue by honzajavorek** [r-spacex/SpaceX-API#123]
It would be nice to provide the API description in one of the API description formats, such as the [API Blueprint](http://apiblueprint.org/) (actually Markdown-based, so not that far from what you have now) or the [OpenAPI](https://www.openapis.org/).

**Comment by jakewmeyer** [comment]
API blueprint looks awesome! Been wanting a good standardized format for the docs 👍

**Comment by paraskakis** [comment]
Technically Oracle "owns" API Blueprint as much as it "owns" OpenAPI ;)
Both are open source, both are public specs. Apiary (and Oracle) are invested in both equally.
Choice is up to you, how usable you find each format and what tooling you might want to use from each ecosystem. One great way to verify that your API Description (and thus documentation) matches a specific API implementation is http://dredd.org/en/latest/ - open source testing tool you can use.
I'd be happy to review any API description you put up.

**Comment by jakewmeyer** [comment]
Fair enough, I'll get started on converting the docs over 👍

**Comment by codenirvana** [comment]
@jakewmeyer I feel in addition to the current documentation, having a [Postman Collection](https://www.getpostman.com/collection) will help to access this more easily. 
It allows API Documentation, Categorised Folders, Saved Examples and more.

**Comment by jakewmeyer** [comment]
Absolutely open to having multiple formats/standards available @codenirvana 
Would you be willing to help document it?

@amorriscode Definitely need help creating the api-blueprint version of the docs, juggling a few other feature requests currently.

**Comment by amorriscode** [comment]
@jakewmeyer I have the day off tomorrow so I will tackle this then! I'm going to use the [API Blueprint](http://apiblueprint.org/) if that's okay with you. 👍

**Comment by jakewmeyer** [comment]
Links should be fixed by #137

**Comment by amorriscode** [comment]
Whoops, sorry about that!

**Comment by jakewmeyer** [comment]
No worries 👍
