### ISSUE TITLE
Feature Request: Write support to "launch" a "rocket" using API

### ISSUE THREAD

**Issue by rahul286** [r-spacex/SpaceX-API#124]
@jakewmeyer Thanks for awesome work! 🙂 

I noticed that all the APIs are ready only. Or did I miss something?
How about adding write support?
So that we can do something like below and launch rockets with the API! 🚀

```
POST https://api.spacexdata.com/v2/launches
```

We can also use HTTP PUT instead, if "putting" a rocket into space feels more semantic! 😉

**Comment by rahul286** [comment]
@jakewmeyer Thanks for considering this. 🎉 

Totally agree that unauthorized POST requests can lead to many problems including more increase [space debris](https://en.wikipedia.org/wiki/Space_debris)!

I hope you find a proper authentication solution in time. May the Force be with you!🤞

**Comment by jhpratt** [comment]
Jake, with the new launch client I'm working on, I'll be able to verify the
identity of someone as a subreddit moderator or thread host — letting them
at least update the T0 time seems sensible. I'll already be handling the
change on my end.

If wanted, I could add another field for "approved contributor" to allow
arbitrary users the ability to do so.

**Comment by jakewmeyer** [comment]
@jhpratt keeping this on the back burner for now, until most of the other issues are cleared out and finished. Don't worry about it for the time being

**Comment by jakewmeyer** [comment]
V3 will support PATCH requests for launches. Still working out the details with validation and how I want the input, but this will allow anyone to update a launch with new or corrected info. I'm reserving the ability to create and delete launches, but because launches are added so far in advance, this should be a non issue.

Still a few weeks away from being able to add this, but it's on the way 👍

**Comment by rahul286** [comment]
@jakewmeyer Thanks for the update! 🎉

**Comment by twilco** [comment]
Allowing anyone to edit existing launches seems concerning to me...it only takes one malicious person to ruin it for everyone.

**Comment by Maftalion** [comment]
IMO you should make a 'suggestion' endpoint for each category such as POST -https://api.spacexdata.com/v3/launches/64/suggestion which wouldn't create a new launch but writes to a different table that you can use to receive all suggested updates. That way you can set up a dashboard for all suggested update for you and your mods to vet before actually modifying the records. BTW great work and I hope you all keep it up 👍

**Comment by jeroenboumans** [comment]
Could be the same table but maybe "pushed" rockets can be flagged with a property "accepted" (tiny integer: 0/1) which will be left out in all the GET responses but is used in filtering. So GET endpoints only return launches with "accepted = 1". The accepted property is not visible in the returned json. Just a thought ;)
