### ISSUE TITLE
querystring to Sort

### ISSUE THREAD

**Issue by emersonlaurentino** [r-spacex/SpaceX-API#126]
currently it is possible to do sort ascending and descending, however it is not possible to choose a field to do this sorting. ref: [Query String Options](https://github.com/r-spacex/SpaceX-API/blob/master/docs/launches.md#query-string-options)

I suggest adding a new `sort` attribute to choose any attribute to be sorted.

**Comment by jakewmeyer** [comment]
Added to the list 👍 Thanks!

**Comment by jakewmeyer** [comment]
Sorting support is live + added to docs 👍
