### ISSUE TITLE
epoch_jd is a String, but it appears the actual value is a number

### ISSUE THREAD

**Issue by twilco** [r-spacex/SpaceX-API#128]
Hi all.  I'm writing a wrapper over this API in Rust, and found something a little odd in this `https://api.spacexdata.com/v2/info/roadster` - specifically with the returned `epoch_jd` field.  The value I retrieved was `"2458349.347256945"`.  Is this value ever not a decimal number?  If not, would it be possible to drop off the quotes?  Having the quotes on makes it awkward to deserialize this value in Rust.

**Comment by jakewmeyer** [comment]
Ahh, should be a number, I’ll make the change shortly. 👍

**Comment by twilco** [comment]
Thanks!

**Comment by jakewmeyer** [comment]
Fixed!
