### ISSUE TITLE
Is the API abandonned?

### ISSUE THREAD

**Issue by tysonlmao** [r-spacex/SpaceX-API#1341]
Hi, I'm trying to use this api for a project, and I've noticed the data on the /v5/launches/upcoming endpoint only goes up to Q4 2022. Is it still being updated?

**Comment by LarsVerschoor** [comment]
Hi, yes this project is no longer being maintained

**Comment by tysonlmao** [comment]
That's a shame, there doesn't seem to be many other options as spacex doesn't have a public api.

**Comment by LarsVerschoor** [comment]
Yeah, it really is a shame! This was the first API i had ever used..
