### ISSUE TITLE
Wrapper Graphql

### ISSUE THREAD

**Issue by emersonlaurentino** [r-spacex/SpaceX-API#138]
I am creating a wrappers graphql for api, u can chack in: [SpaceX API GraphQL](https://github.com/emersonlaurentino/spacex-qraphql-api).

Current Roadmap:
- [x] Launches
- [x] Rockets
- [x] Capsules
- [x] Company Info
- [x] Launchpads
- [x] Parts

**Comment by emersonlaurentino** [comment]
@jakewmeyer can you add on readme? I finalized the implementation of the `parts` endpoint.

**Comment by jakewmeyer** [comment]
Added

**Comment by emersonlaurentino** [comment]
Thanks!
