### ISSUE TITLE
Policy for allowing tips to creators of API consuming clients

### ISSUE THREAD

**Issue by philipengberg** [r-spacex/SpaceX-API#140]
Is there a policy on whether or not it is considered to be okay to allow users of endpoints consuming apps to pay tips to the creators of such?

**Comment by jakewmeyer** [comment]
No official policy, but I work on this project for fun in my free time, and don't want to attach any financial responsibility to the project. 

I do appreciate the offer though 👍

**Comment by philipengberg** [comment]
Alright, cool 🙂 What about allowing end users to support developers like me, who makes use of this API to convey the data to users in an engaging way? Use of this API will of course be attributed!

**Comment by jakewmeyer** [comment]
Absolutely fine with that 👍  Feel free to use the API any way you like

**Comment by philipengberg** [comment]
Wonderful, thanks for the great work 👏
