### ISSUE TITLE
Collect a voluntary aggregate of API clients

### ISSUE THREAD

**Issue by philipengberg** [r-spacex/SpaceX-API#141]
I thought it could maybe be interesting to maintain a markdown file in this repo with a creator crowdsourced overview of clients currently using this API, fx to gain inspiration or provide feedback.

Creators of their own clients could then provide PRs which would add their own client to the list.

**Comment by jakewmeyer** [comment]
Isn't the existing list pretty similar to what you're suggesting?

Feedback and ideas are generally funneled to issues and pull requests in the respective repos.

**Comment by philipengberg** [comment]
Sure, it's great. My feeling is that that list is mostly API wrappers instead of actual UI clients? I might be wrong, though 😁I was more thinking of "actual UI clients", like say http://spacexstats.xyz/ or my app https://itunes.apple.com/dk/app/spacexpedia/id1434177600?mt=8 🙂

**Comment by jakewmeyer** [comment]
Ahh, I understand now.

Are we thinking a spot in the readme? or a page in the docs?

I'm fine with either

**Comment by philipengberg** [comment]
Maybe a separate doc is most appropriate? 🙂 If you are aware of a more complete list than mine, shoot them here and I can cook up a draft for one if you'd like?

**Comment by philipengberg** [comment]
I was thinking something along the lines of this https://github.com/r-spacex/SpaceX-API/pull/147. Feedback?

**Comment by jeroenboumans** [comment]
I'll add it as soon as the clients.md is merged :)

**Comment by philipengberg** [comment]
@jeroenboumans It's merged 🎉

**Comment by jeroenboumans** [comment]
Adding :) I've also added a "More" column for an url linking to, for example, a productpage. Hope that's fine by you guys, since my application is not yet open sourced. Will be whenever v2.0 launches :) 👍
