### ISSUE TITLE
Discrepancies regarding rocket fuels

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#142]
I don't get why Falcon 9 & Falcon Heavy vehicles are listed with 'different' oxidizers, or 'propellant_1 in the JSON'.

Falcon Heavy:
```
propellant_1: "subcooled liquid oxygen"
propellant_2: " RP-1 kerosene"
```

Falcon 9:
```
propellant_1: "liquid oxygen"
propellant_2: "RP-1 kerosene"
```

I get that 'subcooled liquid oxygen' and 'liquid oxygen' are technically the same propellant, but for the sake of consistency, they should be the same.

Also, there's a black space in 'propellant_2' in the Falcon Heavy :)

**Comment by jakewmeyer** [comment]
Corrected. Not sure why it was added that way.
