### ISSUE TITLE
Upcoming launches data source

### ISSUE THREAD

**Issue by philipengberg** [r-spacex/SpaceX-API#146]
Can I ask who is responsible for keeping the upcoming launch data up to date, and where we get this data from?

I'm primarily curious since the data of [SpaceXNow](https://spacexnow.com/) seems to be much more complete 🤔

**Comment by jakewmeyer** [comment]
Another issue with adding launches far in advance is getting the proper date format correct. In order to have a valid date, we need to know the day at the very least.

**Comment by jakewmeyer** [comment]
This works for me. Adding this in a few days 👍

**Comment by jakewmeyer** [comment]
Added to all launches. Hope this helps 👍

**Comment by philipengberg** [comment]
Wonderful 😍

**Comment by philipengberg** [comment]
So does this mean that we'll now try to expand the upcoming launch data? 🙂

**Comment by jakewmeyer** [comment]
Yes! 

Another thing to consider is that a good amount of the future launches on the manifest only list the quarter or half the launch occurs in, not just the year. 

![Imgur](https://i.imgur.com/nz3Sde5.png)

**Comment by jakewmeyer** [comment]
The launch manifest usually has the most up to date information possible, so I've been writing a parser for this. 

Once we have the launch added, it checks this page every 10 min, and updates times and dates accordingly. Should cut down on database maintenance levels.

**Comment by jakewmeyer** [comment]
Update script also automatically sets the precision based on the times listed. Also planning on keeping all upcoming launches as tentative up until the moment of launch, since it could change at any time up to that point.

**Comment by philipengberg** [comment]
Good point 👍 Awesome job 💪

**Comment by jakewmeyer** [comment]
Upcoming launches for the next year have been added
