### ISSUE TITLE
Invalid static fire dates

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#151]
Two of the upcoming launches contains invalid static fire date which aren't good to parse (day 00). Is it intentionally and I should fix my library or it's just typo?

I think about:
*"2018-09-00T00:00:00.000Z"*
and
*"2018-11-00T00:00:00.000Z"*

**Comment by jakewmeyer** [comment]
Went ahead and changed them to the first of the month

**Comment by Tearth** [comment]
Nice, now works good, thanx,.
