### ISSUE TITLE
Adding new data to Dragon capsules

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#153]
Hey! I was wondering if adding 'dry mass' and 'maiden flight date' tags to dragon capsules would be worth the effort to add :) Here how it could looks like:

```
{
    "id": "dragon1",
    "name": "Dragon 1",
    "type": "capsule",
    "active": true,
    "crew_capacity": 0,
    ...
    "dry_mass_kg": 4200,
    "dry_mass_lb": 9300,
    ....
    "first_flight": "2010-12-8"
    ...
}
```

The information is readily available at Wikipedia. Thanks for considering it :)

**Comment by jakewmeyer** [comment]
Added 👍

**Comment by jesusrp98** [comment]
I see that dry mass is added correctly, but I can't retrieve the 'maiden flight date'. I don't know if I have to wait the server to refresh or something. Please, let me know.
Thanks.
