### ISSUE TITLE
Reuse count on Cores

### ISSUE THREAD

**Issue by philipengberg** [r-spacex/SpaceX-API#157]
So far cores have obviously only been reused once, thus not incentivising to keep count on this. But now that Block 5 is well under way, this will hopefully change soon 🎉

So provided that we can get the data, maybe we should also think about adding reuse counts where appropriate. I guess it will also make sense for Dragons and one day even fairings 🤠

**Comment by jakewmeyer** [comment]
I agree. It's been in launches for awhile now, but it makes sense to add it to the individual cores and capsules as well.

**Comment by jakewmeyer** [comment]
Added 👍

**Comment by philipengberg** [comment]
Is the reuse count already on launches? 🤔

**Comment by jakewmeyer** [comment]
Reuse count already existed as `flight` under the core section in launches, but it needed to be added to the core tracking too.

**Comment by philipengberg** [comment]
Oh yeah, that’s right!
