### ISSUE TITLE
What's the best way to get a specific launch?

### ISSUE THREAD

**Issue by philipengberg** [r-spacex/SpaceX-API#159]
I can't seem to find documentation for or working endpoints that returns a specific launch. The only way I seem to be able to replicate this is by querying a specific flight number:

```
https://api.spacexdata.com/v2/launches?flight_number=50
```
However, this obviously returns an array instead of a single object, which is slightly annoying 😄 

Would it make sense to follow the principle of most other endpoint by having a detail endpoint like

```
https://api.spacexdata.com/v2/launches/{flight_number or some sort of ID}
```

**Comment by jakewmeyer** [comment]
v3 endpoint supports this

[https://api.spacexdata.com/v3/launches/65](https://api.spacexdata.com/v3/launches/65)

**Comment by philipengberg** [comment]
And also, most endpoints that reference missions, like `/ships` of `/parts/cores`, only reference them by name. 

```json
"missions": [
    "Iridium NEXT 7",
    "SAOCOM 1A"
]
```

So what is the best way to load the corresponding launch from that?

**Comment by jakewmeyer** [comment]
Most of the endpoints are unlikely to change, but until it's officially released, I would wait on using it in production, just in case we decide to make last minute changes.

If you want a peek at the v3 documentation, it's located [here](https://documenter.getpostman.com/view/2025350/RWaEzAiG)

**Comment by philipengberg** [comment]
OMG, Postman docs 😍

**Comment by philipengberg** [comment]
But what about my second question? 🙂

**Comment by jakewmeyer** [comment]
My feeling exactly ❤️

**Comment by jakewmeyer** [comment]
As far as the second question goes

Currently we can get launches with a mission name like:
[https://api.spacexdata.com/v3/launches?mission_name=TESS](https://api.spacexdata.com/v3/launches?mission_name=TESS)

One option is changing the v3 endpoint to accept a mission name param instead of flight number:
[https://api.spacexdata.com/v3/launches/TESS](https://api.spacexdata.com/v3/launches/TESS)

**Comment by philipengberg** [comment]
The name is just not guaranteed to be unique 😕What if all the endpoints that return references to missions return a list of objects like

```json
"missions": [
    {
        "name": "Iridium NEXT 7",
        "flight": 55
    },
    {
        "name": "SAOCOM 1A",
        "flight": 45
    }
]
```

Then a client can still show the name as preview and then use the ID to get the full thing.

**Comment by jakewmeyer** [comment]
Sounds good to me 👍

**Comment by jakewmeyer** [comment]
Capsules, Cores, and Ships have all been updated with this style 👍

**Comment by philipengberg** [comment]
You blow my mind every single day 😄

**Comment by philipengberg** [comment]
Works like a charm 💃
