### ISSUE TITLE
Landing attempts on /parts/cores

### ISSUE THREAD

**Issue by philipengberg** [r-spacex/SpaceX-API#160]
Is there a specific reason that `/parts/cores` only references each kind of attempt as a boolean instead of a count? A bit along the lines of https://github.com/r-spacex/SpaceX-API/issues/157, wouldn't that make more sense? 🤔

**Comment by jakewmeyer** [comment]
This is also on my list of things to update. Don’t really know why I choose a Boolean to represent it when we should be tracking the # of attempts instead 🤷🏼‍♂️

**Comment by philipengberg** [comment]
Perfect, sounds good 🙂

**Comment by jakewmeyer** [comment]
Updated

**Comment by philipengberg** [comment]
Fastest 🔫 in the West 💥
