### ISSUE TITLE
Add launches count to cores

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#162]
The 'launches' tag would count all previous successful or unsuccessful launches, not including the futures one, unlike the missions tag, which represents all past & futures launches.
```
{
    "core_serial": "B10XX",
    "block": X,
    "status": "active",
    ...
    "launches": 1
    ...
    "missions": [
      {
        "name": "PAST MISSION",
        "flight": X
      },
      {
        "name": "FUTURE MISSION",
        "flight": X
      },
    ],
    ...
  }
```
Thank you very much :)

**Comment by jakewmeyer** [comment]
Missions only contains past launches currently
