### ISSUE TITLE
'Landing intention' core tag

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#164]
Add a new tag to cores, specifying if it's going to land.
- True if is intended to be landed.
- False if is not intended to be landed.
- Null if we don't know if it's going to be landed.
 ```
{
    "core_serial": "B1045",
    "flight": 2,
    "block": 4,
    "reused": true,
    "land_intention": true | false | null,
    "land_success": null,
    "landing_type": null,
    "landing_vehicle": null
}
```

**Comment by jakewmeyer** [comment]
Added as `landing_intent` 👍

**Comment by philipengberg** [comment]
@jesusrp98 @jakewmeyer Couldn't that be inferred from `landing_vehicle != null`?

**Comment by jesusrp98** [comment]
When ```landing_vehicle == null``` the core is not intended to be landed. But when we speak about future launches, ```landing_vehicle == null``` could mean that we don't know if that vehicle is actually going to land or not.

**Comment by philipengberg** [comment]
But would we ever know that landing is intended without also knowing the landing type?

**Comment by jesusrp98** [comment]
For example, this is the core info from the Iridium NEXT 5 mission:
```
{
    "core_serial": "B1041",
    "flight": 2,
    "block": 4,
    "reused": true,
    "land_success": null,
    "landing_intent": false,
    "landing_type": null,
    "landing_vehicle": null
}
```
As you can see, all landing parameters are ```null``` because it wasn't intended to be landed. So ```landing_intent``` is false.

But there's futures launches where we don't know if SpaceX is intending to land the booster. So all landing tags are ```null```. This doesn't say if they intend to land the core or not, just that we don't know it right now.

So, when all land tags are ```null``` we can't infer if they intend, or intended, to land the booster. That's why we need the ```landing_intent```, to tell us that piece of information.

**Comment by philipengberg** [comment]
@jesusrp98 I 100% get your point. 

My question is - to you @jakewmeyer - will it ever be the case **in practice** that we *know* they will attempt to land it, **without** also knowing *how* they will attempt to land it?
