### ISSUE TITLE
Upcoming launches are not order by date

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#166]
Looking around the upcoming launches list, I noticed that many launches that have placeholder date, pointing at the first day of the month, are disordered.

**Comment by jakewmeyer** [comment]
Technically they are in the order as described in on the subreddit launch [manifest](https://www.reddit.com/r/spacex/wiki/launches/manifest). The partial dates represent launches without set times. The precision of the date is noted as `tentative_max_precision`.

A potential solution could be just storing the partial date as a string straight off the manifest ex. `2019 Feb 17` or `2018 Q4` for dates without times.

**Comment by jesusrp98** [comment]
Oh, my bad! Just using the `tentative_max_precision` could save me.
Thank you very much!
