### ISSUE TITLE
Flight 88

### ISSUE THREAD

**Issue by garyjacobs** [r-spacex/SpaceX-API#167]
Seems like Flight 88 is missing?
CRS-19 Should be flight_number 88 and not 89? Unless I'm missing something?

**Comment by jakewmeyer** [comment]
Looks like it would be 89 according to the [manifest](https://www.reddit.com/r/spacex/wiki/launches/manifest). The update script automatically reorders the flights according to the order on the manifest. Looks like they added a new flight to the manifest a day ago, but it wsn't added to upcoming launches yet.
