### ISSUE TITLE
Adding landing pads end-point

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#171]
The idea would be to implement a similar end-point as the launch pads one, but for landing pads. It would use the same tags, but adding new ones, such as landing type (RTLS or ASDS), attempted & successful landings and its Wikipedia link.
For floating landing pads' coordinates, using its ports' coordinates would be great.

Also, adding attempted & successful launches and its Wikipedia link to the launch pad end-point would be a pretty nice addition :)

**Comment by jakewmeyer** [comment]
Added to the todo list 👍

**Comment by jakewmeyer** [comment]
@jesusrp98 

Endpoint and data added and live. Check it out and let me know if you want to add/change any data 👍 

[https://api.spacexdata.com/v3/landpads](https://api.spacexdata.com/v3/landpads)

[https://api.spacexdata.com/v3/landpads/LZ-1](https://api.spacexdata.com/v3/landpads/LZ-1)

**Comment by jesusrp98** [comment]
The new endpoint is great! It has all the information we could ever need. And speaking of adding data, adding the Wikipedia link & attempted & successful launches to the launchpad endpoint would streamline the information if it's not too much to ask.
And again, thank you for your fast & great work developing this awesome API! :)

**Comment by jesusrp98** [comment]
Thank you @jakewmeyer!
