### ISSUE TITLE
[q] Is this official SpaceX data?

### ISSUE THREAD

**Issue by markvital** [r-spacex/SpaceX-API#173]
Is this data validated by SpaceX representative and if yes how often?
It would be great to see this info somewhere in the project description.

PS: I'm very thankful for this API, it saved me a lot of time.

**Comment by jakewmeyer** [comment]
This is not official data and is 100% fan run and fan collected. The majority of the data comes from the r/SpaceX subreddit [wiki](https://www.reddit.com/r/spacex/wiki/index).

**Comment by markvital** [comment]
@markvital have you thought about contacting SpaceX representatives and asking, if they are interested to validate it? 
Maybe it's possible to set up some process, where someone from their side validates changes once per week/per months.

This way we'll have more quality data.
