### ISSUE TITLE
Add More Explosions Data

### ISSUE THREAD

**Issue by markvital** [r-spacex/SpaceX-API#177]
Currently, there is only variable `launch_success`, that indicates launch failure/explosion.
It would be great to add more data, at least at which point of time (from countdown) and **altitude** did failure happen. Also it would be great to indicate type of failure eg. explosion/loss of mission/etc.

This data will allow to visualize partial trajectory before explosion:
![spacex exlosions](https://user-images.githubusercontent.com/742796/47948599-13eb0000-df3c-11e8-963a-da56b1e10766.png)

**Comment by jakewmeyer** [comment]
We could have some sort of results or outcome object with this kind of information, something that can describe details on success or details on failures.

**Comment by markvital** [comment]
Maybe something like this?

if case of success:
``` javascript
{
  launch_success: true
}
```


in case of failure:
```  javascript
{
  launch_success: false,
  launch_failure_details: {
    time: 0:33,     // time from countdown, could be negative (in case with AMOS-6 launch)
    altitude: 5681, // altitude on which failure happened, maybe this can be calculated from time?
    reason: "merlin engine failure"      // short description of main reason of failure
  }
}
```

**Comment by jakewmeyer** [comment]
Don't know if time from countdown will work will all cases, mainly Amos-6, because the explosion occurred right before the static fire test, not the launch.

**Comment by jesusrp98** [comment]
I'm going to lay down mi opinion here:

I think getting the altitude would be an easy task, since there's a lot of data from the SpaceX's launch failures in the internet.

The reason could be a simple message, just like in the @markvital example.

But the tricky thing is time. Not a problem in the first Falcon 1 launches & CRS-7 mission, but would be a problem in the Amos-6 mission. One solution could be using a '-1' in failures prior to T-0s.

**Comment by markvital** [comment]
@jesusrp98 -1 could be a solution for Amos-6. Won't people interpret it as "minus one second"? 

Why can't we give negative time for Amos-6 (for ex. -23,4576), which means actual time left to planned launch time. This will make everything clear.
All we need to know is planned launch time and actual time of explosion.

**Comment by jesusrp98** [comment]
That sounds good to me yes.

**Comment by jakewmeyer** [comment]
@markvital  Are you wanting altitude in km or m?

**Comment by markvital** [comment]
either way, km is fine for me

**Comment by jakewmeyer** [comment]
km it is 👍 

All data has been added

**Comment by markvital** [comment]
Wow, thank you!

**Comment by markvital** [comment]
> No altitude available for falcon 1 flight 1 unfortunately

Is it because they didn't have telemetry data?

Wikipedia says: "Impact occurred at T+41 seconds onto a dead reef about 250 feet from the launch site". 
Maybe it's possible to calculate approximate altitude somehow?
