### ISSUE TITLE
Gridfins/legs data is null for some future launches in 2019

### ISSUE THREAD

**Issue by markvital** [r-spacex/SpaceX-API#178]
Why some future launches have no gridfins and legs data?
```javascript
{
    //...
    gridfins: null,
    legs: null
}
```
My current understanding is that all future launches except maybe very-very few will intend to land and have both fins and legs installed, right?

<img width="1035" alt="screen shot 2018-11-03 at 5 16 17 pm" src="https://user-images.githubusercontent.com/742796/47954056-52110f80-df8e-11e8-96cd-13a5cdc9fc95.png">

**Comment by jesusrp98** [comment]
What I understand is when we don't know if the vehicle will be equiped with legs & gridfins, those tags should be null. But in the other hand, is mostly certain that all Block 5 Falcon 9 will be equiped with legs & gridfins. So is up to @jakewmeyer to decide.

**Comment by jakewmeyer** [comment]
Like @jesusrp98 said, if we know for sure it's a block 5, then both would be used. At some point SpaceX will start expending the block 5 cores after 10 launches or so each, but we're far from that at the moment.

**Comment by markvital** [comment]
I see. Didn't know about **Block 5**
