### ISSUE TITLE
Launch videos from different non-official YouTube channels

### ISSUE THREAD

**Issue by markvital** [r-spacex/SpaceX-API#179]
I noticed that some videos in `video_link` field point to different YouTube channels, rather than official [SpaceX youtube channel](https://www.youtube.com/channel/UCtI0Hodo5o5dUb67FeUjDeA). Why is that?

For instance videos for Falcon 1 Flight 1, 2, 3, and 5; Falcon 9 test flight; COTS 1; COTS 2; CRS-1; CASSIOPE; SES-8; CRS-3, CRS-7, Amos-6, etc. - have different youtube channels.

It would be great to unify those launches, because YouTube is famous for its copyright protection and one day someone could remove those video, which will result in broken links. It also results in appearance of annoying ads in non-spaceX videos.

**Comment by jakewmeyer** [comment]
Unfortunately the official SpaceX YouTube doesn't have many of the early videos. I just went back through and updated a few of the falcon 1 videos, but the first falcon 1 launch isn't on there.

**Comment by markvital** [comment]
Maybe it's stupid idea, but...
How about creating youtube channel "SpaceX-API" and re-uploading all missing videos there?
This way at least all the missing videos will be under the same use to minimize broken links in the future.

**Comment by jakewmeyer** [comment]
I'm open to this 👍

**Comment by jhpratt** [comment]
Make sure the videos are released under a license that allows for this if
you choose to follow through on that.

**Comment by roydondsouza** [comment]
Also, you can publish YouTube videos as "Unlisted " which can be accessed only with a link. This way it won't show up in public feeds.

**Comment by markvital** [comment]
> Considering that these videos have been up for 5-8 years without any copyright issues, I think the chances of broken links are extremely low.

True, however I would double check each of those videos, maybe we can consolidate it somehow. Right now we have too many different users, who owns those videos and we don't have control over them.
Even though broken links might not be an issue, ads are. Because they are uploaded by different users, some of them can decide to monetize them or youtube sometimes automatically attaches ads.

For example I see an ad in one of the videos:


<img width="1184" alt="screen shot 2018-11-13 at 3 06 39 pm" src="https://user-images.githubusercontent.com/742796/48415482-2a703300-e756-11e8-9d18-2fbda59a690e.png">


Kind of annoying :(


Maybe SpaceX could re-upload missing videos to their channel? Let me tweet them and ask...

**Comment by markvital** [comment]
I just noticed that **Falcon 1, launch 2** is uploaded to SpaceX youtube channel, but the link in API points to something else.

Someone needs carefully check each launch video, to see if it's present in the SpaceX channel, and compile a list of all the launches that are missing. 
Then we can tweet that list of missing launches to SpaceX and ask them to upload missing video. How about that?

I'll try to do it myself, when I have time, although I'm not the most attentive person (can miss something) need someone very-very attentive.

**Comment by markvital** [comment]
@jakewmeyer do you usually read closed issues?
