### ISSUE TITLE
intelsat 35e launch is duplicated

### ISSUE THREAD

**Issue by waterskier2007** [r-spacex/SpaceX-API#18]

**Comment by jakewmeyer** [comment]
Duplicated where?

**Comment by waterskier2007** [comment]
https://api.spacexdata.com/launches

Unless I am mistaken, the first and last objects in the list are both Intelsat 35e

**Comment by HarvsG** [comment]
I am also seeing this

**Comment by jakewmeyer** [comment]
Should be fixed, Thanks.
