### ISSUE TITLE
Link launch videos to specific events

### ISSUE THREAD

**Issue by markvital** [r-spacex/SpaceX-API#180]
It would be great to link videos to specific launch events:
- countdown
- explosion (if occurs)
- first stage separation
- second stage separation
- boosters landing
- payload drop (fairing separation)
- dragon docking (not sure this is actually filmed)

This will allow to build some sort of visual browser, where people could much faster analyze a lot of launches by watching youtube videos.
All we need is to save video time in seconds for each event, so developers can pass it to youtube API.

This would probably easier to do, if all video will be unified, pointing to official SpaceX youtube channel, as I described in #179

**Comment by markvital** [comment]
For ex. data could look something like this:
``` javascript
{
  flight_number: 22,
  // ...
  video_events: {
   countdown : 
      time: 345, // could  be in second from video start or hh:mm:ss
      video: "https://youtu.be/nBwAYT_ogj4" // we could use video link for each specific events, if it's not present in the main video or use default value from video_link
    },
    first_stage_sep : {
      time: 544,
    },
    booster_landing : {
      time: 1211,
    },
    payload_drop_off : {
      time: 6232,
      video: "some_other_video_link"
    }
  }
}
```

or event like this, if all events could be found in one video:
``` javascript
{
  flight_number: 22,
   // ...
  video_events: {
    countdown: 0;
    first_stage_sep 544,
    booster_landing : 1211,
    payload_drop_off : 6232
  }
}
```

**Comment by jakewmeyer** [comment]
Will probably go with the second option, because all the events except dragon docking should be contained in the same video.

We'll need to decide on a standardized list of possible events to include. The subreddit currently tracks the following timeline for each launch:

![Image](https://i.imgur.com/KChd55N.png)

**Comment by markvital** [comment]
I vote for Liftoff, Stage separation, Fairing separation, Payload deploy, Landing success.

I don't see explosions there and first stage landing failure.

**Comment by markvital** [comment]
For my  infographic this is what makes sense:

<img width="678" alt="screen shot 2018-11-08 at 12 40 42 am" src="https://user-images.githubusercontent.com/742796/48166069-25dbf280-e2f0-11e8-8861-f45d37d92db0.png">

**Comment by jakewmeyer** [comment]
Sounds good 👍 

For the times, do you want the exact moment the event happens? Or just before?

**Comment by jakewmeyer** [comment]
@roydondsouza  Pretty sure this only involves the video, not the actual launch timeline. Only used it as an idea for fields to possibly include.

**Comment by roydondsouza** [comment]
@jakewmeyer I think its very clear as you are using the label `video_events`

**Comment by markvital** [comment]
> For the times, do you want the exact moment the event happens? Or just before?

10 seconds before the event happens, so users will have few seconds to understand what's going on

**Comment by markvital** [comment]
Actually, I think the best way is to return time of the exact moment in API, and then add those 10 seconds or however needed later in the code. 
This will give some flexibility for the developers, because different events require different time to understand what's going on from video.
For example: countdown is always 10 seconds before, fairing separation it's enough to show 3 seconds before, for boosters landing 5-7 seconds before...

**Comment by jakewmeyer** [comment]
Gotcha. This will probably take a bit of time to complete, so bear with me 👍

**Comment by jeroenboumans** [comment]
> Will probably go with the second option, because all the events except dragon docking should be contained in the same video.
> 
> We'll need to decide on a standardized list of possible events to include. The subreddit currently tracks the following timeline for each launch:
> 
> ![Image](https://camo.githubusercontent.com/5398423beba4566240f8700150734ae0fbed2493/68747470733a2f2f692e696d6775722e636f6d2f4b43686435354e2e706e67)

This is awesome, I was thinking for posting a feature request like this this week haha!

Would be great to have these timetables from the presskit-PDF at the exact timestamps. So no 10 sec. extra. This should be done client-sided IMO. @jakewmeyer shall I put that request in another issue, since this issue is all about the video timestamps?

**Comment by jakewmeyer** [comment]
@jeroenboumans Wouldn't most of these times line up exactly with the ones on the presskit?

Because @markvital is adding the video delay after the fact, both of the times should b similar, if not the same.

**Comment by jeroenboumans** [comment]
@jakewmeyer yes, that is correct. If these could also be provided via the API, instead of ...
1. downloading the presskit 
2. extract the tabular data 
3.  upload/import it via a secondary API

...that would come in handy, a lot 👍 
If this data doesn't have your preference I'll add it to the secondary API, that's no problem. I was just thinking this could be of use for other SpaceX app clients as well. :)

**Comment by jakewmeyer** [comment]
Sounds good, here's saocom-1 as an example: 

```json
{
  "timeline": {
    "webcast_liftoff": 1019,
    "go_for_prop_loading": -2280,
    "rp1_loading": -2100,
    "stage1_lox_loading": -2100,
    "stage2_lox_loading": -960,
    "engine_chill": -420,
    "prelaunch_checks": -60,
    "propellant_pressurization": -60,
    "go_for_launch": -45,
    "ignition": -3,
    "liftoff": 0,
    "maxq": 59,
    "meco": 140,
    "stage_sep": 144,
    "second_stage_ignition": 151,
    "boostback_burn": 156,
    "fairing_deploy": 168,
    "first_stage_entry_burn": 357,
    "first_stage_landing": 466,
    "seco": 607,
    "payload_deploy": 757
  }
}
```

`webcast_liftoff` references the time in the webcast when liftoff occurs. This should make it easy to find the events in the timeline by adding or subtracting times from it.

**Comment by jeroenboumans** [comment]
Thanks @jakewmeyer ! Will look forward implementing this!

**Comment by adrianmartinezverax** [comment]
Hello guys, I am Adrian Martinez, I am 18 years old Mobile App developer. I really Need your help on the API of SpaceX Go

**Comment by jesusrp98** [comment]
@adrianmartinezverax Hey! If you have issues related to SpaceX GO! directly, it's preferable if you contacted me privately.
Will solve any problems you have with the app no problem :)

**Comment by adrianmartinezverax** [comment]
How can i put my own information in the SpaceX Go App, like on rockets, launches, mission and everything. So they should be showing in the app. When i change the the link in url.dart 'https://api.spacexdata.com/v3 its not showing anything. So how can i remove it so i can put my own information. And by the way i have never done hybrid apps before that fetch data from the internet. And please tell me steps by steps and i will do it. 
Thanks Thursday, 07 February 2019, 05:52PM +02:00 from Chechu  notifications@github.com :

**Comment by jakewmeyer** [comment]
@jesusrp98 @jeroenboumans @markvital All the timelines have finally been added 👍

**Comment by jeroenboumans** [comment]
Thanks @jakewmeyer looking forward to build a nice feature on top of this! :) (**putting it on the backlog**)

**Comment by waruss321** [comment]
Has this been removed in v4?

**Comment by jakewmeyer** [comment]
Yes, mostly because it was tough to automate, and SpaceX stopped giving press kits with timelines on them.

An alternative option might be parsing the timeline used in the reddit launch threads ([Like this one](https://www.reddit.com/r/spacex/comments/iiwlch/rspacex_saocom_1b_launch_discussion_updates_thread/)). If I can parse these reliably enough, we could bring this back. Only caveat is the timeline is updated live, so it wouldn't be as useful for planning purposes.
