### ISSUE TITLE
Difference in launchdates - SSO-A mission

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#184]
Hi @jakewmeyer ,

I've noticed there is a difference in launch dates for mission SSO-A (flightnr 71):
```
...
"launch_date_unix": 1514764800,
"launch_date_utc": "2018-01-01T00:00:00.000Z",
"launch_date_local": "2017-12-31T16:00:00-08:00"
...
```
Since I don't have access to the mongodb anymore, could somebody fix this please?

Thanks! 👍

**Comment by jakewmeyer** [comment]
Looks like because the launch was delayed, the wiki has it as `2018 TBD` currently. Looks like it just set the max precision wrong, it should be year instead of month. 

Otherwise the date is correct

**Comment by jeroenboumans** [comment]
Thanks for the feedback jake! Could we add a property to the data informing us that the corresponding launch date currently is TBD or making the launchdate more precise?

**Comment by jakewmeyer** [comment]
Well technically every upcoming launch is TBD to some extent 🤷‍♂️ 

I'm okay with adding the tbd boolean field if we want to. If the wiki [launch manifest](https://www.reddit.com/r/spacex/wiki/launches/manifest) NET date contains TBD at all, I'll have it set as true.

**Comment by jeroenboumans** [comment]
Thanks Jake, appreciate it! :relaxed:

**Comment by jesusrp98** [comment]
Shouldn't be SSO-A the last 2018 mission to launch in 2018 now? Reading the upcoming launches list, I see that the launches that have a more concrete launch date are before the one that have a more vague launch date.

**Comment by jakewmeyer** [comment]
Order should be consistent with the order on the wiki. Pretty sure it'll launch the last week of November. If they change the order on the wiki, the API order will automatically update as well.

**Comment by jesusrp98** [comment]
OK that's great. Thanks!

**Comment by jakewmeyer** [comment]
@jeroenboumans do you want the tbd field? Or is it fine the way it is?

**Comment by jesusrp98** [comment]
What would be the difference between `is_tentative` & a hypothetical `tbd` field?

**Comment by philipengberg** [comment]
Correct, I use it to show **`NET Nov. 2018`** fx, depending on the precision level.

**Comment by jesusrp98** [comment]
Using the `TBD` tag the same way used in the [launch manifes](https://www.reddit.com/r/spacex/wiki/launches/manifest) would be a good idea. For example, when a launch is postponed indefinitely, like in this case.

**Comment by jeroenboumans** [comment]
@jakewmeyer @jesusrp98 I'd say leave the launch dates intact. End applications decide themselves whether they use the `TBD` property or not 👍

**Comment by jesusrp98** [comment]
Agree.

**Comment by jakewmeyer** [comment]
Field is added and live. What all should we consider to be TBD?

**Comment by jhpratt** [comment]
IMO if we don't know the exact NET day, regardless of whether the time is
unknown. The date is what people will likely be interested in in most
cases, anyways.

**Comment by jeroenboumans** [comment]
I agree with @jhpratt :)

**Comment by jakewmeyer** [comment]
Gotcha

Will consider dates like `2019 Jan`, `2019`, `2019 Q1`, `2019 H1` as TBD

Dates like `2019 Feb 17`, or `2019 Jan 8 04:57` won't be TBD

**Comment by jakewmeyer** [comment]
@philipengberg Also made a slight change to when `is_tentative` is set. If a launch has a time available, `is_tentative` will be false. Previously it was set as true until the moment of launch.

Felt like the field wasn't being used properly, but this should fix that.

**Comment by jeroenboumans** [comment]
awesome, thanks @jakewmeyer ! 👍
