### ISSUE TITLE
Add reusable tag to second stages

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#185]
Add the same tag the `first_stage` section has in the `/rockets` endpoint to the `second_stage` section. An example for Falcon 9 could be:

```
{
    "first_stage": {
      "reusable": false,
      "engines": 9,
      ...
    },
    "second_stage": {
      "reusable": false,
      "engines": 1,
      ....
      },
}
```

Also, since we don't know `burn_time_sec` from BFR yet, shouldn't they be `null` instead of `0` seconds?

**Comment by jesusrp98** [comment]
Also, I've noticed that Falcon Heavy's second stage doesn't have `fuel_amount_tons`, which is kinda weird. That tag could be the same as Falcon 9's.

**Comment by jakewmeyer** [comment]
Added and corrected 👍

**Comment by jesusrp98** [comment]
Updated data isn't showing to me. Is the information cached in some sort, and so, I should wait until data is updated?

**Comment by jakewmeyer** [comment]
Sorry about that, forgot to clear the cache for those endpoints.

Should be showing correct now

**Comment by jesusrp98** [comment]
Great. Thanks!
