### ISSUE TITLE
Request for offset in endpoints

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#187]
Hi @jakewmeyer,

Would it be possible to add an offset option in the request that can be used for pagination? Currently `limit` is an option but no offset can be given with the request. This way the impact of the launches query can be optimised in performance and load on both client and server side.

For example:
- Return the 3rd set with as size of 5 results of all launches:
`https://api.spacexdata.com/v3/launches?offset=2&limit=5`

- Return the first set with as size of 5 results of all launches:
`https://api.spacexdata.com/v3/launches?offset=0&limit=5`
`https://api.spacexdata.com/v3/launches?limit=5`

Cheers!
Jeroen

**Comment by jakewmeyer** [comment]
Should be easy to add 👍 

I have finals until Wednesday, so I should be able to add this later in the week.

**Comment by jeroenboumans** [comment]
Thanks again @jakewmeyer, appreciate it! Good luck with your finals! 👍🎉

**Comment by jakewmeyer** [comment]
Added and live 👍 

[https://api.spacexdata.com/v3/launches?limit=1&offset=5](https://api.spacexdata.com/v3/launches?limit=1&offset=5)

Available on any endpoint that can return multiple results. Docs have been updated as well.

**Comment by felipediogo** [comment]
Shouldn't you close this issue then? @jakewmeyer

**Comment by jakewmeyer** [comment]
Yes, hadn't seen it until now

@jeroenboumans sounds good 👍
