### ISSUE TITLE
Iridium NEXT Mission 2 launch time

### ISSUE THREAD

**Issue by quadrplax** [r-spacex/SpaceX-API#188]
According to the API, the launch occurred at 06:25 local time and 13:25 UTC:
```
	"launch_date_unix": 1498397100,
	"launch_date_utc": "2017-06-25T13:25:00.000Z",
	"launch_date_local": "2017-06-25T06:25:00-07:00",
```
Based on what the hosts say in the webcast, the lighting, its description, and the Wikipedia page, however, the launch occurred at 13:25 LOCAL time and 20:25 UTC:

[https://www.youtube.com/watch?v=ei3nGWD4d5A](https://www.youtube.com/watch?v=ei3nGWD4d5A)

To put it simply, the local time was mistaken for the UTC time. The unix timestamp is also wrong as a result. I would like for this to be fixed as it makes my calculation for the shortest time between any two launches incorrect. Thanks!

**Comment by jakewmeyer** [comment]
Fixed 👍
