### ISSUE TITLE
Cores & capsules order

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#190]
When you order cores or capsules using the `order` querrystring, all vehicles where `original_launch` is `null` appear in the wrong order.

Using `order=desc`, I assume that those vehicles should be at the start of the output, since they'll be launch in the future.

And then, when `order=asc`, those vehicles should go to the end of the list.

Thanks.

**Comment by jakewmeyer** [comment]
This happens because mongodb and other databases generally treat null as the lowest possible value, hence why they show up first when in ascending order. 

Should be able to fix this easily by splitting it into 2 queries, 1 for non null launch dates, and 1 for those will null haunch dates, and concatenating them together depending on the order.

**Comment by jesusrp98** [comment]
> /cores/upcoming and /cores/past would make sense, but /cores should probably contain all cores, just in a corrected order.

So `/cores/upcoming` would have all null launch date cores, and `/cores/past` all non-null launch date cores.

And what about `/cores` then? What would be the difference between what we have now, and the updated one?

**Comment by jakewmeyer** [comment]
`/cores` would have both null and non null launch date cores, with the order fixed

**Comment by jesusrp98** [comment]
Yeah, that's great!

**Comment by jakewmeyer** [comment]
@jesusrp98 Added and live

[/cores](https://api.spacexdata.com/v3/cores)
[/cores/upcoming](https://api.spacexdata.com/v3/cores/upcoming)
[/cores/past](https://api.spacexdata.com/v3/cores/past)

[/capsules](https://api.spacexdata.com/v3/capsules)
[/capsules/upcoming](https://api.spacexdata.com/v3/capsules/upcoming)
[/capsules/past](https://api.spacexdata.com/v3/capsules/past)

Play around with it a bit, and let me know if you find anything out of place

**Comment by jesusrp98** [comment]
Both endpoints works great!

Thank you very much! :1st_place_medal:
