### ISSUE TITLE
Add launch window to launches

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#191]
Add a `launch_window` tag, holding the launch window in seconds. For example, the GPS III SV01's launch window is 26 minutes. This information can be located in its [reddit thread](https://www.reddit.com/r/spacex/comments/a71wyn/rspacex_gps_iii2_official_launch_discussion/).

- For instantaneous launches, like CRS missions, a `0` would be ideal.
- If the launch window is unknown, `null` would be the best option.

Here is an example of how could it look like:
```
{
  "flight_number": 73,
  "mission_name": "GPS III SV01",
  "launch_window": 1560,
  ...
}
```

Thanks!

**Comment by jakewmeyer** [comment]
Not sure how many actually have a window listed, just from my initial looking, most appear to have an instantaneous launch time, rather than a window.

**Comment by jesusrp98** [comment]
I've checked both Reddit threads & official press kits and, of what I could see, all of them have a launch window listed. I mean, all launches have a launch window, instantaneous or not. 
If the launch is instantaneous, the tag `launch_window` would be `0` seconds.

**Comment by jakewmeyer** [comment]
Sounds good, it's in the pipeline 👍

**Comment by jakewmeyer** [comment]
Launch windows have been added 👍

**Comment by jesusrp98** [comment]
Great! Thank you so much!
