### ISSUE TITLE
Current webcast URL

### ISSUE THREAD

**Issue by pvegh** [r-spacex/SpaceX-API#192]
What do you think of an endpoint to learn the location of the current webcast?
Which is normally available at https://www.spacex.com/webcast
and currently would be https://www.youtube.com/watch?v=yRiLPoy_Mzc
Additionally it would be nice to know if this is for a mission currently in progress.

I'm thinking of something like: app checks this endpoint and can tell the user, "hey there is a missions live now, and here's the video"

Not perfectly sure about the details yet, I might have a more exact idea soon.

**Comment by jesusrp98** [comment]
One solution could be using the `filter` tag in the URL: https://api.spacexdata.com/v3/launches/next?filter=links. 
It just downloads the specific `links` tag, then look for `video_link`.

**Comment by pvegh** [comment]
Alright I'll try it for the next launch and see if the video link is available in time.
I'm just prototyping a new app, no time pressure

**Comment by jakewmeyer** [comment]
Generally the webcast link is added 24 hours or so before the launch, so you should have plenty of time.

Adding on to what @jesusrp98 said, you could even go a step further and use [https://api.spacexdata.com/v3/launches/latest?filter=links/video_link](https://api.spacexdata.com/v3/launches/latest?filter=links/video_link), which only gives you the webcast link.

**Comment by jakewmeyer** [comment]
Also, if the latest webcast is always available in the page you linked, we could maybe write a script to grab that link for the most up to date source.
