### ISSUE TITLE
BUG - /v2/info returns wrong data

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#195]
Hi @jakewmeyer ,

Don't know why this changed but the info endpoint of v2 returns Tesla Roadster data. I'm still using some of the v2 endpoints and would appreciate if these remain live.

https://api.spacexdata.com/v2/info

**Comment by jakewmeyer** [comment]
It's returning correctly for me, but it was broken yesterday. Looks like the order of the documents switched, and the query depended on the order being correct. Should be fixed.

**Comment by jeroenboumans** [comment]
Thanks @jakewmeyer!
