### ISSUE TITLE
Add youtube_video_id where youtube link is set

### ISSUE THREAD

**Issue by pvegh** [r-spacex/SpaceX-API#196]
If a player needs the  youtube videoId instead of the full URL, currently we need to parse the full youtube link on the client side. I think it would be better to do this once on the API side.

Maybe something straightforward like:
"video_link": "https://youtu.be/yRiLPoy_Mzc",
"youtube_video_id": "yRiLPoy_Mzc",

What do you think?

**Comment by jakewmeyer** [comment]
In addition to adding this field, I'll add a new script to poll [https://www.spacex.com/webcast](https://www.spacex.com/webcast) for the link as soon as the new one is posted. Should be able to get the link and video id updating completely automated 👍

**Comment by jakewmeyer** [comment]
@pvegh video id's have been added 👍

**Comment by pvegh** [comment]
Cool, looks exactly like what I had in mind..
I just switched my implementation to the new **youtube_id**.
Thank you Jake!
