### ISSUE TITLE
Dragons endpoint returns them in the wrong order

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#199]
The `/dragons` endpoint returns the available Dragon capsules (Dragon 1 & 2) in the wrong order. It should be first Dragon 1, and then Dragon 2.
For example, the `/rockets` endpoint returns rockets from Falcon 1 to BFR by default.

**Comment by jakewmeyer** [comment]
Fixed 👍

**Comment by jesusrp98** [comment]
Great!
