### ISSUE TITLE
Add crew endpoint

### ISSUE THREAD

**Issue by jakewmeyer** [r-spacex/SpaceX-API#202]
Endpoint: `https://api.spacexdata.com/v3/crew`

Things to decide on:
- [ ] Crew schema
- [x] Integration with launches

**Comment by AlbericTrancart** [comment]
Any update on this? :slightly_smiling_face: 

Proposition:

```
[
  {
    person: "Bob Behnken",
    organization: "NASA",
    flights: [{
      flight_number: 83,
      launch_date: "2020-01-01"/null,
      return_date: "2020-06-01"/null,
      destination: "ISS",
    }],
  }
]
```

**Comment by philipwhiuk** [comment]
It's a payload property I would think.

The specificity in terms of the stage is likely to be important here.

For Demo-2 it's likely that the NASA astronauts will arrive on Crew Dragon and then leave on the same Demo-2 Crew Dragon. But it's also likely (indeed it's the normal behaviour I think for ISS) that you leave on a different rocket.

There's not much on return-to-Earth data in a payload right now - it's just 

```
"mass_returned_kg":905,
"mass_returned_lbs":1995
```

For Crew Dragon you also have both unpressurized and pressurized mass (if we get the breakdown). You need crew_sent, crew_returned. Not sure if flight_time is:

* Earth -> Earth
* Earth -> ISS
* Stage Sep -> ISS
* Stage Sep -> Earth

If it's just Stage Sep -> ISS you want to have ISS -> Earth somewhere.

Also there's no way currently to get ISS arrival date-time, ISS departure date-time, Earth arrival date-time as far as I can tell. That's also relevant for CRS missions.

**Comment by jakewmeyer** [comment]
Planning on getting this in place this weekend, at least an initial version. 

@philipwhiuk 
* Planning on adding a top level `crew` array with the names of crew at launch. In addition, I can add a `crew_returned` array to the crew dragon payload, along with other crew dragon applicable info.

* `flight_time` currently is time from liftoff to splashdown

@AlbericTrancart 
Will likely use a missions array to keep track of flights like the existing setup for cores/capsules
```json
[
  {
    "person": "Bob Behnken",
    "organization": "NASA",
    "missions": [
      {
        "name": "CRS-12",
        "flight": 45
      },
      {
        "name": "CRS-17",
        "flight": 78
      }
    ],
  }
]
```

**Comment by mighty-phoenix** [comment]
Can I work on this issue?

**Comment by jakewmeyer** [comment]
@mighty-phoenix sure, endpoint is in place, data just needs to be collected and added to the database.

**Comment by mighty-phoenix** [comment]
@jakewmeyer I am new to this project. Can you please tell me how I can proceed with collecting and adding the data to the database?
