### ISSUE TITLE
Mission #75 wrongly added to MR STEVEN

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#203]
The latest SpaceX's mission, `Nusantara Satu (PSN-6) / S5 / Beresheet`, has been wrongly added to the MR STEVEN's missions list:
```
  "missions": [
    {
      "name": "KoreaSat 5A",
      "flight": 50
    },
    ...
    {
      "name": "Nusantara Satu (PSN-6) / S5 / Beresheet",
      "flight": 75
    }
  ]
```

**Comment by jakewmeyer** [comment]
Should be fixed now. Looks like I forgot to remove it from the ships array in the launch, so the ships update script thought it was part of the mission.

**Comment by jesusrp98** [comment]
Great, good job!
Thanks :)
