### ISSUE TITLE
Wrong last launch ID

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#204]
I've noticed that the last launch present in the `launches/upcoming` endpoint has 107 has the `id`, and before that there's a launch with ID 91. Shouldn't the last launch have an `id` of 92?

**Comment by jakewmeyer** [comment]
Technically it's correct according to the [manifest](https://old.reddit.com/r/spacex/wiki/launches/manifest), it just got moved to 2020.

Going to remove it for the time being until I add more launches to fill in the gap

**Comment by jesusrp98** [comment]
Great! I looked weird to me that one launch had 91 as id, and the next one 107.
