### ISSUE TITLE
Missing fairing details in upcoming Falcon Heavy launches

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#205]
In both ArabSat 6A & STP-2 upcoming flights, the `fairings` field is `null`:
```
"fairings": null
```

But in most upcoming 'non-Dragon' launches, the `fairings` parameter has some data:
```
"fairings": {
  "reused": false,
  "recovery_attempt": null,
  "recovered": null,
  "ship": null
}
```

**Comment by jakewmeyer** [comment]
Fixed

**Comment by jesusrp98** [comment]
Great!

**Comment by jesusrp98** [comment]
@jakewmeyer Although this issue is fixed on the ArabSat 6A launch, I've noticed that it's still a problem on the STP-2 mission.

**Comment by jakewmeyer** [comment]
Updated

**Comment by jesusrp98** [comment]
Great. Now both of them are fixed! :)
