### ISSUE TITLE
Update Dragon 2 first flight date

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#206]
Currently, the Dragon 2 first flight date is November 1st, 2018. Now, as the Demo-1 mission has been successfully launch, it should be March 2nd, 2019.

Also, the `active` parameter should be `true`.

**Comment by jakewmeyer** [comment]
Updated

**Comment by jesusrp98** [comment]
:)

**Comment by jesusrp98** [comment]
@jakewmeyer Shouldn't be the 'First flight' date March 2nd instead of NET July? That day was its first flight. Like Falcon Heavy, its maiden launch was a demo mission, and its first flight is February 6th.

**Comment by jakewmeyer** [comment]
Whoops, looks like I grabbed the date from DM-2 instead. Should be correct now.

**Comment by jesusrp98** [comment]
I don't know if it's something related to data caching, but it's still July 2019 for me :/

**Comment by jakewmeyer** [comment]
Fixed. Got the date wrong in /capsules and /dragons, only updated capsules.

**Comment by jesusrp98** [comment]
Great!
