### ISSUE TITLE
Payload reuse meaning

### ISSUE THREAD

**Issue by beckyconning** [r-spacex/SpaceX-API#207]
`rocket.*.reused` seems to refer specifically to fairing reuse
`rocket.*.cores.reused` seems to refer to core reuse

i'm not sure what `rocket.*.payloads.*.reused` means. 

each `rocket.*.payloads.*` has information about the payload itself such as who is the customer. does it refer to whether the payload itself was reused? if so is there not meant to be some other information about second stage reuse?

<img width="848" alt="screen shot 2019-03-02 at 6 24 15 pm" src="https://user-images.githubusercontent.com/457901/53685966-74871f80-3d19-11e9-98eb-801409b823a1.png">

as shown in these charts there is no information about first and second stage reuse other than core and payload reuse.

**Comment by jakewmeyer** [comment]
The payload reused field is really only applicable to dragon at this point, but could also be applicable to another mission like [X-37 B](https://en.wikipedia.org/wiki/Boeing_X-37).

`rocket.first_stage.cores.reused` = core reuse
`rocket.second_stage.payloads.reused` = payload reuse
`rocket.fairings.reused` = fairing reuse

**Comment by beckyconning** [comment]
thanks for your reply!

so there are no other parts of the first and second stages which can be reused?

**Comment by jakewmeyer** [comment]
Not currently, but with [super heavy](https://en.wikipedia.org/wiki/BFR_(rocket)) the entire 2nd stage is reusable. For those we might need to add a reused field to `rocket.second_stage` since starship isn't technically a "payload".

**Comment by beckyconning** [comment]
also you mentioned that
 
> The payload reused field is really only applicable to dragon at this point

but i've noticed that the `Orbcomm-OG2-M2` is listed as reused on `December 22nd 2015`

**Comment by beckyconning** [comment]
also `CRS-4` is marked as reused.

although i suppose that spacecraft was eventually reused it wasn't a reused component of that launch which makes the data much less useful.

having an id for spacecraft seems more useful than retrospectively marking past flight data as containing reused components as we can then easily know which flights contained reused components and graph how reuse changes over time.

**Comment by jakewmeyer** [comment]
Corrected both 👍 

Not against adding a unique payload id, but currently the only reused payloads are dragon capsules, and each should have `cap_serial` which should allow for tracking over time.

AFAIK there's no reused payloads planned other than dragon at this time.

**Comment by beckyconning** [comment]
thank you! that is very helpful and makes my weekend far more pleasant.

does this reuse chart seem accurate now?

<img width="853" alt="screen shot 2019-03-03 at 12 42 47 am" src="https://user-images.githubusercontent.com/457901/53689424-69e67d80-3d4d-11e9-89e0-75a544f9aaa2.png">

**Comment by beckyconning** [comment]
I wonder if the same retrospective reuse semantic is in place for the rest of the launch records? Did SpaceX really reuse nine cores and four payloads so far this year?

**Comment by beckyconning** [comment]
The core count of 14 in 2018 seems more like the total for all time at that point rather than the total for that year.

**Comment by beckyconning** [comment]
If the rest of the reuse data consistently uses the retrospective reuse semantic then it may be preferable to mark CRS-4 as reused until all the reuse data can be updated to the more valuable state of the universe at the time of launch semantic.

**Comment by beckyconning** [comment]
At the moment I'm reasonably convinced that we're just hiding the clearest symptom of a wider problem with reuse data.

**Comment by beckyconning** [comment]
I'm going through and checking reuse data against news publications now.

**Comment by beckyconning** [comment]
Core reuse data looks good.

Checking payload reuse data now.

**Comment by beckyconning** [comment]
CRS-11 is marked as unused but it was reused

**Comment by beckyconning** [comment]
Thinking of which I should probably check the cores which weren't marked as reused as well.

**Comment by beckyconning** [comment]
Apart from CRS-11 which should be marked as reused the payload reuse data seems correct now.

**Comment by beckyconning** [comment]
Core data looks good. I'm going to close this issue and open a new one for CRS-11.
