### ISSUE TITLE
CRS-11 payload was reused but not marked as such

### ISSUE THREAD

**Issue by beckyconning** [r-spacex/SpaceX-API#209]
https://www.spacex.com/sites/spacex/files/crs11finalpresskit.pdf

"The Dragon spacecraft being used to support the CRS-11 mission previously resupplied the International Space Station on SpaceX’s CRS-4 mission in September 2014."

I'm making a video about using this API related to this data today so if this could be updated it would make a big positive difference to me.

Thanks!

**Comment by jakewmeyer** [comment]
Fixed, thanks for catching it
