### ISSUE TITLE
Inconsistent nomenclature

### ISSUE THREAD

**Issue by HarvsG** [r-spacex/SpaceX-API#21]
In: https://api.spacexdata.com/launchpads
SLC 40 is given as
```
      "id": "ccafs_slc_40",
      "full_name": "Cape Canaveral Air Force Station Space Launch Complex 40",
```
However in https://api.spacexdata.com/launches
`"launch_site": "CCAFS LC-40"`
The different naming structure makes comparisons and between the different API topics difficult. For example, if one wanted to get information about the launch site Amos-6 flew from `CCAFS LC-40` then the user's code must translate it to `ccafs_slc_40`

and also
`"launch_site": "KSC LC39A"`
notice the different use of `-`

**Comment by jakewmeyer** [comment]
Agreed, I'll go through and make it consistent

**Comment by jakewmeyer** [comment]
Should be in line with the launchpad data now

**Comment by HarvsG** [comment]
https://api.spacexdata.com/launches/upcoming
Is also in need of the same fix.

**Comment by jakewmeyer** [comment]
Fixed 👍
