### ISSUE TITLE
Day.js official UTC plugin

### ISSUE THREAD

**Issue by xxyuk** [r-spacex/SpaceX-API#210]
In dayjs v1.8.9 there is a packed UTC plugin, you could simply `import UTC from 'dayjs/plugin/utc'`, to set Day.js in UTC mode.

We might could give it a try, since the size is pretty small compare to momentjs.

**Comment by jakewmeyer** [comment]
Looks like the only issue would be with the following:

```moment(date, ['YYYY MMM D HH:mm Z', 'YYYY MMM D Z', 'YYYY MMM Z', 'YYYY Q Z', 'YYYY Z'])```

As far as I can tell, the CustomParseFormat plugin only supports a single format passed into it. Also would need support for the `Q` quarter field.

I don't see an official timezone plugin either, but it looks like there's a workaround with the standard Date() functions.

**Comment by xxyuk** [comment]
Yes, you could check the doc here, https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#utc

**Comment by jakewmeyer** [comment]
Still don't see a solution for the first problem. 

I need to be able to parse dates in a variety of [predefined formats](https://momentjs.com/docs/#/parsing/string-formats), and it doesn't look like dayjs supports that.

If it gets added in the future, I'd be happy to reconsider, but this is a big convenience feature I'm unwilling to trade for a small reduction in package size.

I'd also like to see an official timezone plugin. I know that workarounds exist, but I think a date/time library should support it out of the box, even it's small wrapper methods over the std lib ones.

**Comment by xxyuk** [comment]
Maybe we could do a simple for loop using `CustomParseFormat` to test the list os known formats

**Comment by jakewmeyer** [comment]
If it's a simple solution, why can't it be added to dayjs?
