### ISSUE TITLE
Two launches with same flight_number

### ISSUE THREAD

**Issue by feareoc** [r-spacex/SpaceX-API#214]
It appears that there are two launches with the same `flight_number`. Both missions "GPS IIIA-3" and "CRS-19" have `flight_number` 89, and there is no launch with `flight_number` 90. I suppose CRS-19 should in fact have `flight_number` 90

**Comment by jakewmeyer** [comment]
Corrected. Looks like the flight name was updated in the manifest and I didn't catch it.
