### ISSUE TITLE
Is there anyway to know which values may return `null`?

### ISSUE THREAD

**Issue by squarefrog** [r-spacex/SpaceX-API#215]
Taking `Capsule` for example, it's fair to assume `original_launch` could be `null`, and `capsule_id` should never be `null`.

However, is there a definitive way to know whenter an attribute is optional or nullable?

**Comment by jakewmeyer** [comment]
Safe to assume that anything could be null, except any id fields

**Comment by squarefrog** [comment]
Yikes, ok might have to rethink how I consume this API. Thanks for the response.
