### ISSUE TITLE
Arabsat 6A core and boosters serial numbers are wrong

### ISSUE THREAD

**Issue by marcozambi** [r-spacex/SpaceX-API#217]
The core and boosters serial numbers for FH Arabsat 6A ("_id": "5b93d10ac52b5303f4a5ebc0") are wrong.
According to the dedicated [reddit launch campaign](https://www.reddit.com/r/spacex/comments/b0kscl/arabsat6a_launch_campaign_thread/) they should be Center Core: B1055.1 // Side Booster 1: B1052.1 // Side Booster 2: B1053.1

**Comment by jakewmeyer** [comment]
Updated 👍
