### ISSUE TITLE
Wrong landing counts on some cores

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#218]
I've noticed that some cores have wrong attempt & landing tags.
For example, core B1051:
```
"rtls_attempts": 0,
"rtls_landings": 0,
"asds_attempts": 0,
"asds_landings": 1,
```
It has one successful 'ASDS' landing, but no attempt.

Core B1048:
```
"rtls_attempts": 1,
"rtls_landings": 1,
"asds_attempts": 1,
"asds_landings": 2,
```
It has two successful 'ASDS' landings, but only one attempt.

Those are the one I've spotted that have wrong landing counts.
Is this data added & updated manually?
Or instead there's something anything wrong with the script?

**Comment by jakewmeyer** [comment]
It's updated with a script.

Looks like when I made a bunch of linting changes about a month ago I updated one of the variables from snake_case to camelCase, which broke it. It's resolved now.

**Comment by jesusrp98** [comment]
Thanks! Great to hear what everything's working now!
