### ISSUE TITLE
Arabsat 6A timeline inconsistency

### ISSUE THREAD

**Issue by jor-dan** [r-spacex/SpaceX-API#221]
In previous launches each timeline had a `payload_deploy` key or `payload_deploy_1` and `payload_deploy_2` keys for launches with two payload deployments. In this launch the key was renamed to `payload_deployment`. It would be easier to parse if the naming scheme was consistent across all launch timelines.

**Comment by jakewmeyer** [comment]
Whoops, corrected 👍
