### ISSUE TITLE
CRS-17 has fairing properties

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#222]
The `fairings` parameter should be `null` when the launch includes a Dragon vehicle.

**Comment by jakewmeyer** [comment]
Updated. Going to add a test for this specifically, because it seems to be happening more often

**Comment by jesusrp98** [comment]
I've also noticed that these kind of issues happen often.
Maybe is something wrong with the scripts?

**Comment by jakewmeyer** [comment]
Not something the update scripts touch currently. Likely happens when new launches are added.

**Comment by jesusrp98** [comment]
I see.
Thanks!
