### ISSUE TITLE
CRS-17 update

### ISSUE THREAD

**Issue by trasparente** [r-spacex/SpaceX-API#223]
should have `landing_type: ASDS` `landing_vehicle: OCISLY` and `cap_serial: C113`

**Comment by jakewmeyer** [comment]
Updated

**Comment by jesusrp98** [comment]
And what about the core serial? It should also be `B1056`.

All this information is found under the launch campaign page, right [here](https://www.reddit.com/r/spacex/comments/bd2l28/crs17_launch_campaign_thread/).

**Comment by jesusrp98** [comment]
@jakewmeyer Also, both the static fire date & mission patch are missing, as well as any kind of mission's description :/

**Comment by trasparente** [comment]
Could be the database versioned here so we can pull request this kind of updates?

**Comment by jesusrp98** [comment]
If I understand correctly, this API pull most of the info from the SpaceX's subreddit. So maybe is something wrong with the web scrapping scripts?

**Comment by jakewmeyer** [comment]
@trasparente In theory it sounds like a good solution, but the data changes too frequently for it to be viable in practice.

@jesusrp98 100% my fault for slacking on data entry. Once the launch thread is posted, a significant amount needs to be added manually. In a perfect world the launch/campaign threads would always be the same and easy to parse, but the real world is inconsistently inconsistent. People hosting the threads have a lot of freedom to structure things in different ways, and while cool for variety reasons, is a nightmare for parsing 😆 

One of the older ideas we tossed around was having some UI somewhere where trusted users could easily update/add data without directly touching the database, but then people have to keep things up to date in two places, which isn't as convenient, especially on people that just do it for fun. Better to have a single source of truth, which the subreddit already provides.

**Comment by jesusrp98** [comment]
I understand, and thank you very much for maintaining this API.
One option could be to speak with the mods of the subreddit, and standardize most of the post layout?

**Comment by jhpratt** [comment]
@jakewmeyer Once Enceladus is up and running to an extent I'm comfortable with, I can send some updates your way. Not sure what sort of things would be easy-ish to pull, but the countdown at a minimum would be trivial.

Standardizing a format won't be happening though, Enceladus gives the hosts _more_ freedom than they currently have, and it's already been given the green light from the mods.

**Comment by jakewmeyer** [comment]
@jesusrp98 Standardizing isn't realistic, and I wouldn't want to limit the format/creativity of the posts in any way. 

This might  just end up being an inherent limitation to the api unfortunately. There's only so much structured data, and unless SpaceX decides to make public sources available, options are limited.

I'm sure the majority of the people interacting with the api are also double checking times on the subreddit, or use the subreddit exclusively. Hard to beat Reddit for quick updates ¯\_(ツ)_/¯. So while the api might get you 90% of the way, the hardcore people are always going to use reddit to check regardless. The api is best at making the dataset as a whole more accessible, and I've always encouraged people to stick with Reddit for the most up to date info.
