### ISSUE TITLE
CRS-17 Launch date update

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#224]
Launchdate has been set to [4th of May 2:48 a.m. EDT, 6:48 UTC](https://twitter.com/SpaceX/status/1124210054478028800). Can this be updated please? 

@jakewmeyer any possibility for contributors to update existing launchdates whenever the schedule changes (POST request to an API endpoint for example)?

**Comment by jesusrp98** [comment]
I think selecting a small group of people to maintain some of the data that can't be retrieve using script would be a good idea.

**Comment by jeroenboumans** [comment]
@jesusrp98 I'd say, expand the API with some small basic application key/secrets logic so that authorized users can `POST` requests to update records like these. 

**Looking at @jakewmeyer if he embraces this idea as well**

**Comment by jakewmeyer** [comment]
Agree this is a good idea, I'll make it my new big priority.

Biggest consideration is how close to launch we should cut off the updating script, and switch it over to user updates only.

**Comment by jeroenboumans** [comment]
Awesome @jakewmeyer!
 
For the consideration part: shouldn't user updates always override the update script?

**Comment by jakewmeyer** [comment]
In theory yes, but once the wiki updates are disabled by a user input, we depend on the user for updates for the rest of the way, which could be good or bad. Worst case, someone updates and stops the automatic updates, and if the launch keeps getting scrubbed, the updates might not be as quick.

**Comment by jeroenboumans** [comment]
@jakewmeyer Okay, I understand. So what if we compare wikipedia timestamps vs user input timestamps for that: (_"This page was last edited on 7 May 2019, at 01:28 (UTC)."_). 

So in general the wiki should only be used if no user has updated the launchdate, or if the timestamp of the wiki page is newer than the user updated timestamp. Should that work or am I overlooking something here?

**Comment by jeroenboumans** [comment]
Will post this as feedback again in #226

**Comment by jakewmeyer** [comment]
Might work, but there's one scenario where it might not.

Ideally it goes like this:
1. Allow user updates at any time
2. Update script checks the wiki timestamp for changes, and updates if a change was made.

Problem is the wiki update would overwrite any changes made by users but not made to the wiki yet.

**Comment by jakewmeyer** [comment]
Going to address this in #226
