### ISSUE TITLE
Launch date for Starlink is wrongly set to 2019-05-01

### ISSUE THREAD

**Issue by marcozambi** [r-spacex/SpaceX-API#225]
Launch date is currently set to 2019-05-01 but the latest news are indicating 2019-05-15 @ 22:
See https://twitter.com/nextspaceflight/status/1125850141175484417 and https://twitter.com/jeff_foust/status/1125845602024161283

**Comment by jakewmeyer** [comment]
See #226 

Fastest way to update launch times is through the subreddit [wiki](https://www.reddit.com/r/spacex/wiki/launches/manifest)
