### ISSUE TITLE
New app created with SpaceX-API

### ISSUE THREAD

**Issue by chert12** [r-spacex/SpaceX-API#229]
Hi.
Thanks for your API, it's really cool and useful.
I submit new app created with SpaceX API.
Name: SpaceX Universe
Type: Android app
Creator: Oleksii Chernov
Google Play - https://play.google.com/store/apps/details?id=com.aastudio.spacexuniverse
Github - https://github.com/chert12/SpaceX-Universe

**Comment by jakewmeyer** [comment]
Added in a3747f7fcf751d65c0184244fb4035010cac3457 👍
