### ISSUE TITLE
Upcoming Launch showing date Jan 2019

### ISSUE THREAD

**Issue by muazz1m** [r-spacex/SpaceX-API#232]
there is upcoming flight with date Jan 2019, flight_number 91,92, and 93

```
{
        "flight_number": 91,
        "mission_name": "Starlink 3",
        "mission_id": [],
        "launch_year": "2019",
        "launch_date_unix": 1546300800,
        "launch_date_utc": "2019-01-01T00:00:00.000Z",
        "launch_date_local": "2018-12-31T19:00:00-05:00",
        "is_tentative": true,
...
}
```

**Comment by jakewmeyer** [comment]
[Manifest](https://www.reddit.com/r/spacex/wiki/launches/manifest) has all of them listed as **2019**, and the only way to represent a partial date in a timestamp is the beginning of the time period. 

`tentative_max_precision` field should help with this. The value is `year` for all these launches, so you should only consider the year of the timestamp to be precise. 

Potential values are `quarter, half, year, month, day, hour`

Not sure what language you're  using, but with [Moment.js](https://momentjs.com/docs/#/displaying/), you can just feed the timestamp into the constructor, and give different display formats depending on the value of `tentative_max_precision`
