### ISSUE TITLE
2 Launches with the same numbers

### ISSUE THREAD

**Issue by garyjacobs** [r-spacex/SpaceX-API#235]

**Comment by garyjacobs** [comment]
STP 2 and CRS 18 both have the same flight number.
![806CA8FE-E5CF-4B4A-93B4-0FF0C280F7AE](https://user-images.githubusercontent.com/38194997/60088415-f6e09700-9781-11e9-95ad-a5b16b621042.jpeg)

**Comment by jakewmeyer** [comment]
Resolved in 9b47d24d9ede6c23e27d5185606b4d5f066a5267. This could happen when the launch wasn't marked as upcoming anymore, but still appeared in the wiki.

The update script now checks for that, and adjusts the offset accordingly
