### ISSUE TITLE
Update Starship maiden launch date

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#236]
According to [this](https://spacenews.com/spacex-targets-2021-commercial-starship-launch/) article, SpaceX now targets 2021 as the year Starship will be first launched.
```
first_flight: "2021-12-01"
```

**Comment by jhpratt** [comment]
See #226.

**Comment by jakewmeyer** [comment]
@jesusrp98 updated the date, #226 doesn't apply because the rocket details don't pull from the wiki
