### ISSUE TITLE
CRS-18 launch date still with troubles

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#238]
According to #226, launch times are updated every 10 minutes. As I can see on https://www.reddit.com/r/SpaceX/wiki/launches/manifest/, CRS-18 has been updated to the today date (Jul 25) but /launches/next still returns the old time (Jul 24). I'm not sure if it's still a previous bug you fixed a few days ago, but I want to let you know.

**Comment by jakewmeyer** [comment]
Just pushed a fix for this

`2019 Jul 25 [22:01:56]` was the date entered

Haven't seen a launch time with seconds before in the manifest, so I didn't think to add it.

**Comment by Tearth** [comment]
Thanx!
