### ISSUE TITLE
Created a site using your brilliant API

### ISSUE THREAD

**Issue by jimmyboix** [r-spacex/SpaceX-API#239]
Thanks to Jack and the rest for supporting this project.
Had good fun working on this and going to continue with it. 
Could you add it to the list of Apps please :)

Name: SpaceFax
URL: https://spacefax.xyz
Type: Website
Creator: Jimmy Hendrie
Repo: https://github.com/jimmyboix/SpaceFax

**Comment by jakewmeyer** [comment]
Added. Thanks!
