### ISSUE TITLE
Orbcomm payload name inconsistency

### ISSUE THREAD

**Issue by quadrplax** [r-spacex/SpaceX-API#24]
The first Orbcomm mission has a payload name of "Orbcomm-OG2 x 6", while the second one has a name of "Orbcomm OG2 M2". Either the second one should be changed to "x 11" or the first one should be changed to "M1".

**Comment by jakewmeyer** [comment]
Corrected to Orbcomm-OG2-M1 and Orbcomm-OG2-M2
