### ISSUE TITLE
Duplicate flight numbers

### ISSUE THREAD

**Issue by CodyDSmith** [r-spacex/SpaceX-API#240]
Currently GTO-C & CRS-21 both have flight number 99, and ALINA & GPS III SV04 both have flight number 95.

https://api.spacexdata.com/v3/launches?flight_number=95&filter=flight_number,mission_name
https://api.spacexdata.com/v3/launches?flight_number=99&filter=flight_number,mission_name

**Comment by jakewmeyer** [comment]
Looks like GTO-C and ALINA launches were removed from the manifest, went ahead and manually removed them. Going to add a mechanism to remove these missing launches automatically to prevent duplicates.
