### ISSUE TITLE
Amos-17 corrections

### ISSUE THREAD

**Issue by CodyDSmith** [r-spacex/SpaceX-API#244]
The payload mass for Amos-17 is 6500 kg on the reddit manifest (and Spaceflight Now), but the API returns 5500 kg.

The static fire for Amos-17 took place yesterday, but the API returns today, several hours from now. The reddit launch campaign thread says "Static fire completed: 00:00 UTC August 1 / 8:00 pm EDT July 31 2019".

**Comment by jakewmeyer** [comment]
Corrected
