### ISSUE TITLE
Add spacex-api to the clients list

### ISSUE THREAD

**Issue by tbprojects** [r-spacex/SpaceX-API#245]
Hi, I've implemented a JavaScript / TypeScript wrapper for r-spacex/SpaceX-API. Maybe it would be useful to add it to the list of the clients: https://github.com/r-spacex/SpaceX-API/blob/master/docs/clients.md

npm: https://www.npmjs.com/package/spacex-api
github: https://github.com/tbprojects/spacex-api

**Comment by jakewmeyer** [comment]
Added. Thanks!
