### ISSUE TITLE
I want to submit my App

### ISSUE THREAD

**Issue by itsdancedrick** [r-spacex/SpaceX-API#251]
Good day! How can I submit the web app that I developed using this API here's the link https://spacex-archive.web.app/  thank you! 

you can email me here: personal.dancedrick@gmail.com

**Comment by jakewmeyer** [comment]
Best way is to:

1. Fork the repo
2. Add a new line in `/docs/apps.md`
3. Open a pull request with the changes

And we'll get it merged and added 👍

**Comment by itsdancedrick** [comment]
@jakewmeyer  forked then added my site in apps.md :) 
![image](https://user-images.githubusercontent.com/42290274/64110376-8f177f80-cdb4-11e9-9b42-ae47f396cec5.png)

**Comment by jakewmeyer** [comment]
Need to create the pull request in this repo
