### ISSUE TITLE
Trusted Users Updates

### ISSUE THREAD

**Issue by mathisbeauty** [r-spacex/SpaceX-API#252]
I open this issue to talk about the details of implementation of trusted users.
## Main Issue
In relation to the problem mentioned [here](https://github.com/r-spacex/SpaceX-API/issues/224#issuecomment-491404542), that the wiki could overwrite changes made by user updates and not made in the wiki, my last PR relies on the timestamp of the wiki to compare it to other sources of launch dates, but it also checks that the launch date changes between revisions, so only if the date that we care about was updated in the wiki, it will take priority over the user update.

I believe this solves the main issue for adding trusted users, and we could start sketching out the database schemas and a possible UI. And also how to distribute the keys/accounts to the users.

**Comment by jakewmeyer** [comment]
With the addition of wiki + LL, not sure if this is as big of a problem now. Those two update channels already have substantial base of trusted users updating things as they happen, not sure we would gain much by implementing our own channel.
