### ISSUE TITLE
Twitter Scraping for Launch Time Updates

### ISSUE THREAD

**Issue by mathisbeauty** [r-spacex/SpaceX-API#253]
I have two main questions in regards to implementing twitter scraping for launch updates:

1. How to know which tweets talk about a rescheduling of a launch or a date update?
2. How to extract the date from the tweet? Do they follow a consistent pattern?

I think is a pretty complicated problem, and it would be wiser to focus on #252, at least for now.

Any suggestions or ideas?

**Comment by jakewmeyer** [comment]
From what I've seen, the only consistent tweet format is the updates for static fire tests, ex:

```
Static fire test of Falcon 9 complete—team is now working toward August 6 for launch of AMOS-17 from Pad 40 in Florida, pending Range availability
```

Always has a mention of static fire and mission name, so this should be the easiest one to identify. The other formats are more unpredictable, I think that sticking with date updates from the wiki || other providers is the best solution.
