### ISSUE TITLE
Fairings id 

### ISSUE THREAD

**Issue by beckyconning** [r-spacex/SpaceX-API#256]
Unlike payloads and cores its very difficult to track ~~payloads~~ fairings. Please add a unique id for each fairings, this could even be a uuid or incrementing integer.

**Comment by jakewmeyer** [comment]
Payloads or Fairings?

Pyaloads have an exisitng `payload_id` field

Fairings don't have anything currently, mainly because SpaceX doesn't give them a readily avaliable id

**Comment by beckyconning** [comment]
Oh I miswrote. It should be "Unlike payloads and cores it's very difficult to track fairings." 

Do we know which fairings are which even if they don't provide ids?

**Comment by jakewmeyer** [comment]
Not that I'm aware. The've been essentially disposable until very recently. I could give them a random id, but if SpaceX ever starts assigning an id, it would change in the future.

**Comment by beckyconning** [comment]
a random id would be great as currently there is no way to group by them

**Comment by beckyconning** [comment]
straightforward to re-hydrate that data with the new ids later. alternatively the ids you assigned could be kept in addition the the ids spacex eventually assigns them. very important for our analysis.

**Comment by jakewmeyer** [comment]
Any preference on length? UUID?

**Comment by beckyconning** [comment]
uuid would work perfectly.

**Comment by jakewmeyer** [comment]
This will be addressed in v4
