### ISSUE TITLE
Duplicated flight number

### ISSUE THREAD

**Issue by dpyzo0o** [r-spacex/SpaceX-API#258]
Everything is working fine until today. The  launches `https://api.spacexdata.com/v3/launches` return have multiple launches with same `flight_number` , see examples below

<img width="407" alt="Screen Shot 2019-09-20 at 14 44 00" src="https://user-images.githubusercontent.com/24768249/65305209-2eaa7f80-dbb5-11e9-993b-1800669719a5.png">
<img width="413" alt="Screen Shot 2019-09-20 at 14 44 09" src="https://user-images.githubusercontent.com/24768249/65305211-2eaa7f80-dbb5-11e9-9951-4a52f3fdf610.png">
<img width="391" alt="Screen Shot 2019-09-20 at 14 44 20" src="https://user-images.githubusercontent.com/24768249/65305213-2eaa7f80-dbb5-11e9-8819-44d54e0329be.png">
<img width="401" alt="Screen Shot 2019-09-20 at 14 44 29" src="https://user-images.githubusercontent.com/24768249/65305214-2f431600-dbb5-11e9-9d93-dcb7a0a28498.png">

This looks like bug to me. I use the flight_number as keys for my react application because I assume the flight number is unique for every launches.

Anyone can help?

**Comment by dpyzo0o** [comment]
I also find that some launches are not returned by the api anymore. e.g, `https://api.spacexdata.com/v3/launches/106` gives error `Not Found`

**Comment by jakewmeyer** [comment]
Sorry for all the craziness this week. Reddit wiki people were debating the best naming scheme for the starlink and smallsat rideshare launches, which screwed up the launch updater.

**Comment by dpyzo0o** [comment]
@jakewmeyer Thanks for the clarification. It seems to work again today!
