### ISSUE TITLE
connecting to mongodb TIMEOUT

### ISSUE THREAD

**Issue by P48L0** [r-spacex/SpaceX-API#266]
im trying to connect to the mongodb server but i get TIMEOUT...this is the code im running:

```js
const url = 'mongodb+srv://public:spacex@spacex-gcp-gpg0u.gcp.mongodb.net/spacex-api';
const MongoClient = require('mongodb');

(async () => {
  try {
    const client = await MongoClient.connect(url, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    }); 

    console.log( "ok...")


  } catch (err) {
    console.log("ERROR  "+err.stack);
  }
})();

```

i get:

```
ERROR  Error: connect ETIMEDOUT 104.154.151.148:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14)
```

**Comment by jakewmeyer** [comment]
Looks like a network issue, this code runs fine for me. Default timeout is 30 seconds, so that should be more than enough time to connect.

**Comment by P48L0** [comment]
> Looks like a network issue, this code runs fine for me. Default timeout is 30 seconds, so that should be more than enough time to connect.

could it be that the server blocks some countries?

**Comment by jakewmeyer** [comment]
Not that I'm aware of

**Comment by EntOfMD** [comment]
@P48L0 your code works for me too. But just in case, here in another way you can try:

```js
const url =
	'mongodb+srv://public:spacex@spacex-gcp-gpg0u.gcp.mongodb.net/spacex-api';
const MongoClient = require('mongodb');

(async () => {
	await MongoClient.connect(url, {
		useNewUrlParser: true,
		useUnifiedTopology: true
	})
		.then(()=> {
			console.log('DB Connected');
		})
		.catch(err => {
			if (err) throw err;
		});
})();
```

I tried it with `mongodb` and `mongoose` for the MongoClient, they both worked fine.
