### ISSUE TITLE
Inconsistency in dates of Next Launch

### ISSUE THREAD

**Issue by haroldadmin** [r-spacex/SpaceX-API#268]
The launch with the closest upcoming launch date does not always correspond to the data returned by the `/launches/next` endpoint.

For example, data returned by `/launches/next`: Starlink 2 (Oct, 1)
Launch with closest launch date: ANSIS II (Nov, 1)

This makes it harder to rely on the results returned by database queries on cached data from the API.

Also, as is evident from the launch date of Starlink 2, it is not correct to return it as the "next" launch if the launch date has been shifted to an unclear target. While it may well be the next planned launch, the API should at least provide a marker to indicate that a launch's status and launch date may be unclear.

**Comment by jakewmeyer** [comment]
With the way the API handles partial dates, I recommend ordering using `flight_number`, as it matches nicely with the "most likely" order on the subreddit [wiki](https://www.reddit.com/r/spacex/wiki/launches/manifest).

As far as displaying the date goes, I would look at the following fields:

`tdb` - set as `true` until a date has a day of the week

`is_tentative` - set as `true` until the date has a time

`tentative_max_precision`- shows the precision of the date. So for Starlink 2, the date is `2019-10-01T00:00:00.000Z`, but the date is only precise to the month level, or `2019-10`. Potential values are `quarter, half, year, month, day, hour`. Most people have pre-set date formats for these levels of precision, and display the date according the value of `tentative_max_precision`

**Comment by haroldadmin** [comment]
Thank you for the help. Maybe we should consider adding a wiki page on this repository to explain the meaning important parameters such as these.

**Comment by jakewmeyer** [comment]
There's a small section in the top of the [docs](https://docs.spacexdata.com/?version=latest), but I'll edit it for a bit more clarity for similar issues 👍

**Comment by haroldadmin** [comment]
Thanks! I apologize for not reading the docs thoroughly. I'm closing this issue now.

**Comment by jakewmeyer** [comment]
No worries 👍
