### ISSUE TITLE
Pagination total count

### ISSUE THREAD

**Issue by krasnyuk** [r-spacex/SpaceX-API#269]
Is it possible to get total count of records for pagination?

**Comment by jakewmeyer** [comment]
For all the endpoints that return an array (like [https://api.spacexdata.com/v3/cores](https://api.spacexdata.com/v3/cores)), the header `spacex-api-count` is included, and should work for pagination. Pagination params are `limit` and `offset`

[https://reqbin.com/4inargiv](https://reqbin.com/4inargiv) for example

**Comment by krasnyuk** [comment]
Awesome, I think it would be great to add this info to docs, because I just missed that :)

**Comment by jakewmeyer** [comment]
Added 👍
