### ISSUE TITLE
Timezone information incorrect

### ISSUE THREAD

**Issue by HarvsG** [r-spacex/SpaceX-API#27]
After getting some funny javascript behaviour in my server logic I found the issue.
So apparently we got the wrong end of the stick with the ISO datetimes.
For example, Intelsat 35e reads
```
    "launch_date_utc": "2017-07-05T23:35:00Z",
    "launch_date_local": "2017-07-05T23:35:00-04:00",
```
But should read
```
    "launch_date_utc": "2017-07-05T23:35:00Z",
    "launch_date_local": "2017-07-05T19:35:00-04:00",
```
[JSFiddle](https://jsfiddle.net/jzsq4qzt/13/)

So the correct format for a local time is
`local_year`-`local_month`-`local_day`T`local_hour`:`local_minutes`:`local_seconds`+/-`timezone_correction`
and not UTCDateTime+/-`timezone_correction`

**Comment by jakewmeyer** [comment]
So it needs the timezone adjustment twice? Weird.

I'll make another pass on it and convert to the correct times. Thanks 👍

**Comment by jakewmeyer** [comment]
Local timezones should be correct now
