### ISSUE TITLE
API appears to be down

### ISSUE THREAD

**Issue by beckyconning** [r-spacex/SpaceX-API#271]
```
500 Internal Server Error

nginx/1.14.0 (Ubuntu)
```

**Comment by EntOfMD** [comment]
I'm getting the same error but only for /launches route

**Comment by jakewmeyer** [comment]
Interesting. Linode did some scheduled maintenance on the instance at midnight CST, but everything came up just fine after that.

Looks like it was related to the maintenance. but I'll keep a closer eye on it as things move towards normal.
