### ISSUE TITLE
Can not apply both filter and pretty query 

### ISSUE THREAD

**Issue by godhand4826** [r-spacex/SpaceX-API#272]
I setup the server by default.
```bash
$ git clone https://github.com/r-spacex/SpaceX-API.git
$ cd SpaceX-API && npm i && npm run start
```
The pretty query is work fine.
```
$ curl "localhost:5000/v3/launches?pretty=true"
```
The filter query is work fine too.
```
$ curl "localhost:5000/v3/launches?filter=flight_number"
```
But I run with both query, the output is just the same as I only given pretty query.
```
$ curl "localhost:5000/v3/launches?pretty=ture&filter=flight_number"
```
To fix this bug just change the order of the middleware in `app.js`, which is mount middleware `json ` before `mask` to make `mask` execute before `json`.
```js
app.use(json({ pretty: false, param: { pretty: true } })); 
app.use(mask({
  name: 'filter',
}));
```
After fix this bug, all the tests is still passed. 
I don't know where to implement this test(maybe test/utils?) so I create this issue to let you know this bug.

**Comment by jakewmeyer** [comment]
Fixed and deployed 👍 

[https://api.spacexdata.com/v3/launches?pretty=true&filter=flight_number](https://api.spacexdata.com/v3/launches?pretty=true&filter=flight_number)

**Comment by godhand4826** [comment]
Have a good day : )
