### ISSUE TITLE
Live stream link

### ISSUE THREAD

**Issue by xhardcorex** [r-spacex/SpaceX-API#273]
Is it possible to get live stream link of the launch from response?  Thank You!

**Comment by timisenman** [comment]
The livestream link is also always going to be the same, if you are wanting to stream the launch as it's happening: https://www.youtube.com/spacex/live

You should be able to format it similar to most videos, but be warned that you may receive errors with the /live link. It's a bit of tricky URL to work with, especially if you're trying to view the video player before the launch stream has officially started.

**Comment by xhardcorex** [comment]
Thanks for all !
