### ISSUE TITLE
Prefer https links to http for every entity

### ISSUE THREAD

**Issue by haroldadmin** [r-spacex/SpaceX-API#274]
Some entities returned by the API contain links to other websites. For example, [Mission details  for a given ID](https://api.spacexdata.com/v3/missions/9D1B7E0).

Some of these links use the `http` protocol even though the servers for this link might support `https`. In the above example, the link to the mission's website uses `http://www.thaicom.net` even though `https://www.thaicom.net` works just fine.

Can there be a check to ensure that the `http` version of the link only gets added to the database when the website can not handle `https`?

This causes an issue while developing apps for Android Pie and above because the OS crashes the app if it uses cleartext HTTP communication.

**Comment by jakewmeyer** [comment]
This can be a constraint in v4 👍
