### ISSUE TITLE
Wrong data in JCSat 18 and Starlink 2

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#279]
86. JCSat 18 / Kacific 1
  - rocket.first_stage.cores.flight is set to 3, but reuse.core is set to false (should be true)

87. Starlink 2 (Falcon 9 FT)
  - YT link is set to the previous mission Starlink mission (should be null)

**Comment by Tearth** [comment]
It seems that JCSat 18 / Kacific 1 is now correct, so only Starlink 2 YT link is wrong.

**Comment by jakewmeyer** [comment]
Starlink 2 link is resolved. This should only be an issue with back to back starlink launches, so. I guess they changed the link to starlink at some point after the kacific launch.

**Comment by Tearth** [comment]
Thank you
