### ISSUE TITLE
Missing or inaccurate data in cores

### ISSUE THREAD

**Issue by marcozambi** [r-spacex/SpaceX-API#285]
I have noticed a few problems with the boosters data in the cores endpoint.

Here are some examples:

1) _original_launch_ and _original_launch_unix_ fields are missing (i.e. they have null value) for cores B1057 and B1059 despite they have all flown in one mission, hence they had a first flight.

2) The status of a booster could be defined in a more precise way when it comes to "lost" stages. A status of "lost" conveys, at least to me, the idea of a stage that suffered an accident and was literally lost, either because exploded during ascent or because failed landing. This status at the moment also includes "expended" boosters, which are not lost but rather disposed after a number of reuses that was deemed sufficient by SpaceX. To work out this difference one is forced to read/parse the _details_ field, looking for words like "expended".  I would suggest to actually make "expended" as a status by itself.

**Comment by jakewmeyer** [comment]
1. I added automatic updating for the the launch dates in cores in capsules, so this shouldn't be an issue going forward 👍 

2. Absolutely agree. Unfortunately the subreddit [wiki](https://old.reddit.com/r/spacex/wiki/cores) makes no distinction and categorizes them all as `lost`. However, the core `fate` column usually mentions the word expended, so we could set an expended status based on the presence of `expended`
