### ISSUE TITLE
Crew Dragon IFA data issue

### ISSUE THREAD

**Issue by 499602D2** [r-spacex/SpaceX-API#287]
Lacking a bunch of data, plus some incorrect data with the capsule.

**Booster**
Core recovery (landing intent) should be set to false, as no recovery will be attempted.
Legs and gridfins should be set to false, as there is no recovery hardware onboard.

**Payload**
Capsule serial number is C205 (currently null) and it is **not** reused, as it is currently marked as such.
Maybe set crew to 0 as this is an unmanned flight?

**Other**
Launch site is marked as "KSC LC 39A", when the correct typographic form is "KSC LC-39A"

**Comment by jakewmeyer** [comment]
This should all be resolved at this point, except the typography of LC-39A. Going to leave that as is for legacy reasons, would likely break something downstream.
