### ISSUE TITLE
Starlink 3 data issue

### ISSUE THREAD

**Issue by 499602D2** [r-spacex/SpaceX-API#289]
Booster is lacking reuse count and recovery mode. B1051 has flown twice before, and will be landing on OCISLY. https://reddit.com/r/spacex/comments/eof5pr/starlink3_launch_campaign_thread/

**Comment by jakewmeyer** [comment]
Updated

**Comment by timisenman** [comment]
Is the date for the upcoming Starlink 3 launch TBD? Current date reads Jan 16th

**Comment by Tearth** [comment]
https://api.spacexdata.com/v2/launches/next returns "launch_date_utc":"2020-01-16T00:00:00.000Z","launch_date_local":"2020-01-15T19:00:00-05:00", which is invalid, because in the Reddit manifest we see "2020 Jan Late [16:00]" (so I assume that parser got this 16 as day, not as hour).

**Comment by Tearth** [comment]
It looks like the launch date has just backed to the valid, but I think it's worth to fix this bug when someone adds "Late" or another word in the date.

**Comment by jakewmeyer** [comment]
Parser couldn't read the date, so it skipped updating that one. I get email notifications about bad parsing, so it usually gets resolved quickly.
