### ISSUE TITLE
Add Roadster launch video link

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#295]
Add [the link](https://youtu.be/wbSwFU6tY1c) of the maiden Falcon Heavy to the Tesla Roadster endpoint.

For example:
```
video: "https://youtu.be/wbSwFU6tY1c",
```

**Comment by jakewmeyer** [comment]
Added 👍

**Comment by jesusrp98** [comment]
Great! Thanks!
