### ISSUE TITLE
API v4

### ISSUE THREAD

**Issue by jakewmeyer** [r-spacex/SpaceX-API#296]
### Current issues with v3

1. Lack of strictly enforced schema at the application + db levels
2. No API endpoints for updating, adding, or deleting data
3.  No truly unique id for each datapoint (core, capsule, launch, etc..)
4.  Data too tightly coupled with launches (fairings, payloads).
5.  Duplicated data between launches and parts involved in a launch
6. Confusing date fields for newcomers
7. No job queueing system for update scripts, or any route to trigger them manually if necessary
8. No way for community to contribute to/fix api docs
9. Missing robust search capability

**Comment by Jon-000** [comment]
hi, i find that there is not using mongoose.model or something similar in the project, so why using mongoose? why not just using mongodb nodejs driver alone? is this intended? like it is faster not using model, or because the project is just working in progress?

**Comment by jakewmeyer** [comment]
Originally I didn't use mongoose, not sure what the reason was at the time.

Thinking a complete rewrite isn't the best course here. Better to slightly revise the data model, keep it in mongo, add mongoose models and mutator routes.

**Comment by jesusrp98** [comment]
Is there an ETA on the development of v4??

**Comment by timisenman** [comment]
All sound like great problems to address 👍

**Comment by jakewmeyer** [comment]
ETA is before DM-2 launches.

Made good progress over the weekend, all of the routes and data models are in place.

Biggest things left are:
* Write new Redis cache middleware
* Write v4 docs
* Refactor update scripts to use the api for updating
* Migrate all the old data into the new db

**Comment by jesusrp98** [comment]
Wasn't the v4 version of API originally planned to be written with Go?
I've check the `v4`branch and it's JS once again, in comparison with `v4-experimental`.

It's OK to me, just a curiosity.

**Comment by jakewmeyer** [comment]
That was the plan up until recently, ran into a weird issue with the way slices are encoded to json. Instead of encoding empty slices as `[]` as you'd expect, it encodes as `null` to save on memory. There's a patch in progress to give an option to encode as empty arrays, but it's not slated until go 1.16 at the very least, which is over a year away. 

This new version was already super far behind, so I shelved the go version. Maybe it could be ported in the future, but I'd rather get these updates out the door.

**Comment by jakewmeyer** [comment]
**Update:**

All the routes, auth, caching, etc.. are in place and functional at this point. 

The majority of the data has been added, except for launches, which I'm planning on adding over the weekend.

Also porting all the update scripts this weekend too, shouldn't be too bad.

After that, it'll just be writing the new documentation for all the routes. I've pretty much finished the homepage docs, most of the work left is on the individual routes.

The new API is also live at [https://stage.spacexdata.com](https://stage.spacexdata.com) if anyone wants a first look.

The docs [homepage](https://github.com/r-spacex/SpaceX-API/tree/v4/docs/v4) should give a pretty good overview on the route layouts, nothing too complex this time around.

Thanks everyone for your patience!

**Comment by jesusrp98** [comment]
Such a nice job @jakewmeyer, congratulations!!
I have various questions to ask about this new API version:

- I've checked most of the response layouts and I haven't noticed any breaking change compared to the `v3` version of the API. Is there anyone that I haven't noticed?
- Regarding data manipulation via the API itself, how this will be handled? Will anyone be able to edit data, or will you handpick a number of people to include in this service?

Thank you very much for your dedidation over these past few years, improving this awesome project!

**Comment by jakewmeyer** [comment]
Most everything is the same, just small tweaks to field names mostly, and properly splitting data out of launches. Notable missing data includes the following:
* **Press kit timelines**: The schema for the existing timeline needs a rework, so I'm going to push this past v4. The data entry on this one is pretty tedious, so hopefully I can find a way to reliably parse the press kit for the timeline.
* **Missions**: After looking at the data, a lot of this seemed pretty redundant, so I took it out for the time being. This was originally added to give people an easier option to find all CRS launches for example, but with full text search and a tighter integration with mongo queries, these should be a lot easier to search for.
* **History**: I neglected this data for quite awhile, and then there's the issue of deciding on the threshold that makes something a historical event, at a company where most things are historical events 😆.  The wikipedia page does a pretty good job of documenting this, so unless someone wants to maintain it, I'm leaving it out.
* **Company info**: Not sure how commonly this is used, but the wikipedia page is a much more accurate source for this info. If this is still needed, I can add it back.
* **Roadster endpoint**: Most of this orbit info is already available for each payload, so having a separate endpoint for this is a bit redundant. I'll likely keep the old update script running, since it's low maintenance.  

As far as data manipulation goes, it'll be restricted to people in the community, but I haven't really decided on the decision process for that. Each API key has a set of roles, so a key can be restricted to any combo of create, read, delete actions if needed. But it's not wide open, I have to add an API key for anyone to mess with it. Biggest thing with this is how to handle user provided updates that compete with update scripts potentially. Thinking about adding some property (`source`) to each (launch, core ship, etc...) that would cause the update script to skip over that item, preserving the user provided update. But that could potentially introduce problems where users forget to change that property back to get script updates. Curious if anyone has a better idea for that.

**Comment by jesusrp98** [comment]
Thanks a ton of great information, thanks!
- **History**: I think it would be nice to integrate this endpoint inside the `v4` version of the API. To do that, it should be easilly maintainable. I've checked both r/SpaceX & Wikipedia's achievements lists, and I think the Wikipedia one can be fully integrated inside the API itself. I offer myself to do this work, defining a new data scheme, recollecting all the data, and keeping it up-to-date. Going to open an issue related to all of this if you want to.
- **Company**: I've seen that this endpoint is used by most clients of this API, including mine. I think it shouln't be too difficult to copy all info from `v3`: both scheme & data is fine.
- **Roadster**: Again, both scheme, data & functionality is fine. It'd be nice to have this endpoint available inside the `v4` version, but if you ultimately think that it's not necessary to port it to the newer version, and keep the `v3` version alive, would be fine as well.

**Comment by jakewmeyer** [comment]
Sounds good, feel free to open the issue.

As far as roadster and company data go, I'll go ahead and keep that for v4 👍

**Comment by spaceincase** [comment]
Anyway we could add a photos section in v4? Just pull all the spacex flickr public photos and save the urls in an array? Ive noticed numerous projects that use this api taking that approach, Myself included.

**Comment by jesusrp98** [comment]
As far a I can see in this new version of the API, most of the data inside the `launches` endpoint, related to land and launchpad, payload, rocket etc. are only represented with its `id` parameter.

This generate a huge issue for clients app, because if you want to display some basic info about them (for example core name (B10XX), launchpad name etc., another API call will be required, rising the service load in the way.

What do you think would be a sutible solution?

**Comment by jakewmeyer** [comment]
Not too concerned with increased load, plenty of headroom there. The goal was to reduce the amount of duplicated data across the api, so things only get updated in 1 place ideally. 

Mongoose has a nice deep populate plugin, that essentially goes and replaces all the id's with the document they represent elsewhere, which reduces the amount of calls needed. This could be a potential solution, just need to figure out a way to do that with the pagination plugin I'm using.

**Comment by jakewmeyer** [comment]
Example:

`POST https://stage.spacexdata.com/v4/launches/query`

Body:
```json
{
  "options": {
    "populate": [
      "cores.core",
      "ships",
      "crew",
      "capsules",
      "payloads",
      "launchpad",
      "rocket"
    ]
  }
}
```

This goes and populates all those references, while retaining all the pagination functionality. This should save some roundtrips. 👍

**Comment by jesusrp98** [comment]
I'm trying to use what you've mentioned in your last message, but it's throwing me a 400 error. Am I doing something wrong? 
<img width="634" alt="imagen" src="https://user-images.githubusercontent.com/8961959/81670074-60739d80-9447-11ea-901c-681e3febdbb7.png">

**Comment by jakewmeyer** [comment]
Should be a `POST` instead of `GET`

**Comment by jesusrp98** [comment]
Ah nice bd, sorry!! That's nice and works pretty well!!

Does this `query` feature works with other subendpoints, such as `launches/next` etc.?

**Comment by jakewmeyer** [comment]
Not yet. Working on a good solution for that, since those endpoints don't use pagination.

**Comment by jesusrp98** [comment]
I see.
I think is a pretty nice solution for retrieving all information available inside the data-base, without duplicating anything in the process.

Will there be an option to retrieve specific values of each populated entry?
For example, when populating the `rocket` field inside the `lauches` endpoint it adds all information each rocket. Would it be able to just request its name?

**Comment by jesusrp98** [comment]
Another issue I've found is I can't populate arrays.
When I populate `cores.core` inside the `launches` endpoint, there's a new field called `launches` containg all previous launches of that specific booster.

How could I show that piece of information?

**Comment by jakewmeyer** [comment]
It supports nested populate, for your example this would work.

```json
{
  "options":{
    "populate":[
      {
        "path":"cores.core",
        "populate":[
          {
            "path":"launches"
          }
        ]
      }
    ]
  }
}
```

**Comment by jesusrp98** [comment]
That's great! Also, as I asked earlier, is there be an option to retrieve specific values of each populated entry?
For example, when populating the rocket field inside the launches endpoint it adds all information each rocket. Would it be able to just request its name?

**Comment by jakewmeyer** [comment]
Whoops, missed that part.

```json
{
  "options": {
    "populate": [
      {
        "path": "rocket",
        "select": {
          "name": 1
        }
      }
    ]
  }
}
```

When I fill out the rest of the docs, I'll add more complete examples to document all the possible options. 

[This](https://mongoosejs.com/docs/api.html#query_Query-populate) has all the possible options for populate.

**Comment by jesusrp98** [comment]
This works perfectly! I'm really amazed by how this new systems handles API calls! 
Congratulations @jakewmeyer!!

Just one little thing, it seems that trying to retrieve dragon data inside the `payload` field retrieves 'null':

Options used:
```
{
  "options": {
    "limit": 1000,
    "populate": [
      {
        "path": "payloads",
        "populate": {
          "path": "dragon.capsule"
        }
      },
      {
        "path": "crew"
      },
      {
        "path": "cores.core",
        "populate": {
        	"path": "launches",
        	"select": {
        		"name": 1
        	}
        }
      },
      {
        "path": "rocket",
        "select": {
          "name": 1
        }
      },
      {
        "path": "launchpad",
        "select": {
          "name": 1
        }
      }
    ]
  }
}
```

Output:
```
"payloads": [
  {
    "dragon": {
      "capsule": null,
      ...
    }
  }
]

```

**Comment by jakewmeyer** [comment]
Found the one reference I missed 😆 

Should work now

**Comment by jesusrp98** [comment]
Nice! I'm looking for issues inside the `launch` endpoint.

Having problems now retrieving ships related to fairings:

Options:
```
{
  "options": {
    "limit": 1000,
    "populate": [
      {
        "path": "fairings",
        "populate": {
          "path": "ships"
        }
      }
    ]
  }
}
```

Output:
`Cast to ObjectId failed for value "false" at path "_id" for model "Launch"`

**Comment by jakewmeyer** [comment]
Sending it to the same url? Usually this is an error on `GET` requests for a single item by id

**Comment by jesusrp98** [comment]
This is a screenshot of the problem. As you can see, I'm using a `POST` type request :/
![image](https://user-images.githubusercontent.com/8961959/82037703-cf006780-96a2-11ea-8937-b0c07af20350.png)

**Comment by jakewmeyer** [comment]
Should be:
```json
{
  "options": {
    "limit": 1000,
    "populate": [
      {
        "path": "fairings.ships"
      }
    ]
  }
}
```

Populate requires an id, so the bad query assumed that `fairings` was an id or array of id's. 

This worked previously for the arrays because the first level was an id, then you populate one level  deeper. So in this case, because fairings isn't an id, it failed to populate. In cases like that, just reference the exact path to the id.

**Comment by jakewmeyer** [comment]
Closing as v4 is live
