### ISSUE TITLE
Starlink 4 YouTube link

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#302]
Starlink 4 YouTube link is set to the old one (https://youtu.be/1KmBDCiL7MU). Shouldn't it be removed (because SpaceX didn't create a stream for this launch yet)?

**Comment by jakewmeyer** [comment]
Yep, added a check in the webcast updater, but there was a bug in it.

Should be fixed now. Checks to make sure the most recent launch youtube id doesn't match before updating.

**Comment by Tearth** [comment]
Nice, thanx.
