### ISSUE TITLE
tentative_max_precision field is null

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#308]
The [GPS III SV03 (Columbus)](https://api.spacexdata.com/v3/launches/96) launch has a null `tentative_max_precision` field.

@jakewmeyer is this an expected behaviour, or this is a thing to be fixed?

**Comment by jakewmeyer** [comment]
Not expected.

This should be resolved now, the regex that sets this field should be more tolerant of extra spacing
