### ISSUE TITLE
update Wikipedia link for launchpad ksc_lc_39a

### ISSUE THREAD

**Issue by paulkaefer** [r-spacex/SpaceX-API#310]
Link at [/launchpads](https://api.spacexdata.com/v2/launchpads) endpoint is https://en.wikipedia.org/wiki/Kennedy_Space_Center_Launch_Complex_39#Launch_Pad_39A, but should be https://en.wikipedia.org/wiki/Kennedy_Space_Center_Launch_Complex_39#Launch_Complex_39A (article section/anchor link changed [last June](https://en.wikipedia.org/w/index.php?title=Kennedy_Space_Center_Launch_Complex_39&diff=next&oldid=902990559)).

Might be worth checking other Wikipedia links, too.

I'd be happy to help, with guidance... but I believe you store this in a MongoDB, so the source would need to be updated?

**Comment by jakewmeyer** [comment]
Updated!
