### ISSUE TITLE
B1046 status outdated

### ISSUE THREAD

**Issue by quadrplax** [r-spacex/SpaceX-API#312]
B1046 was destroyed during the In Flight Abort Test, but the API still shows it as active with details of "At the Cape awaiting IFA launch."

**Comment by jakewmeyer** [comment]
Looks like some columns were added to the wiki page the updater was parsing. This should be resolved in 5506df007342cc858365db1346cef995dde5e90f

**Comment by quadrplax** [comment]
Interesting, I was wondering how the API got its data. Thanks!
