### ISSUE TITLE
Question on Youtube URL

### ISSUE THREAD

**Issue by TravisBrown01** [r-spacex/SpaceX-API#313]
Sorry if this is not the place to be asking questions. From my understanding the API has Youtube Videos Implemented. My question is "Does the API pull the Video URL or the Video ID?"

**Comment by jakewmeyer** [comment]
For each launch under links there's `video_link` and `youtube_id`. This video link is automatically grabbed from [https://www.spacex.com/webcast](https://www.spacex.com/webcast), and the youtube id is extracted from that url.

**Comment by TravisBrown01** [comment]
Do you know what format the link is? youtube.com/embed/videoID, youtube.com/watch?v=videoID, youtu.be/videoID

**Comment by jakewmeyer** [comment]
Usually in the format `https://youtu.be/I4sMhHbHYXM`, but no guarantee that all will be the same.
