### ISSUE TITLE
Starlink 6 landed_success showing incorrect data

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#316]
The launch has yet to occur, but the API shows `"landed_success": true`.

<img width="286" alt="Screen Shot 2020-04-22 at 6 29 48 AM" src="https://user-images.githubusercontent.com/20021876/79916042-02b0ee80-8463-11ea-8662-843b19d3b269.png">

**Comment by jakewmeyer** [comment]
Fixed

**Comment by timisenman** [comment]
Thanks so much, Jake. You're my hero.
