### ISSUE TITLE
502 response from GET request to /rockets

### ISSUE THREAD

**Issue by spaceincase** [r-spacex/SpaceX-API#320]
Is this api down currently? Noticed my site was having issues earlier. Now it seems to be completely down. Decided to hop on postman and send a request to /rockets and got a 502.

**Comment by Tearth** [comment]
I see it too (502 error), looks like API is down.

**Comment by andy-rose-pantheon** [comment]
Same here. Trying to do the GraphQL tutorials which depends on this

**Comment by Tearth** [comment]
Looks like API is alive again

**Comment by jakewmeyer** [comment]
Looks like Linode had a pretty major outage this afternoon in Dallas where the VPS is. 

[https://status.linode.com](https://status.linode.com)

Seems like a good case for multi region redundancy 🙃
