### ISSUE TITLE
DM-2 missing data

### ISSUE THREAD

**Issue by 499602D2** [r-spacex/SpaceX-API#322]
DM-2 missing some data.

**Core landing:** OCISLY

**Dragon serial:** C206

**Dragon crew:** 2 (launch['crew'])

https://reddit.com/r/spacex/comments/fjf6rr/dm2_launch_campaign_thread/

**Comment by jakewmeyer** [comment]
Mostly updated. Crew info was a bit of an afterthought back in v3, and will only be available in v4, which should be live before this launch.
