### ISSUE TITLE
Starlink 7 missing data

### ISSUE THREAD

**Issue by 499602D2** [r-spacex/SpaceX-API#323]
**Core:** B1049.4

**Landing:** OCISLY

https://reddit.com/r/spacex/comments/gamcbr/starlink7_launch_campaign_thread/

**Comment by jakewmeyer** [comment]
Updated

**Comment by 499602D2** [comment]
Nitpicks, but seems that the reuse count was set to 3 instead of 4, at least on my end

**Comment by jakewmeyer** [comment]
Reuse count in `/cores`? Or in the launch itself?
