### ISSUE TITLE
Latest Flights have lots of null values

### ISSUE THREAD

**Issue by SteveR92** [r-spacex/SpaceX-API#325]
Entries like details, images, and launch success all appear to be null for the last 10 or so flights. Is there a particular reason for this and will this continue to be the case?

**Comment by jakewmeyer** [comment]
Those are upcoming launches, so little is known until a few days before launch usually.

Details are filled out a bit earlier, once the subreddit creates campaign threads for the launch. 

Images are from the official SpaceX photography team, those usually take a day or two to get uploaded to Flickr.
