### ISSUE TITLE
Flight numbers are inconsistent in new configuration

### ISSUE THREAD

**Issue by waterskier2007** [r-spacex/SpaceX-API#33]
here: https://api.spacexdata.com/v1/launches/upcoming

flight numbers are strings

whereas here: https://api.spacexdata.com/v1/launches

flight numbers are numbers

**Comment by jakewmeyer** [comment]
A carryover from the old database, when all the launches were in the same table, and it was filtering based on the value.

The field should only be Ints now, and I added tentative predicted flight numbers to the upcoming ones.
