### ISSUE TITLE
Demo Mission 2 - no crew information.

### ISSUE THREAD

**Issue by PiotrRut** [r-spacex/SpaceX-API#330]
Would be nice to say this updated, with either the number of crew members of their names for this and future crewed missions

**Comment by jakewmeyer** [comment]
That was added as a bit of an afterthought, and the feature was pushed to v4. 

V4 is pretty close to being done, and that'll have full support for crew.

**Comment by PiotrRut** [comment]
> That was added as a bit of an afterthought, and the feature was pushed to v4. 
> 
> 
> 
> V4 is pretty close to being done, and that'll have full support for crew.

Awesome! Thanks a lot!!
