### ISSUE TITLE
Falcon Heavy Test Flight - bad video link?

### ISSUE THREAD

**Issue by stanifert** [r-spacex/SpaceX-API#331]
Getting “This video is unavailable” response from YouTube. Or is it just me?

**Comment by jakewmeyer** [comment]
Hmm, working correct for me.

This is flight 55, correct?

**Comment by stanifert** [comment]
> Hmm, working correct for me.
> 
> 
> 
> This is flight 55, correct?

Yes. Working now! Not sure what I was doing wrong. Thanks!
