### ISSUE TITLE
New App - XLaunch

### ISSUE THREAD

**Issue by stanifert** [r-spacex/SpaceX-API#332]
Hi there! I released my app 'XLaunch' on the iOS App Store last month, making use of this great API. It supports watching livestreams, viewing photos, and tons more. Would love to have it added to the known apps list! Anyone interested can download it for free.

**Comment by jakewmeyer** [comment]
Fantastic work on the app, it's already on my front page 👍 

Added in 312556ff36f5e25f075569842205a186af0d8fa6

**Comment by stanifert** [comment]
Thanks!!
