### ISSUE TITLE
New Website using the API - https://www.spacexandmars.com/

### ISSUE THREAD

**Issue by jiachengzhang1** [r-spacex/SpaceX-API#333]
Hello! I created [SpaceX and Mars](https://www.spacexandmars.com/) making use of this API as a project for learning web development. 

The website displays SpaceX missions and weather on Mars. Would you add the website to the known app page, I would be appreciate it! The source code is on https://github.com/jiachengzhang1/spacex-and-mars/ 

Thank you 🙏

**Comment by jakewmeyer** [comment]
Added! Thanks 👍
