### ISSUE TITLE
Falcon Heavy Test Flight (#55) - YouTube video link changed?

### ISSUE THREAD

**Issue by stanifert** [r-spacex/SpaceX-API#336]
I'm getting back a link to a CNET video on YouTube for the video link (~13min long), rather than the official stream from SpaceX (~34min long). Am I missing something or was the link changed?

**Comment by jakewmeyer** [comment]
I switched it to a cnet re-upload of the launch while testing, but the original issue got closed before I could comment.

So you saw it working, and probably thought the original video was working again. 

Just switched it back to the original, still seems to be broken in the app. Not sure if something is wonky with the video itself, or maybe some ios issue.

**Comment by stanifert** [comment]
Sorry about that! I'm seeing the SpaceX livestream link now, and the link is good.

Now that I've looked deeper into it, it seems like the error is with video playback, not the API. I'm using XCDYouTubeKit (https://github.com/0xced/XCDYouTubeKit) for video playback so looks like the issue is there.
