### ISSUE TITLE
[Data Addition] Demo-2 video links now live on SpaceX's YouTube, old livestream link is dead

### ISSUE THREAD

**Issue by stanifert** [r-spacex/SpaceX-API#337]
Demo 2 launch videos are now live on SpaceX's YouTube.

Old link (livestream, no longer works): https://www.youtube.com/watch?v=bIZsnKGV8TE&feature=youtu.be

New links:
Part 1 (Launch): https://www.youtube.com/watch?v=xY96v0OIcK4
Part 2 (Coast): https://www.youtube.com/watch?v=z9uAN6YNkP0
Part 3: (Approach/Docking): https://www.youtube.com/watch?v=AIyonw6LEOs

**Comment by jakewmeyer** [comment]
Main launch link updated, no support for multiple webcast links in v3, adding to the v4 feature list.
