### ISSUE TITLE
Inconsistent date formats

### ISSUE THREAD

**Issue by waterskier2007** [r-spacex/SpaceX-API#34]
example url https://api.spacexdata.com/v1/launches/upcoming

FormoSat-5
launch_date_utc: 2017-08-24T18:50:00

X-37B OTV-5
launch_date_utc: 2017-08-28T00:00:00**Z**

As you can see, sometimes they specify a time zone, sometimes not...

**Comment by jakewmeyer** [comment]
Corrected, should be in line with all other previous and upcoming launches
