### ISSUE TITLE
launch payload customer is oddly formatted

### ISSUE THREAD

**Issue by waterskier2007** [r-spacex/SpaceX-API#35]
shouldn't customers be an array of strings? instead of listing them as customer_1, customer_2?

the way it is right now makes it tough to parse because there could be an unknown number of customers. I think it should be something like...

customers: ["NASA", "TSA", "USAF"]

**Comment by jakewmeyer** [comment]
I'll make a pass on the customers to correct this 👍

**Comment by waterskier2007** [comment]
looks like upcoming have been fixed so far :)

**Comment by jakewmeyer** [comment]
Should be live across the board now 👍

**Comment by waterskier2007** [comment]
nice!
