### ISSUE TITLE
No flight time for COTS 1

### ISSUE THREAD

**Issue by AlbericTrancart** [r-spacex/SpaceX-API#354]
When I look at the COTS 1 launch, I see: flight_time_sec: null
From wikipedia: [3 hours, 19 minutes](https://en.wikipedia.org/wiki/SpaceX_COTS_Demo_Flight_1)

=> 11940 seconds

Thanks for updating this :slightly_smiling_face:

**Comment by jakewmeyer** [comment]
Updated, thanks!
