### ISSUE TITLE
Maintaining data on Kaggle

### ISSUE THREAD

**Issue by vopani** [r-spacex/SpaceX-API#355]
Thanks for this API and data.

Is it ok to publish this data on [Kaggle](https://www.kaggle.com/datasets) with the same licensing terms and linking the GitHub / API as the source?

It will enable data scientists to build notebooks and projects around the data.

**Comment by jakewmeyer** [comment]
Absolutely!

**Comment by vopani** [comment]
Thanks! I have published the most relevant datasets (will add other sources and fields in subsequent versions) in tabular format: https://www.kaggle.com/rohanrao/rspacex-data

I have used the **CC0-PublicDomain** license which has no constraints on how it can be used. Let me know if you'd recommend another license for using the data or if you'd like any other changes in the dataset.

**Comment by jakewmeyer** [comment]
Looks good to me 👍
