### ISSUE TITLE
V3 and V4 launch ids are different

### ISSUE THREAD

**Issue by marcozambi** [r-spacex/SpaceX-API#357]
I started to play with V4 to migrate the tools I built around V3, and I noticed that the launch id for V4 entries are different than the ones in V3.
This is a disruptive change.
I used the launch id as unique reference for GET calls to retrieve specific launches' data, and they are all going to break if I don't build a correspondence table :/

**Comment by jakewmeyer** [comment]
Disruptive, but for a good reason. One of the biggest complaints I got about previous version was the lack of truly unique id's. Sure, flight number *should* be unique for launches, but there's was a lack of consistency across the categories about what should be used as an id.

I assume you're referencing an endpoint like `GET /launches/89`. 

This is still possible, and while it's not as terse as before, the flexibility should be much improved. In this case, a `POST` to `https://api.spacexdata.com/v4/launches/query` with a body of:
```json
{
  "query": {
      "flight_number": 89
  },
  "options": {
      "limit": 1
  }
}
```

Would get a similar response.

**Comment by marcozambi** [comment]
Hi Jake,
thanks for your answer. Actually I've always stored and used the _id property, which has always remained unique afaik. I then passed it to GET requests through the flight_id parameter.
Would it then be possible to reference a specific flight/launch through its unique id (not flight number) with V4?

**Comment by jakewmeyer** [comment]
No worries, glad we got it figured out 👍
