### ISSUE TITLE
Starlink orbit tracking

### ISSUE THREAD

**Issue by jakewmeyer** [r-spacex/SpaceX-API#359]
* Add an endpoint purely for Starlink sats and orbit tracking `/starlink`
* Add auto updater job to fetch orbits

**Comment by jakewmeyer** [comment]
Model should adhere to the standards for [orbit data messages](https://public.ccsds.org/pubs/502x0b2c1.pdf)

**Comment by jakewmeyer** [comment]
Current draft schema is the following:

```json
{
  "spaceTrack": {
    "CCSDS_OMM_VERS": "2.0",
    "COMMENT": "GENERATED VIA SPACE-TRACK.ORG API",
    "CREATION_DATE": "2020-06-19 21:36:08",
    "ORIGINATOR": "18 SPCS",
    "OBJECT_NAME": "STARLINK-55",
    "OBJECT_ID": "2019-029AK",
    "CENTER_NAME": "EARTH",
    "REF_FRAME": "TEME",
    "TIME_SYSTEM": "UTC",
    "MEAN_ELEMENT_THEORY": "SGP4",
    "EPOCH": "2020-06-19 20:00:01.000224",
    "MEAN_MOTION": 15.58451914,
    "ECCENTRICITY": 0.0000165,
    "INCLINATION": 52.993,
    "RA_OF_ASC_NODE": 151.6812,
    "ARG_OF_PERICENTER": 29.9824,
    "MEAN_ANOMALY": 201.95,
    "EPHEMERIS_TYPE": 0,
    "CLASSIFICATION_TYPE": "U",
    "NORAD_CAT_ID": 44268,
    "ELEMENT_SET_NO": 999,
    "REV_AT_EPOCH": 6007,
    "BSTAR": 0.00056,
    "MEAN_MOTION_DOT": 0.00043234,
    "MEAN_MOTION_DDOT": 0,
    "SEMIMAJOR_AXIS": 6770.273,
    "PERIOD": 92.399,
    "APOAPSIS": 392.25,
    "PERIAPSIS": 392.027,
    "OBJECT_TYPE": "PAYLOAD",
    "RCS_SIZE": "LARGE",
    "COUNTRY_CODE": "US",
    "LAUNCH_DATE": "2019-05-24",
    "SITE": "AFETR",
    "DECAY_DATE": null,
    "DECAYED": 0,
    "FILE": 2768934,
    "GP_ID": 155985474,
    "TLE_LINE0": "0 STARLINK-55",
    "TLE_LINE1": "1 44268U 19029AK  20171.83334491  .00043234  00000-0  56046-3 0  9991",
    "TLE_LINE2": "2 44268  52.9926 151.6812 0000165  29.9824 201.9500 15.58451914 60072"
  },
  "version": "v0.9",
  "launch": "5eb87d30ffd86e000604b378",
  "id": "5eed7714096e590006985635"
}
```

**Comment by jakewmeyer** [comment]
Auto update is functional, and version and launch are calculated from existing launch data

Updating should be pretty hands off, as new Starlink sats get added to their database, they automatically get added to ours. Only update will be on the calculation of Starlink version, once they push past v1.0.

**Comment by jakewmeyer** [comment]
@AlbericTrancart Since this was one of your feature requests, what kinds of aggregations are you looking for?

**Comment by AlbericTrancart** [comment]
Looks nice! Right now the Starlink data on SXS is manual.
I'm doing the upgrade to the v4 then I'll automate the Starlink section.
As I'm using GatsbyJS, the site is rebuilt every 24 hours so there are no performance concerns: I'll aggregate all those numbers at build time.

**Comment by AlbericTrancart** [comment]
Ok @jakewmeyer I found a small issue. It seems that 3 deorbited satellites are missing (with these ids: https://en.wikipedia.org/wiki/Starlink#Deorbited_satellites)

Otherwise great data, the [Starlink section](https://www.spacexstats.xyz/#starlink-in-space) is completely automated now!

**Comment by jakewmeyer** [comment]
Tweaked the query to spacetrack a bit and they should all be in there now 👍 

Awesome!

**Comment by AlbericTrancart** [comment]
Yes the tweak worked, it works perfect :ok_hand:

**Comment by stazrad** [comment]
This is awesome @jakewmeyer! I was just looking at the draft schema- is there anyway to use lat/long (or some other positioning logic) to indicate where (over earth) the satellites are for mapping purposes?

**Comment by stazrad** [comment]
@AlbericTrancart just saw you had the same idea to map the 🛰️ around the 🌍  -- I'm totally down to make that happen with https://github.com/MonsantoCo/ol-kit 😁

**Comment by jakewmeyer** [comment]
Actually pretty easy ask. There's a nice lib [tle.js](https://github.com/shashwatak/satellite-js), that does most of the heavy lifting math required.

Should be straightforward for me to integrate into the updater

**Comment by jakewmeyer** [comment]
Looks like they also have some neat methods for calculating satellites visible from a position, ground tracking, and info in relation to a position. I'll integrate those as well into some new routes.

**Comment by stazrad** [comment]
oh nice- looks like i just need the `TLE_LINE0`, `TLE_LINE1`, `TLE_LINE2` already provided in the payload -- thanks for the tip about that lib^

**Comment by jakewmeyer** [comment]
Feel free to use either 🤷‍♂️ , I'll expose the results for those using other languages

**Comment by 414412** [comment]
hi .how do we use Starlink orbit tracking for iphone

**Comment by stazrad** [comment]
@jakewmeyer added tracking of the ISS & historical SpaceX launches to our demo site on [ol-kit](https://github.com/MonsantoCo/ol-kit/pull/133) (checkout the [screenshots in the PR](https://github.com/MonsantoCo/ol-kit/pull/133))...lmk when you standup the endpoint for the Starlink 🛰️ & I'd love to add those as well!

**Comment by jakewmeyer** [comment]
@stazrad awesome work 👍 

Lat/Lon, height, and velocity are live on the Starlink endpoints, and get updated hourly with the orbit updates. 

Hoping to get to the rest of the [tle.js](https://github.com/davidcalhoun/tle.js/) integration this weekend, for stuff like ground tracks, individual sat info from a position, and getting visible sats from a position.

**Comment by head898** [comment]
https://ropsten.etherscan.io/tx/0x0a33e474cf1e237db0957c474ae270d46a1c34c8394cebb75a3cae96e20c9606
