### ISSUE TITLE
Starlink-9 missing data

### ISSUE THREAD

**Issue by 499602D2** [r-spacex/SpaceX-API#366]
- Boosted by B1051.4

- 4 past flights for this core (DM-1, RADARSAT, Starlink-3, Starlink-6)

- Payload Starlink sats + BlackSky 5 & 6

- Used ASDS unknown, but probably JRTI considering OCISLY is docked in Port Canaveral atm.

**Comment by 499602D2** [comment]
And source: https://old.reddit.com/r/spacex/comments/h8mold/starlink9_launch_campaign_thread/

**Comment by jakewmeyer** [comment]
Updated 👍
