### ISSUE TITLE
Missing some photo URL

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#368]
It seems that most of SpaceX-hosted photos are not publicly available anymore, throwing a 404 HTTP error :/

**Comment by jakewmeyer** [comment]
The flickr images? Can I see a few examples?

**Comment by jesusrp98** [comment]
Just the `spacex.com` links are broken. They should be replace with other Flickr photos, or just delete them.

This links are related to the Dragon V1 capsule.
```
 "flickr_images": [
      "https://www.spacex.com/sites/spacex/files/styles/media_gallery_large/public/2015_-_04_crs5_dragon_orbit13.jpg?itok=9p8_l7UP",
      "https://www.spacex.com/sites/spacex/files/styles/media_gallery_large/public/2012_-_4_dragon_grapple_cots2-1.jpg?itok=R2-SeuMX",
      "https://farm3.staticflickr.com/2815/32761844973_4b55b27d3c_b.jpg",
      "https://farm9.staticflickr.com/8618/16649075267_d18cbb4342_b.jpg"
    ],
```

**Comment by jakewmeyer** [comment]
Removed the broken links and replaced them with some more permanent ones 👍

**Comment by jesusrp98** [comment]
Great! I've also found some broken photos within the Falcon 1 vehicle, at the `rockets` endpoint. Don't know if the old info is cached and will be updated in the near future :)

**Comment by jakewmeyer** [comment]
Images for rockets should be fixed too
