### ISSUE TITLE
Headers request - Add Cache-Control headers to responses

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#373]
Hi @jakewmeyer 

I've noticed no `Cache-Control` headers have been added to the API responses. Since applications might want to optimise their caching providing the `Cache-Control` headers could be very useful. Would it be possible to add these? I am for example using Retrofit to make API calls. If `Cache-Control` is added I can less frequent make calls to the API.

Cheers!
Jeroen

**Comment by jakewmeyer** [comment]
How deep do we want to go on this?

Are you just looking for max age?

**Comment by jeroenboumans** [comment]
I'm trying to implement offline caching for looking up data without the need for internet connection so I guess *max-age* Cache-Control would be fine for now?

**Comment by jakewmeyer** [comment]
Any preference on time? If not, I'll probably just set it based on the existing TTL's for Redis

**Comment by jeroenboumans** [comment]
No preference at the moment. :)

**Comment by jakewmeyer** [comment]
Changes are added and live in v4. Is this something you need in v3?

**Comment by jeroenboumans** [comment]
Would be nice if these can be added to the v3 as well so I can quick add this to my client if it's not that much work. Will migrate to v4 in the upcoming month probably.

**Comment by jakewmeyer** [comment]
Added and live in v3

**Comment by jeroenboumans** [comment]
I noticed the `max-age` value in the headers is `30` seconds. Is this correct?

**Comment by jakewmeyer** [comment]
For launches, yes. Long enough that the db doesn't get hammered too hard during heavy traffic, yet short enough that time sensitive updates don't take too long.

**Comment by jeroenboumans** [comment]
Thanks for adding! :)

**Comment by jeroenboumans** [comment]
Hi @jakewmeyer, I was looking into the response headers a bit more and it might be interesting to add an [`ETag`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) header. This way the API doesn't have to send a full response when the client has a certain version of the requested resource. Interesting enough to apply to the API? Might lower the amount of db queries/api resources.

**Comment by jakewmeyer** [comment]
Added etag support for v3 and v4. However, this only works for conditional GET requests, and while it works great for v3, v4 is much more heavy on POST requests, so this won't do much for that.
