### ISSUE TITLE
V3 / V2 Deprecated - November 7th, 2020

### ISSUE THREAD

**Issue by jakewmeyer** [r-spacex/SpaceX-API#380]
* V3 / V2 data will no longer receive updates after **November 7th, 2020**
* V3 / V2 endpoints will remain live forever, to preserve any existing links
* After the above date, a warning will be added to all V2 and V3 responses to notify the change

**Comment by Tearth** [comment]
I really liked V2, sad it's going to retire. Maybe we should add to https://github.com/r-spacex/SpaceX-API/blob/master/docs/clients.md a new column indicating which API version is supported? I predict that a few of them will be outdated after deadline.

**Comment by jakewmeyer** [comment]
I've toyed with the idea in the past of making a compatibility layer for v4 that translates the data into v3 and v2 compliant responses, but the issue is with the custom queries/filtering. Since the data is stored differently, translating the queries is nearly impossible. So then it became a decision between having current data with broken filtering vs. functional queries with old data.

Agreed on the version listing 👍

**Comment by Tearth** [comment]
Understandable, I've checked the new query system today for the first time (I was stick with V2 because of the library) and it looks quite different from the old one, so no doubts it's hard to do a translation between them. Version listing will help people to choose the library which supports the newest API with fresh data. Hopefully, most of them will be updated (and I will try to update mine too).

**Comment by jakewmeyer** [comment]
If necessary, I can extend the date further, just trying to get the ball rolling

**Comment by Tearth** [comment]
No problem, I think a month is sufficient for rewriting a library. V4 looks really cool and more consistent, can't wait to use it!

**Comment by jesusrp98** [comment]
What do you think about extending the deprecation time to September 2020?

Think a month time is a bit short ://

**Comment by waruss321** [comment]
What are the main differences between v4 and v3, just wondering the reasoning behind the move and what the advantages are going to be. Also I agree that September 2020 would be a more ideal date to give people time to rewrite their code. Awesome work ++

**Comment by jakewmeyer** [comment]
Updated to September 👍

**Comment by jakewmeyer** [comment]
@waruss321 Most of the improvements are behind the scenes, but some of the bigger user facing improvements:

* All items of the api now have a truly unique uuid's

* Less confusing date fields

* More flexibility with custom queries. Previously the api relied on a custom query builder that required a ton of maintenance, and limited the potential of queries. Now the power is back to the user, and it allows for better customization of only the data you want.

**Comment by timisenman** [comment]
Just to confirm: All good on my end here. Thanks for the extensions!

**Comment by jakewmeyer** [comment]
Pushing the date 1 week
