### ISSUE TITLE
App URL change

### ISSUE THREAD

**Issue by jimmyboix** [r-spacex/SpaceX-API#391]
Hi @jakewmeyer ,

Hoping to get line 16 in apps.md swapped out with below (custom domain expiring):

`| [SpaceFax](https://spacefax1.web.app) | Website | [James Hendrie](https://github.com/jimmyboix) | [GitHub](https://github.com/jimmyboix/SpaceFax) | |`

thanks
Jimmy

**Comment by jakewmeyer** [comment]
Updated 👍
