### ISSUE TITLE
md doc tools?

### ISSUE THREAD

**Issue by luanweijie** [r-spacex/SpaceX-API#394]
I want to know what tool to export md document?

**Comment by jakewmeyer** [comment]
What file? What format?

**Comment by luanweijie** [comment]
just like the file dir (/docs/v4/*),  is this by any postman generate tools?

**Comment by luanweijie** [comment]
In other words, how is the api document generated

**Comment by jakewmeyer** [comment]
v4 docs aren't generated, it's just how I decided to structure it

**Comment by luanweijie** [comment]
thanks a lot
