### ISSUE TITLE
New App - Spacexopedia

### ISSUE THREAD

**Issue by TheAlphamerc** [r-spacex/SpaceX-API#395]
Hi, First of all thanks for creating such an amazing API. I have used this api to create [Spacexopedia](https://play.google.com/store/apps/details?id=com.thealphamerc.flutter_spacexopedia) app.

Android App link:- https://play.google.com/store/apps/details?id=com.thealphamerc.flutter_spacexopedia
Project Repository:- https://github.com/TheAlphamerc/flutter_spacexopedia

**Comment by jakewmeyer** [comment]
Added 👍

**Comment by TheAlphamerc** [comment]
Thanks @jakewmeyer
