### ISSUE TITLE
Launchpad/Landpad status field

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#398]
Model returned from the Launchpads endpoint contains `Status` field which is defined as enum (https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/launchpads/schema.md):
```
"status": {
  "type": "String",
  "enum": [
    "active",
    "inactive",
    "unknown",
    "retired",
    "lost",
    "under construction"
  ],
  "required": true
},
```

The model returned from the Landpads endpoint has also a similar one, but in the schema, it's defined just as a plain string (https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/landpads/schema.md):
```
"status": {
  "type": "String",
  "default": null
},
```

Shouldn't be the second one exactly the same as the first one? From what I saw comparing data from both endpoints, this field has exactly the same meaning and the same values.

**Comment by jakewmeyer** [comment]
Whoops, looks like I missed that one, model is updated 👍

**Comment by Tearth** [comment]
Cool! It would be also nice to update the schema of Landpads endpoint:
https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/landpads/schema.md

**Comment by jakewmeyer** [comment]
Updated

**Comment by Tearth** [comment]
Thanx
