### ISSUE TITLE
Possible double encoding of JSON

### ISSUE THREAD

**Issue by HarvsG** [r-spacex/SpaceX-API#40]
```
{
  flight_number: 45,
  launch_year: '2017',
  launch_date_utc: '2017-08-14T16:31:00Z',
  launch_date_local: '2017-08-14T12:31:00-04:00',
  rocket: 'Falcon 9',
  rocket_type: 'FT',
  core_serial: 'B1039',
  cap_serial: 'C113',
  launch_site: {
    site_id: 'ksc_lc_39a',
    site_name: 'KSC LC 39A'
  },
  payloads: [
    [Object]
  ],
  launch_success: null,
  reused: null,
  land_success: null,
  landing_type: null,
  landing_vehicle: 'LZ-1',
  links: {
    mission_patch: null,
    reddit_campaign: 'https://www.reddit.com/r/spacex/comments/6mrga2/crs12_launch_campaign_thread/',
    reddit_launch: null,
    reddit_recovery: null,
    reddit_media: null,
    presskit: null,
    article_link: null,
    video_link: null
  },
  details: null
}

```
I am getting lots of errors in my code

When I do `JSON.parse(data)` on the response I get from the server I get the output as above. Notice how in `data.payloads[0]` there is just `[Object]`. But `data.lauch_site` is fine.

After some research, I think this could be because the JSON is 'double encoded', although I'm not sure if that is something that is the responsibility of the server or the client.

Or I have got completely the wrong end of the stick!

Edit: This is the code I use to parse the JSON data, note that it isn't throwing an error, only later when I try to access data within `data.payloads[0]`

```
      res.setEncoding('utf8');
      let rawData = '';
      res.on('data', (chunk) => { rawData += chunk; });
      res.on('end', () => {
        try {
          const parsedData = JSON.parse(rawData);
          console.log(rawData);
          console.log(parsedData);
          // some code to pick the relevant company data from the user request (request.body.result.parameters.CompanyParams)
          callback(app, parsedData)
        } catch (e) {
          console.error(e.message);
        }
```

**Comment by jakewmeyer** [comment]
@HarvsG not 100% sure here

If you stringify the payload object, does it return normally? Do Javascript objects allow arrays inside them? It looks like it was just stored as an object, and has to be converted back out to a string?

From what I can tell, if it was double encoded, it would have two sets of "" around each key/value

Again, I'm not really sure, and don't have enough Javascript experience to know for sure

**Comment by HarvsG** [comment]
> Or I have got completely the wrong end of the stick!
I am a fool.

There was nothing wrong with the server side.

The `[Object]` notation that appears seems to be a quirk of the `console.log()` function.
The data structure was absolutely fine, my issue was that a completely different line was evaluating `data.payloads[1]`, this was causing the error, because if there is only one customer then it doesn't exist!

**Comment by jakewmeyer** [comment]
No worries, if anything else weird happens, just let me know 👍
