### ISSUE TITLE
Validation of Launch Numbers 98 and 99

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#400]
The next two launches have slightly awkward new numbers, so I wanted to create an issue to make sure the data is correct:
- The next launch is Starlink 9, but is launch 99
- ANASIS II is launch 98, but is after Starlink 9 on the calendar. 

Is this the correct numbering?

**Comment by timisenman** [comment]
Looking at the launch thread, it looks like the launch date is still TBD: https://www.reddit.com/r/spacex/comments/h8mold/starlink9_launch_campaign_thread/

Can this launch be marked with its TBD property as true?

**Comment by jakewmeyer** [comment]
Yes, numbering is correct according to the subreddit [manifest](https://old.reddit.com/r/spacex/wiki/launches/manifest), which keeps the launch order and dates updated in the api.

Looks like I had a slight bug in the updater, and it wasn't setting the `tbd` field properly. It's fixed now, and now when `tbd` appears in the manifest date, the field is set.

**Comment by benjidea** [comment]
I'm not sure this belongs here,
But the "date_utc" for the upcoming Lauches #98 #99 and #100 is in the past (July 1st)

**Comment by jakewmeyer** [comment]
@benjidea All three are slated for `2020 July`, see the [docs](https://github.com/r-spacex/SpaceX-API/tree/master/docs/v4#launch-date-faqs) for an explanation on partial dates.
