### ISSUE TITLE
Error code inconsistency between docs and API

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#408]
The documentation states (for every endpoint which returns a single object) that for request with non-existing in database ID should return 404 code (Not Found), but it seems that API returns 400 (Bad Request) - is this a bug or typo in docs? Personally I think that 404 would be more logical and descriptive than generic 400.

For https://api.spacexdata.com/v4/dragons/5e9d058759b1ff75a7ad5f8f API returns "Not Found" text and 400 error code:
![image](https://user-images.githubusercontent.com/26147774/87666641-4157fb80-c769-11ea-98d2-6f4985f1dab9.png)

**Comment by jakewmeyer** [comment]
This was a bug in the route error handlers, fix is live

**Comment by Tearth** [comment]
Nice, thanx
