### ISSUE TITLE
CORS not enabled?

### ISSUE THREAD

**Issue by andrewconnell** [r-spacex/SpaceX-API#41]
Did a change happen recently that disabled CORS? I was planning to use this data in a demo at a conference this week. The conference is unrelated to SpaceX, NASA or space in general... just a tech conference and thought it was a cool dataset. 

But suddenly seeing errors related to CORS. The response headers look very different too... looking back through the commits I don't see anything that says CORS was disabled.

**Comment by jhpratt** [comment]
Nope, still enabled!

[Here's the code.](https://github.com/r-spacex/SpaceX-API/blob/master/src/app.rb#L32)

**Comment by andrewconnell** [comment]
Damn... you responded too quick (I was just about to delete the issue I submitted). 

My bad... stoopid error on my part. Thanks for making this available!

**Comment by jakewmeyer** [comment]
@andrewconnell Glad it's resolved. Haven't touched the CORS support since it was enabled a few weeks ago. What fixed it? Out of curiosity...

**Comment by andrewconnell** [comment]
"thinner fingers"

IOW, fixed a stupid mistake on my part. 

I'd love to help & contribute to the project, but I don't know Ruby :-/ Will keep an eye out for ways I can help...

**Comment by jakewmeyer** [comment]
No worries! If you have any suggestions or ideas, I'm sure we can find something for you to help out with. 👍
