### ISSUE TITLE
Starlink-9 needs is_tentative/net to be true

### ISSUE THREAD

**Issue by CodyDSmith** [r-spacex/SpaceX-API#415]
For V3, tentative_max_precision is currently "month", but is_tentative is false.  This means the API is giving an exact date for Starlink-9 of midnight on July 10, which was over 11 days ago.

For V4, date_precision is currently "month", but net is false.  I assume "net" is the V4 replacement of is_tentative? I don't see another way to determine when the date becomes exact and date_precision should be ignored.

**Comment by CodyDSmith** [comment]
This also appears to be the case for SAOCOM 1B.

**Comment by CodyDSmith** [comment]
I see that "is_tentative" has been changed to true on V3 for Starlink-9. For V4, "net" is still false which confuses me, but I see that "tbd" is now true for V3 and V4.

Some documentation on how to properly interpret and combine "net", "tbd", "date_precision", and "date_utc" for V4 would be greatly appreciated.

**Comment by jakewmeyer** [comment]
See [this](https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/README.md#launch-date-faqs) section in the v4 docs

For example, the launch manifest has the Starlink 9 date set as `2020 TBA`.

If the date contains `TBD` or `TBA`, `tbd` is set as true
If the date contains `NET`, `net` is set as true

NET isn't used often, but it's there for the rare cases

**Comment by CodyDSmith** [comment]
I've read that section. I meant more of a logic flow. For example, according to the docs, "date_precision" doesn't get more detailed than "hour" so what value should we check to know when to start ignoring "date_precision" and accept the minutes and seconds of "date_utc"? If "net" is false and "tbd" is false then ignore "date_precision" because the date is exact? This was easy in V3 because it had "is_tentative".

**Comment by jakewmeyer** [comment]
`NET` or `TBD` could be set for any date precision potentially, so I wouldn't use them to determine how much of the date is valid. Technically every upcoming launch could be considered `TBD` or `NET`, these are just to give a bit more context if needed.

So far, I've never seen a time posted without minutes, so we never bothered adding a level below `hour`. Even if this doesn't include minutes or seconds, this is more than precise enough for a future launch.

**Comment by CodyDSmith** [comment]
Oh OK, if "date_precision" is "hour" then it is safe to use the entire date, including minutes and seconds. "hour" is full precision. A blurb in the docs about that might be a good idea. Thanks for the help!

**Comment by jakewmeyer** [comment]
I'll add a note 👍
