### ISSUE TITLE
SAOCOM 1B Date

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#417]
The API currently has the date set for tomorrow, but it looks like it's slated for a few days from now, on the 25th:
https://www.reddit.com/r/spacex/comments/ffoz5r/saocom_1b_launch_campaign_thread/

**Comment by pvegh** [comment]
Also it should be shown as /next instead of Starlink #9, shouldn't it?

**Comment by jakewmeyer** [comment]
The API tracks the order of launches on the subreddit [manifest], and since both dates are shaky currently, the order could probably go either way.
