### ISSUE TITLE
Latest version v3 vs v4

### ISSUE THREAD

**Issue by pvegh** [r-spacex/SpaceX-API#418]
I see some inconsistency here.
1. github says latest is v4
2. https://docs.spacexdata.com/?version=latest shows v3
3. Postman export is also v3

Is v4 really the current stable?

**Comment by jakewmeyer** [comment]
The docs live in the repo now for v4 onward, see [here](https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/README.md)

**Comment by pvegh** [comment]
Can we have a postman collection for v4 as well? I liked it very much, easy to quickly test it.

**Comment by jakewmeyer** [comment]
Happy to 👍

**Comment by jakewmeyer** [comment]
Added, see the top of the v4 [docs](https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/README.md) for the link

**Comment by pvegh** [comment]
Maybe just add some hint about v4 to the top of the v3 docs page, saying latest might misdirect people.
https://docs.spacexdata.com/?version=latest
Otherwise this can be closed, thanks!

**Comment by jakewmeyer** [comment]
Will do, thanks 👍
