### ISSUE TITLE
launches/next endpoint returns old launch

### ISSUE THREAD

**Issue by waterskier2007** [r-spacex/SpaceX-API#419]
https://api.spacexdata.com/v3/launches/next returns the Starlink-9 launch, which is not the "next" launch.

**Comment by CodyDSmith** [comment]
I believe launch order is set from the reddit manifest which has Starlink-9 as the next launch: 
 https://old.reddit.com/r/spacex/wiki/launches/manifest

No upcoming launches have a solid date yet so "next" is fairly irrelevant.

**Comment by waterskier2007** [comment]
Alright, thank you for the information 👍
