### ISSUE TITLE
V3 > V4 converting question

### ISSUE THREAD

**Issue by warwickofthegh** [r-spacex/SpaceX-API#420]
Just starting looking at moving my site from using the v3 api to v4 and I think I'm missing the best way to use v4.

V3 - To get data for upcoming 20 launches I could call the the /launchs API 1 time, and this would contain launch, payload, launchpad, rocket data.

V4 - to get the same data I call launches, then for each launch I need to call /payload/:id, /launchpad/:id, rockets/:id for each record,  resulting in 60+ API calls just to compile a basic upcoming launch list.

What am I missing here, how do I use v4 to get all upcoming launch data with least amount of API calls.

... love the work you do with this, thanks again!

**Comment by jakewmeyer** [comment]
Best way is to use the `query` endpoint for launches.

`POST https://api.spacexdata.com/v4/launches/query`

With the body:

```json
{
  "options": {
    "populate": [
      "cores.core",
      "cores.landpad",
      "ships",
      "crew",
      "capsules",
      "payloads",
      "launchpad",
      "rocket"
    ]
  }
}
```

This will populate the fields with id's with the corresponding objects.

If you want to cut down on the response size, you can specify the fields you want like so:

```json
{
  "options": {
    "populate": [
      "cores.core",
      "cores.landpad",
      "ships",
      "crew",
      "capsules",
      "payloads",
      "launchpad",
      {
          "path": "rocket",
          "select": {
              "name": 1
          }   
      }
    ]
  }
}
```

See [this](https://mongoosejs.com/docs/api.html#query_Query-populate) for all possible options, but the above should be what you're looking for.

**Comment by warwickofthegh** [comment]
ah no I see, I'll give it a run thanks again!
