### ISSUE TITLE
Flight Club mission telemetry resources can be made dynamic

### ISSUE THREAD

**Issue by murphd37** [r-spacex/SpaceX-API#43]
``GET https://api.spacexdata.com/v1/launches/latest`` returns a JSON response which points to a static Flight Club simulation result in the ``telemetry`` attribute. The ``id`` in the Flight Club query string is the id of a specific simulation - so this will never update itself. 

Rather than have the returned URL in the form

``https://www.flightclub.io/results/?id=5f90f4b8-3e5f-41ef-aa1a-4551254b2589&code=OTV5``

a better format is to remove the ``id`` attribute so you're left with

``https://www.flightclub.io/results/?code=OTV5``

________________________

What Flight Club does behind the scenes is find the ``id`` of the most recent, most accurate and up-to-date mission simulation. Often, this estimate is made after the mission when there is a webcast to use as a reference point - so these estimates are always much more accurate than a specific guess and can only get more accurate over time, without the need for you to change anything.

If you're curious what the actual simulation ``id`` is in this scenario, you can find it by querying 

``https://www.flightclub.io:8443/FlightClub/api/v1/missions/?code=OTV5``

and looking for the ``livelaunch`` attribute.

**Comment by jakewmeyer** [comment]
Gotcha 👍  I'll make a pass and update with the correct codes

**Comment by jakewmeyer** [comment]
All FlightClub links should now be dynamic 👍
