### ISSUE TITLE
Add caught field to fairing info

### ISSUE THREAD

**Issue by jakewmeyer** [r-spacex/SpaceX-API#437]
For example, with Starlink 9 the fairings weren't caught, but were technically fished out of the ocean and recovered.

Adding a `caught` field should make situations like this more clear.

```javascript
"fairings" : {
    "reused" : false, 
    "recovery_attempt" : true, 
    "recovered" : true,
    "caught": false,
    "ships" : [
        "5ea6ed2e080df4000697c908", 
        "5ea6ed2e080df4000697c907"
    ]
}
```

**Comment by MattoDeg** [comment]
I think maybe it should be useful to add a status for each fairing, and ultimatley maybe an unique id, because some has flown thrice. Just a suggestion, idk how hard the implementation is.

**Comment by jakewmeyer** [comment]
Dupe of #594
