### ISSUE TITLE
Add headers to HTTP responses

### ISSUE THREAD

**Issue by AlbericTrancart** [r-spacex/SpaceX-API#44]
The API should return a `Content-Type: application/json` header.
Also, a `Last-Modified:` header would be nice to allow the creation of a local cache.

**Comment by jakewmeyer** [comment]
Content type header is now set correctly.

**Comment by jakewmeyer** [comment]
Looking at solutions for the last modified problem

**Comment by jakewmeyer** [comment]
For the time being I added a Last-Modified header that I can update each time I add to the database, as a temporary solution. Looking at a better way to dynamically generate the date based on real-time updates to the database instead of updating the repo with the newest date for each change.
