### ISSUE TITLE
[v4] Typo in postman collection

### ISSUE THREAD

**Issue by fmoessle** [r-spacex/SpaceX-API#440]
Postman collection: https://app.getpostman.com/run-collection/ed4ed700dcc55b2c1f1c

All URLs under the "Rocket" folder have the following typo:
**roackets** instead of **rockets**

Example: 
https://api.spacexdata.com/v4/roackets
https://api.spacexdata.com/v4/roackets/{{id}}
https://api.spacexdata.com/v4/roackets/query
...

**Comment by jakewmeyer** [comment]
Whoops, should be fixed now
