### ISSUE TITLE
Next mission is NET:false and date_precision:month

### ISSUE THREAD

**Issue by pvegh** [r-spacex/SpaceX-API#441]
I find it confusing that both NET and date_precision exist. Do we really need both?
What do I check for in a client? "Both" doesn't seem like the best option :)
Shouldn't NET be always true if precision anything but exact?

**Comment by jakewmeyer** [comment]
Right now `NET` is purely cosmetic, and I wouldn't recommend using it for any logic decisions. It's only flagged as true if `NET` is present in the date listed on the subreddit [manifest](https://old.reddit.com/r/spacex/wiki/launches/manifest) which is rare. It's been applied inconsistently by the community and SpaceX  themselves, and there's not a clear pattern to when it's used.

**Comment by pvegh** [comment]
So date_precision is the way to go. Thanks
