### ISSUE TITLE
Are limit and sorting parameters (i.e. "/launches/past?order=desc") not supported in V4?

### ISSUE THREAD

**Issue by stanifert** [r-spacex/SpaceX-API#442]
I don't see them in the docs and seems like they are not working. For example `https://api.spacexdata.com/v4/launches/past?order=desc`  or `https://api.spacexdata.com/v4/launches/past?limit=5` returns the same data as `https://api.spacexdata.com/v4/launches/past`

I can do this sort of thing locally, but wondering if the API still supports this to save some effort.

**Comment by warwickofthegh** [comment]
it doesn't seem like any routes take in parameters any longer, all custom queries have moved to the /query route

**Comment by stanifert** [comment]
That's what I figured. Thanks!

**Comment by jakewmeyer** [comment]
Correct, it's all handled by the `/query` routes now
