### ISSUE TITLE
Data fixes

### ISSUE THREAD

**Issue by AlbericTrancart** [r-spacex/SpaceX-API#45]
- [x] Rocket names can be found with the `rocket` key for Falcon 1 and `rocket_name` for Falcon 9: it should be the same key.
- [x] CRS-8 is flagged as a reused _flight_. The core was later reused but the flight is not a reuse in itself.
- [x] CRS-8 `payload_type` is `Satelite`, it should be `Dragon 1.1`.
- [x] Almost in every satellite flight `Satellite` is mispelled as `Satelite`.

**Comment by jakewmeyer** [comment]
All corrections should be live now
