### ISSUE TITLE
Request for One Month Extension to V3 Support

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#464]
Hey all,

A couple of us had been caught off guard by the switch to V4, and our production apps are now rendered a bit helpless. 

I know there was sufficient lead time in the V2/V3 deprecation plan, but speaking for myself, I only discovered that plan yesterday, after debugging why my app wasn't updating. 

As the V4 changes are so dramatic, our app's entire networking layers need reworking, refactoring, and testing, so I'd like to ask for a tiny bit more mercy in the migration, and request extended support for V3 for a month while we learn the new API, implement it, and verify it within our apps. 

On behalf of my products, there are about 8,000 people that would be very grateful of a little bit more time 🙏.

**Comment by stanifert** [comment]
I would also greatly appreciate an extension. Let us know what you can work with, and thank you for the tireless work.

**Comment by timisenman** [comment]
Going to tag @jakewmeyer just in case it helps get eyes on this. Thanks in advance for the consideration, Jake.

**Comment by jesusrp98** [comment]
Yeah, one month extension would be awesome!

**Comment by jakewmeyer** [comment]
Happy to extend, I'll update the other issue 👍

**Comment by stanifert** [comment]
Much appreciated @jakewmeyer! Thank you.

**Comment by timisenman** [comment]
You're our collective hero @jakewmeyer! Thank you so, so much.

**Comment by timisenman** [comment]
Hey @jakewmeyer One final month would be appreciated on my end. I'm finishing the transition this week, and Apple has been extremely slow in approving new app versions, so a bit more cushion would let me seal the deal 🙏

**Comment by jakewmeyer** [comment]
Sure thing 👍  I'll update the issue

**Comment by stanifert** [comment]
@jakewmeyer appreciate the extension! I definitely could use it as well. Thank you!

**Comment by timisenman** [comment]
My hero. Thank you @jakewmeyer 🙏

**Comment by head898** [comment]
https://ropsten.etherscan.io/tx/0x0a33e474cf1e237db0957c474ae270d46a1c34c8394cebb75a3cae96e20c9606
