### ISSUE TITLE
[V4] Select just specific data to return

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#469]
I want the API to not return specific information for certain endpoints, such as small patch images inside launches, for example.
I've read the documentation and I've tried doing this but it doesn't work :/

```
{
    "options": {
        "populate": [
            {
            	"path": "links.patch",
            	"select": {
            		"small": 0
            	}
            },
        ]
    }
}
```

**Comment by jesusrp98** [comment]
Just figured out how to do this. But still having issues hiding details contained in arrays. For example:

- Hiding payload parameters of dragon info.
```
 "payloads": [
                {
                    "dragon": {
                        "capsule": null,
                        "mass_returned_kg": null,
                        "mass_returned_lbs": null,
                        "flight_time_sec": null,
                        "manifest": null,
                        "water_landing": null,
                        "land_landing": null
                    },
                    "name": "FalconSAT-2",
                    "type": "Satellite",
                    "reused": false,
                    "launch": "5eb87cd9ffd86e000604b32a",
                    "customers": [
                        "DARPA"
                    ],
                    "norad_ids": [],
                    "nationalities": [
                        "United States"
                    ],
                    "manufacturers": [
                        "SSTL"
                    ],
                    "mass_kg": 20,
                    "mass_lbs": 43,
                    "orbit": "LEO",
                    "reference_system": "geocentric",
                    "regime": "low-earth",
                    "longitude": null,
                    "semi_major_axis_km": null,
                    "eccentricity": null,
                    "periapsis_km": 400,
                    "apoapsis_km": 500,
                    "inclination_deg": 39,
                    "period_min": null,
                    "lifespan_years": null,
                    "epoch": null,
                    "mean_motion": null,
                    "raan": null,
                    "arg_of_pericenter": null,
                    "mean_anomaly": null,
                    "id": "5eb0e4b5b6c3bb0006eeb1e1"
                }
            ],
```
- Hiding rocket & launches array.
 "launchpad": {
                "name": "Kwajalein Atoll",
                "full_name": "Kwajalein Atoll Omelek Island",
                "locality": "Omelek Island",
                "region": "Marshall Islands",
                "timezone": "Pacific/Kwajalein",
                "latitude": 9.0477206,
                "longitude": 167.7431292,
                "launch_attempts": 5,
                "launch_successes": 2,
                "rockets": [
                    "5e9d0d95eda69955f709d1eb"
                ],
                "launches": [
                    "5eb87cd9ffd86e000604b32a",
                    "5eb87cdaffd86e000604b32b",
                    "5eb87cdbffd86e000604b32c",
                    "5eb87cdbffd86e000604b32d",
                    "5eb87cdcffd86e000604b32e"
                ],
                "status": "retired",
                "id": "5e9e4502f5090995de566f86"
            },

**Comment by jakewmeyer** [comment]
Hiding the arrays completely?

**Comment by jakewmeyer** [comment]
Launchpad for example:

```json
{
    "options": {
        "populate": [
            {
            	"path": "launchpad",
            	"select": {
            		"rockets": 0,
                         "launches": 0
            	}
            }
        ]
    }
}
```

This should hide the fields

**Comment by jakewmeyer** [comment]
And for the original question, this would hide the large patch link.

```json
{
  "options": {
    "select": {
      "links.patch.large": 0
    }
  }
}
```

Because links isn't a populated field, you can use a top level select. The populate select only applies to the object that was populated.

**Comment by jesusrp98** [comment]
Yeah that solves my issue. Thank you very much!!
