### ISSUE TITLE
Data about reuse ideas

### ISSUE THREAD

**Issue by AlbericTrancart** [r-spacex/SpaceX-API#47]
Now that capsule reuse is a thing and fairing reuse is not far, we should get a better definition of "reused".
My idea would be to have a section like this, depending of the vehicule type:

```
reuse: {
  booster: true,
  sidebooster1: false,
  sidebooster2: true,
  fairings: true,
  capsule: false,
}
```

But I'm not sure if it would the best way to do it.

**Comment by jakewmeyer** [comment]
Agreed, would allow for a more granular understanding of reusability.

**Comment by jakewmeyer** [comment]
Going to collect all the data for #45 and #46 to make one big pass on the data, including this one

**Comment by jakewmeyer** [comment]
After all the additions, this is what the CRS-12 data would look like, as an example.
```json
{
    "flight_number": 45,
    "launch_year": "2017",
    "launch_date_unix": 1502728260,
    "launch_date_utc": "2017-08-14T16:31:00Z",
    "launch_date_local": "2017-08-14T12:31:00-04:00",
    "rocket": {
      "rocket_id": "falcon9",
      "rocket_name": "Falcon 9",
      "rocket_type": "FT"
    },
    "telemetry": {
      "flight_club": "https://www.flightclub.io/results/?code=CR12"
    },
    "core_serial": "B1039",
    "cap_serial": "C113",
    "reuse": {
        "booster": false,
        "sidebooster1": false,
        "sidebooster2": false,
        "fairings": false,
        "capsule": false
    },
    "launch_site": {
      "site_id": "ksc_lc_39a",
      "site_name": "KSC LC 39A"
    },
    "payloads": [
      {
        "payload_id": "SpaceX CRS-12",
        "customers": [
          "NASA (CRS)"
        ],
        "payload_type": "Dragon 1.1",
        "payload_mass_kg": 3310,
        "payload_mass_lbs": 7298,
        "orbit": "ISS",
        "mass_returned_kg": 1724,
        "mass_returned_lbs": 3800,
        "flight_time_sec": 2842920,
        "cargo_manifest": "https://www.nasa.gov/sites/default/files/atoms/files/spacex_crs-12_missionoverview.pdf"

      }
    ],
    "launch_success": true,
    "land_success": true,
    "landing_type": "RTLS",
    "landing_vehicle": "LZ-1",
    "links": {
      "mission_patch": "http://spacexpatchlist.space/images/thumbs/spacex_f9_039_crs_12.png",
      "reddit_campaign": "https://www.reddit.com/r/spacex/comments/6mrga2/crs12_launch_campaign_thread/",
      "reddit_launch": "https://www.reddit.com/r/spacex/comments/6tfcio/welcome_to_the_rspacex_crs12_official_launch/",
      "reddit_recovery": null,
      "reddit_media": "https://www.reddit.com/r/spacex/comments/6th2nf/rspacex_crs12_media_thread_videos_images_gifs/",
      "presskit": "http://www.spacex.com/sites/spacex/files/crs12presskit.pdf",
      "article_link": "https://spaceflightnow.com/2017/08/17/photos-falcon-9-rocket-soars-into-space-lands-back-at-cape-canaveral/",
      "video_link": "https://www.youtube.com/watch?v=vLxWsYx8dbo"
    }
}
```

**Comment by AlbericTrancart** [comment]
Yay! Thank you for the others PR! While you're at it, I received this message: 

> I wanted to point out that the heaviest GTO sat launched by Spacex was the Intelsat 35e at 6761kg, not Inmarsat: https://en.wikipedia.org/wiki/Intelsat_35e

(Intelsat is currently listed as 6000kg)

**Comment by AlbericTrancart** [comment]
@jakewmeyer just to be sure, this will be a breaking change (as now I'm checking the `reuse` boolean parameter). How do we handle such changes? I know there is an API versioning system but for now it may be overkill?
Idea to dash the issue: store the new data in a `reusedParts` parameter and flag the flight as `reused` if at least one part is reused. Not sure if we would want this (it would flag CRS-13 as reused for instance as it was done in the subreddit sidebar), just throwing some ideas :slightly_smiling_face:

**Comment by jakewmeyer** [comment]
I decided to leave in the old reused data in addition to the new reused details. This should prevent it from being a breaking change, while allowing for the detailed reusability data we were after.

**Comment by AlbericTrancart** [comment]
Congrats for the new tag release! I can't think of any info to add, the API is very good :+1: :+1: :+1:
