### ISSUE TITLE
[V4] Ability to 'select' data from Roadster endpoint

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#472]
I'm not able to perform a `POST` action to cherry pick the data I want to receive from the API, just like I can do with the other endpoints.

**Comment by jakewmeyer** [comment]
Since this was a legacy carryover from v3, I didn't add a `/query` style endpoint. 

Would you rather have the typical `/query` endpoint interface with 1 result, or a similar interface without a paginated type response?

**Comment by jesusrp98** [comment]
What I'm looking for is just to select the data I want to display inside the app, using the `select` parameter, like in many other endpoints.

The pagination section of a response doesn't have much sense here, since it's only a single vehicle.

**Comment by jakewmeyer** [comment]
This has been added, see the [doc](https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/roadster/query.md) for more details.

The only option exposed is `select`, so this should work nicely 👍

**Comment by jesusrp98** [comment]
Great, it seems to work fine!
Thanks!
