### ISSUE TITLE
Launches Next don't show Future Lanches

### ISSUE THREAD

**Issue by TalOrlanczyk** [r-spacex/SpaceX-API#473]
https://api.spacexdata.com/v4/launches/next
show only "date_local": "2020-08-31T20:00:00-04:00" for some days now

**Comment by jakewmeyer** [comment]
This is how we show partial dates, see [this](https://github.com/r-spacex/SpaceX-API/tree/master/docs/v4#launch-date-faqs) section of the docs for more details.

The date for this until last night was `2020 Sep`, so the date is only valid to the month level.
