### ISSUE TITLE
Launch 38 has invalid landing ship

### ISSUE THREAD

**Issue by designatednerd** [r-spacex/SpaceX-API#48]
Hi! Awesome work. I would love to fix this except my familiarity with where the hell this would be located in a web app like this is...low. 

The data when I hit `/launches` for launch 38 shows an invalid landing ship - "OSCILY" instead of "OCISLY". Caught this when using this API to build out a sample iOS app. Gotta love strict typing.

If someone can point me to where this can be adjusted I'd be happy to open a PR - if it's just something which needs to be updated at the DB level though, it's wherever the `landing_vehicle` JSON parameter is generated.

**Comment by jakewmeyer** [comment]
Thanks for the correction, it was just a quick fix in the DB, should be live now 👍
