### ISSUE TITLE
[V4] Missing launch failure details

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#483]
The V3 of this API offered more information about a launch failure.
Info like when the failure occured in the mission and the altitude are missing.

Here's a image with missing details.
<img width="515" alt="imagen" src="https://user-images.githubusercontent.com/8961959/93020380-06453d80-f5dd-11ea-9cfe-d408a0d91a17.png">

**Comment by jakewmeyer** [comment]
This should be fixed now. One of the updates to V4 was to allow for multiple failures. The format is identical to V3, it's just an array of failure objects now.

**Comment by jesusrp98** [comment]
Great!
