### ISSUE TITLE
"reuse_count" set to -1 and "status" set to null in /cores endpoint

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#489]
Hi, I found today that https://api.spacexdata.com/v4/cores returns a bit strange values in "reuse_count" field for the three newest boosters, which a bit breaks my parser (because I didn't expect that it can hold negative values):

```json
{"block":5,"reuse_count":-1,"rtls_attempts":0,"rtls_landings":0,"asds_attempts":0,"asds_landings":0,"last_update":null,"launches":[],"serial":"B1061","status":null,"id":"5f57c53d0622a6330279009f"},
{"block":5,"reuse_count":-1,"rtls_attempts":0,"rtls_landings":0,"asds_attempts":0,"asds_landings":0,"last_update":null,"launches":[],"serial":"B1062","status":null,"id":"5f57c5440622a633027900a0"},
{"block":5,"reuse_count":-1,"rtls_attempts":0,"rtls_landings":0,"asds_attempts":0,"asds_landings":0,"last_update":null,"launches":[],"serial":"B1063","status":null,"id":"5f57c54a0622a633027900a1"}
```

Shouldn't it be set to zero or not sent at all (if there is a NULL value there)?

EDIT: there is also a second problem: "status" field is set to null instead of "unknown".

**Comment by jakewmeyer** [comment]
Sorry about that, default for `reuse_count` is zero now. 

Status issue was a broken selector on the cores wiki scraper, fixed now.

**Comment by Tearth** [comment]
No problem, thanx for fix!
