### ISSUE TITLE
Possible to query next launch

### ISSUE THREAD

**Issue by waruss321** [r-spacex/SpaceX-API#494]
Is it possible to populate fields when requesting the next launch?

Tried:

POST: https://api.spacexdata.com/v4/launches/next/query
Body: 
{
  "options": {
    "populate": [
      "rocket"
    ]
  }
}

**Comment by jakewmeyer** [comment]
Not possible currently, but it can be done though the general launches query endpoint like this:

```
POST https://api.spacexdata.com/v4/launches/query
```

Body:

```json
{
  "query": {
    "upcoming": true
  },
  "options": {
    "populate": [
      "rocket"
    ],
    "sort": {
      "flight_number": "asc"
    },
    "limit": 1,
  }
}
```

**Comment by waruss321** [comment]
Perfect! Thanks for the quick reply. 

Always appreicate your great work 🚀

**Comment by jeroenboumans** [comment]
Had the same request, thanks @jakewmeyer!

**Comment by head898** [comment]
https://ropsten.etherscan.io/tx/0x0a33e474cf1e237db0957c474ae270d46a1c34c8394cebb75a3cae96e20c9606
