### ISSUE TITLE
Python bindings?

### ISSUE THREAD

**Issue by scoopgracie** [r-spacex/SpaceX-API#495]
Are there any Python bindings for this? I want to make a Python CLI program for this, but I don't want to write a duplicate library if there is already one.

**Comment by scoopgracie** [comment]
(other than https://github.com/SaidBySolo/SpaceX-Async-Wrapper and the ones that don't use v4)

**Comment by jakewmeyer** [comment]
Other than [SpaceX-Async-Wrapper](https://github.com/SaidBySolo/SpaceX-Async-Wrapper), I'm not aware of any others for v4+

**Comment by scoopgracie** [comment]
Okay. I'll write my own.
