### ISSUE TITLE
Patch URLs not working.

### ISSUE THREAD

**Issue by charlesomer** [r-spacex/SpaceX-API#496]
Hi, it appears the patch URLs are no longer responding. I'm guessing this is some sort of image box change?

**Comment by jakewmeyer** [comment]
Spot checked a few of the links and they appear to work for me. 

Can you link a few that you have issues with?

**Comment by charlesomer** [comment]
Hmm you appear to be right, I'm able to access on my phone. Looks like it's something locally! I should have checked that first, my apologies!
