### ISSUE TITLE
Errors are not consistent

### ISSUE THREAD

**Issue by mwaldstein** [r-spacex/SpaceX-API#50]
Comparing /vehicles to /launchpads, the error messages for invalid id's are not consistent, complicating error handling.

## Observed behavior:
`GET https://api.spacexdata.com/v1/vehicles/bad`
`{
  "error": "No Endpoint Found"
}`
Status code is 404: Not Found

`GET https://api.spacexdata.com/v1/launchpads/bad`
`{
  "error": "No Matches Found"
}`
Status code is 200: OK

## Expectation: 
Both would return the 'No Matches Found' message. I have no opinion on status code, though the most REST-ful would be 404's in both cases.

**Comment by jakewmeyer** [comment]
I agree, both should return a 404, regardless of the message. I'll reduce it to a single agnostic 404 error message, to make it easier to check for, as opposed to multiple. 👍

**Comment by jakewmeyer** [comment]
All errors now return the following `{"error": "No results found"}` with a 404 status code

**Comment by mwaldstein** [comment]
Thanks
