### ISSUE TITLE
Get capsule type in V4?

### ISSUE THREAD

**Issue by scoopgracie** [r-spacex/SpaceX-API#500]
V3 gave the capsule type (Dragon 1.0, Dragon 2, etc.). Is there a way to get this from V4?

**Comment by scoopgracie** [comment]
(Issue #500!)

**Comment by jakewmeyer** [comment]
Somehow this got left out of the V4 upgrade, this has been added now 👍

**Comment by scoopgracie** [comment]
Thanks!
