### ISSUE TITLE
New Site using the API

### ISSUE THREAD

**Issue by TheKicker** [r-spacex/SpaceX-API#501]
This is a **low importance issue** - but figured it would be cool to get it added to the APPS.MD file. 

I'm trying to learn Vue.js and per all of the Youtube & uDemy virtual mentors I've had over the years - **the best way to learn is by doing**.  Hence, this year I started a site I call **Rocket Downrange** which uses this SpaceX API, several from NASA and one that mimicked this exact API but for Rocket Lab.  It recently went offline so I'm going to try and figure out what to do instead.

I am open to criticism, so if I am doing something wrong - don't be afraid to let me know. I took a few courses in college but am pretty much self-taught at this point.  

The URL: Rocketdownrange.com
Github author: @TheKicker
Github URL: github.com/TheKicker/rocket-downrange

Other: Someone else advertised my project on Morioh.com 
Link: morioh.com/p/549620727119

**Comment by jakewmeyer** [comment]
Added in 8fce3a94031aff2f8a54465cecdeba085760e586

Thanks!

**Comment by TheKicker** [comment]
Thank you, Jake :) Appreciate you, friend!
