### ISSUE TITLE
Why is the date and time which I am getting like this?

### ISSUE THREAD

**Issue by samg11** [r-spacex/SpaceX-API#518]
<img width="1439" alt="Screen Shot 2020-10-07 at 10 07 30 AM" src="https://user-images.githubusercontent.com/18032772/95342113-102d2a00-0885-11eb-957d-815c8d3c20e2.png">

**Comment by waruss321** [comment]
The date precision is "month".
https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/README.md#launch-date-field-explanations

**Comment by samg11** [comment]
Why is the date precision so off though

**Comment by warwickofthegh** [comment]
@samg11 because we've lost Elon's direct phone number, if you have it could you please get more accurate dates that is publically known

**Comment by head898** [comment]
https://ropsten.etherscan.io/tx/0x0a33e474cf1e237db0957c474ae270d46a1c34c8394cebb75a3cae96e20c9606
