### ISSUE TITLE
Update all crew

### ISSUE THREAD

**Issue by esper-creative** [r-spacex/SpaceX-API#519]
Currently only get 2 crew members for GET: https://api.spacexdata.com/v4/crew. Can we add the latest crew or the latest crew launch. Launch ID: 5eb87d4dffd86e000604b38e

Crew: 
https://en.wikipedia.org/wiki/Shannon_Walker
https://en.wikipedia.org/wiki/Soichi_Noguchi
https://en.wikipedia.org/wiki/Victor_J._Glover
https://en.wikipedia.org/wiki/Michael_S._Hopkins

Thanks :)

**Comment by jakewmeyer** [comment]
Added and updated 👍

**Comment by head898** [comment]
https://ropsten.etherscan.io/tx/0x0a33e474cf1e237db0957c474ae270d46a1c34c8394cebb75a3cae96e20c9606
