### ISSUE TITLE
PLEASE FIX! When will we get better date precision?

### ISSUE THREAD

**Issue by samg11** [r-spacex/SpaceX-API#523]
<img width="1270" alt="Screen Shot 2020-10-10 at 12 58 12 PM" src="https://user-images.githubusercontent.com/18032772/95660814-7372c280-0af8-11eb-8314-c584c7b10759.png">
<img width="364" alt="Screen Shot 2020-10-10 at 12 59 24 PM" src="https://user-images.githubusercontent.com/18032772/95660816-74a3ef80-0af8-11eb-865e-34c608f6c169.png">

**Comment by jakewmeyer** [comment]
See the [docs FAQ's](https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/README.md#launch-date-faqs) for more details on this.

In your screenshot, `date_utc` is `2020-10-01T00:00:00.000Z`
`date_precision` is `month`

So the date is only valid up to the month level, or `2020-10`

The API tracks the dates on this [wiki](https://old.reddit.com/r/spacex/wiki/launches/manifest) page, and this launch is slated for `2020 Oct`

**Comment by samg11** [comment]
How do I edit the wiki

**Comment by samg11** [comment]
?

**Comment by jakewmeyer** [comment]
Wiki states:

`This wiki is written and maintained entirely by members of this subreddit (those with accounts >180 days old, and >500 subreddit comment or link karma).`

If you don't meet those requirements, I'd message the mods to see if they can do anything.

**Comment by head898** [comment]
https://ropsten.etherscan.io/tx/0x0a33e474cf1e237db0957c474ae270d46a1c34c8394cebb75a3cae96e20c9606
