### ISSUE TITLE
Possible Typo? - GPS III SV05 Flight Number

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#526]
The furthest upcoming launch's (GPS III SV05) flight number reads "124" but is preceded by "113". So I'm wondering if that's possibly a typo.

**Comment by jakewmeyer** [comment]
Technically not a typo

Since I first added that, it's been pushed back a lot, hence the number gaps.

The update script uses the [manifest](https://old.reddit.com/r/spacex/wiki/launches/manifest) order to automatically reorder things, I just haven't filled in the gaps yet.

**Comment by timisenman** [comment]
Gotcha! Just numerical coincidence then. Thanks @jakewmeyer!

**Comment by head898** [comment]
https://ropsten.etherscan.io/tx/0x0a33e474cf1e237db0957c474ae270d46a1c34c8394cebb75a3cae96e20c9606
