### ISSUE TITLE
Incorrect mission numbering?

### ISSUE THREAD

**Issue by fabisiak** [r-spacex/SpaceX-API#530]
Hi,
I'm using your API and I see the mission numbering is different each time. For example, today in this API is Starlink-14, and there is information about Starlink-15 in the SpaceX press release. What is this caused?

**Comment by jakewmeyer** [comment]
While it's technically the 15th launch for Starlink, the first launch was a v0.9 version of the satellites, so r/SpaceX considers it a test flight and doesn't include it with the operational launches.

**Comment by fabisiak** [comment]
Could you changed it?
This is press kit from SpaceX: https://spacex.com.pl/files/2020-10/starlink-15-press-kit.pdf
Also te same information from wikipedia: https://en.wikipedia.org/wiki/Starlink
