### ISSUE TITLE
/starlink - "DECAYED" value always null

### ISSUE THREAD

**Issue by johnunar** [r-spacex/SpaceX-API#542]
The "DECAYED" value is always null, even if the "DECAY_DATE" is in the past. Is this a feature or a bug?

**Comment by jakewmeyer** [comment]
Looks like [Space Track](https://www.space-track.org/) got rid of that field for some reason recently.

I updated the behavior, so now it's set based on the presence of DECAY_DATE.

**Comment by johnunar** [comment]
> Looks like [Space Track](https://www.space-track.org/) got rid of that field for some reason recently.
> 
> I updated the behavior, so now it's set based on the presence of DECAY_DATE.

Cool, that's what I did anyway. Thank you:)
