### ISSUE TITLE
Update CRS-13

### ISSUE THREAD

**Issue by petrosh** [r-spacex/SpaceX-API#56]
Should be
```json
core_serial: "1035.2"
landing_type: "RTLS"
reused: true
...
```

**Comment by jakewmeyer** [comment]
updated

**Comment by petrosh** [comment]
missing `landing_vehicle: "LZ-1"` 😅

**Comment by petrosh** [comment]
Is there any other way we can help on these updates? Hopefully there will be a lot of data entry soon... 🏭

**Comment by jhpratt** [comment]
@petrosh As far as has been discussed on the Slack, not yet — issues are the best way. In the long-term we'd like to create a web interface that would allow certain people to update the database quicker. That could certainly be expanded to allow "suggested changes" from other people, with a simple yes/no approval from an authorized user.

No idea on a time frame for the web interface — no one has started work on it yet. If everything with Mission Control goes well, I could probably do some work on it in about a month.

**Comment by jakewmeyer** [comment]
@petrosh This is probably the most logical step forward as far as autonomy and data accuracy goes.
