### ISSUE TITLE
Outage: Getting a 400 from API on launch endpoints!

### ISSUE THREAD

**Issue by esper-creative** [r-spacex/SpaceX-API#561]
body: 

getaddrinfo ENOTFOUND mongo

**Comment by Avivhdr** [comment]
Same here!

Appreciate the help.

**Comment by KatarinaLauren** [comment]
Same here on launches!

**Comment by Haanhan** [comment]
v4 Endpoints been down for quite a few hours already. 
Appreciate the help on restoring them!

**Comment by jakewmeyer** [comment]
Should be resolved now, the VM ran out of storage space at the worst possible time.

Apologies everyone!

**Comment by Haanhan** [comment]
Thank you! Really appreciate it.
