### ISSUE TITLE
Starlink 15 core reuse count is out by 1. Is this the same everywhere else too?

### ISSUE THREAD

**Issue by esper-creative** [r-spacex/SpaceX-API#567]
On starlink-15 the reuse count for the core is out by.

It should say 6 but says 5. It says this launch is it's 7th flight

![Screenshot 2020-11-22 at 21 04 01](https://user-images.githubusercontent.com/71106889/99917166-7cb19a80-2d06-11eb-8a87-9dd94163c825.png)

LaunchId: 5fb95b3f3a88ae63c954603c

Am I missing something here?

**Comment by jakewmeyer** [comment]
The core data represents the current state of the core, so it'll automatically update to 6 after Starlink 15 launches

**Comment by esper-creative** [comment]
But if this is the 7th flight of the core shouldn’t the reuse count be 6?

**Comment by MattoDeg** [comment]
I think `reuse_count `represent the number of flight after the first one, in which obviously the core was brand new. Therefore, `reuse_count=flight-1`
