### ISSUE TITLE
All launchpads returning for single request on V4

### ISSUE THREAD

**Issue by mjm1374** [r-spacex/SpaceX-API#568]
I am requesting a single launch pad but always get all launch pads. Call is a get @ https://api.spacexdata.com/v4/launchpads?id=5e9e4502f509092b78566f87 but always get back 6 results
<img width="1404" alt="Screen Shot 2020-11-22 at 7 25 12 PM" src="https://user-images.githubusercontent.com/6233168/99921465-86340600-2cf8-11eb-9a96-f36aec4d1169.png">

**Comment by jakewmeyer** [comment]
Your url is just a little off, should be [https://api.spacexdata.com/v4/launchpads/5e9e4502f509092b78566f87](https://api.spacexdata.com/v4/launchpads/5e9e4502f509092b78566f87)

**Comment by mjm1374** [comment]
thank you, the documentation seems to say otherwise, but that might just be me. sure looks like the URL params need id=xxxx
