### ISSUE TITLE
Empty info about launches on upcoming launches endpoint

### ISSUE THREAD

**Issue by podolskiew** [r-spacex/SpaceX-API#569]
https://api.spacexdata.com/v4/launches/upcoming

I cannot get information about launches as described in the documentation https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/launches/upcoming.md

Please, could you check this, because I got empty info by upcoming launches. (No details, no links, etc.).

**Comment by MattoDeg** [comment]
It works well, I track no issues now.

**Comment by podolskiew** [comment]
I got it, but maybe you got a chance to add some info about upcoming launch such as patch pic? 
For example upcoming mission CRS-21 on Wikipedia this info are present https://en.wikipedia.org/wiki/SpaceX_CRS-21, but via API I can't get this pic

Would be great to get patch pics of upcoming launches

Thanks!

**Comment by jakewmeyer** [comment]
Patch added for CRS-21
