### ISSUE TITLE
Launches by serial# should support filters

### ISSUE THREAD

**Issue by mwaldstein** [r-spacex/SpaceX-API#57]
If you query by core or capsule, currently any further launch query parameters are ignored, e.g. year, start, final, site.

I'd expect something like https://api.spacexdata.com/v1/launches/caps/C106?year=2017 to only return the launch from 2017.

**Comment by jakewmeyer** [comment]
Absolutely 👍  Added to the upcoming feature list, should be live in the next week or so

**Comment by jakewmeyer** [comment]
@mwaldstein Changes should be live now, I ran a few tests through it, let me know if you find any issues 👍
