### ISSUE TITLE
Starlink 16 date error

### ISSUE THREAD

**Issue by MattoDeg** [r-spacex/SpaceX-API#573]
Starlink 16 often changes date. Now is set at 01-01-2020, should be at least 2021 (even if it could be launched on december).

**Comment by jakewmeyer** [comment]
Looks like someone made a typo in the [manifest wiki page](https://old.reddit.com/r/spacex/wiki/launches/manifest) and put 2020 instead of 2021

Manually fixing this for the time being

**Comment by MattoDeg** [comment]
No problem, thank you. It happened two times during this week.
