### ISSUE TITLE
NROL-108 update launch_date

### ISSUE THREAD

**Issue by MattoDeg** [r-spacex/SpaceX-API#581]
NROL-108 is set to 2020-12-01, but at least should be 2020-12-31.

**Comment by jakewmeyer** [comment]
[Manifest](https://old.reddit.com/r/spacex/wiki/launches/manifest) has this as `2020 Dec`, no way to represent past a date currently.

**Comment by MattoDeg** [comment]
Mh ok:( So the only option is to update the manifest, right?

**Comment by jakewmeyer** [comment]
Correct, looks like it got fixed thankfully 👍

**Comment by MattoDeg** [comment]
MS. Tree is already at fairing's landing zone.

https://twitter.com/SpaceXFleet/status/1339579955185741825?s=20

**Comment by MattoDeg** [comment]
Also, there's a window going from 2020-12-19 14:00:00 Z to 2020-12-19 17:00:00, or in second 10800.

**Comment by MattoDeg** [comment]
Both fairing halves are brand new and will be retrieved from water by [Ms Tree ](https://github.com/r-spacex/SpaceX-API/issues/581#issuecomment-748434891) and GO Searcher.
