### ISSUE TITLE
SXM-7 update launch info

### ISSUE THREAD

**Issue by MattoDeg** [r-spacex/SpaceX-API#582]
SXM-7 core is B1051 and this will be its seven flight.

**Comment by jakewmeyer** [comment]
Updated

**Comment by MattoDeg** [comment]
Per Gunter's Space page, mass of SXM-7 should be ~7000 kg (and it will be the same as SXM-8).

**Comment by MattoDeg** [comment]
JRTI has departed towed by Finn Falgout. Downrange will be 644 km.

**Comment by jakewmeyer** [comment]
Updated

**Comment by MattoDeg** [comment]
Static fire occured at 2020-12-07 23:00:00 UTC.

https://twitter.com/SpaceflightNow/status/1336084833131503616?s=20

Go Searcher has departed yesterday in order to catch fairing.

**Comment by MattoDeg** [comment]
Also, one half of fairing is reused from ANASIS-II launch. Maybe it should be useful to add a fairing endpoint like the rocket one, in order to better track which has flown more times and in which launch. SpaceXfleet.com could be an useful website to take data from.

**Comment by MattoDeg** [comment]
There's an error in static_fire_date_utc: timezone is Zulu while for that time (18:00) should be EST. In UTC is 2020-12-07 23:00:00 Z.

**Comment by jakewmeyer** [comment]
1. static fire issue is fixed

2. Agree that fairing tracking should exist, we'll have to come up with our own tracking and serial numbers, haven't seen anyone tracking that yet. Go ahead and create a new issue for this one specifically. 

3. I'll look into using SpaceXfleet.com, as the ship data isn't automated at all. Reliably parsing it will be the biggest issue, especially if the format changes often.

**Comment by MattoDeg** [comment]
How do you manage fairing_reused field if only one half is reused?

**Comment by MattoDeg** [comment]
SXM-7 has a launch window from 2020-12-11 16:21:00Z to 2020-12-11 17:20:00Z, so 1 hour and 59 minutes or 7140 seconds.

**Comment by MattoDeg** [comment]
Launch scrubbed, waiting a new T-0.

**Comment by jakewmeyer** [comment]
The current fairing implementation didn't account for the possibility of individual halves being reused/caught/recovered, so the new implementation will cover this.
