### ISSUE TITLE
CRS-21 update

### ISSUE THREAD

**Issue by MattoDeg** [r-spacex/SpaceX-API#583]
OCISLY departed yesterday (2020-12-01) towed by Tug Hawk.

**Comment by jakewmeyer** [comment]
Updated

**Comment by MattoDeg** [comment]
As always, thank you.

**Comment by MattoDeg** [comment]
I think that UTC it's uncorrect. It should be around 13.45 UTC not 8.19 UTC.

**Comment by MattoDeg** [comment]
Launch has been scrubbed. Now it's set to 2020-12-06 16:17 UTC.

**Comment by jakewmeyer** [comment]
Updated
