### ISSUE TITLE
Turksat 5A update info

### ISSUE THREAD

**Issue by MattoDeg** [r-spacex/SpaceX-API#589]
I think that's the same as it was for [NROL-108](https://github.com/r-spacex/SpaceX-API/issues/581), but Turksat is set to 2020-12-01. Maybe you can manually fix this to at least 2021-01-01 or update the manifest (which I can't because i don't have a reddit account and even though I would not have enough karma.)

**Comment by jakewmeyer** [comment]
Manifest has this one as `2020 Dec Late`, so it should be accurate

**Comment by MattoDeg** [comment]
Yes but API set this to 2020-12-01:( My script won't run if date_utc<now. IDK how scraping/adding info works, but if manifest set to 2020 Dec late, API should return 2020-12-31

**Comment by jakewmeyer** [comment]
My usual recommendation for this is to only read the date up to the level set by `date_precision `, which in this case is set to `month`

Is it possible for you run the script as long as the current date falls within the date up to the precision level?

For example, with the precision as `month`, the script would run as long as now falls within the month of December.

**Comment by MattoDeg** [comment]
Yeah maybe I can do this.

Talking about date precision, is it possible to "increase" it by adding `minute` to the options? Becuase many launches with time precise down sometimes to seconds are set to `hour`. Let me know if it is possible

**Comment by jakewmeyer** [comment]
Possible, but unlikely because it would be a major breaking change to everyone using the api. Hour has been the lowest level since the beginning, so introducing a lower level could break a lot of stuff. Considering how bumpy the v3 to v4 transition was, I'd rather not make a big breaking change like that currently.

**Comment by MattoDeg** [comment]
I did not follow the transition between V3 and V4 because it's 2 or 3 weeks I'm using your API. Don't worry about the precision, I thought that could be an useful implementation. Thank you for all your updates!

**Comment by MattoDeg** [comment]
Booster will be B1060 and it will be its 4th flight. Also, launch is set to 2020-12-31 01:00:00Z.
