### ISSUE TITLE
Update JRTI name and CCAFS name

### ISSUE THREAD

**Issue by MattoDeg** [r-spacex/SpaceX-API#596]
One thing I forgot to mention in #591 is that JRTI has a "2" at the end of its name. 

Also, VP Mike Pence has renamend CCAFS into CCSFS (_Cape Canaveral Space Force Station_) as well as Patrick Air Force Base is now Patrick Space Force Base.

**Comment by jakewmeyer** [comment]
The JRTI issue is because of the legacy id, going to add a new field for the current abbreviations called `name_abbr`.

CCAFS updated 👍
