### ISSUE TITLE
long_name field for launch site object

### ISSUE THREAD

**Issue by richiksc** [r-spacex/SpaceX-API#60]
For each launch site object, in addition to having an id and a name, it would be great to have a "long name".

- `ksc_lc_39a`:
    - name: `"KSC LC 39A"
    - long_name: `"Kennedy Space Center Historic Launch Complex 39A"
- `ccafs_slc_40`:
    - name: `"CCAFS SLC 40"
    - long_name: `"Cape Canaveral Air Force Station Space Launch Complex 40"
- `vafb_slc_4e`:
    - name: `"VAFB SLC 4E"
    - long_name: `"Vandenberg Air Force Base Space Launch Complex 4E"

**Comment by jakewmeyer** [comment]
Sounds good 👍  added to the list

**Comment by jakewmeyer** [comment]
Long names should be live!

**Comment by TheTrain2000** [comment]
@jakewmeyer The API returns this data as `full_name` rather than `long_name`, however the release notes for v2.1.0 states that it is implemented as `long_name`.

**Comment by jakewmeyer** [comment]
@TheTrain2000 correct name was `site_name_long` added to all launches, I'll update the release to reflect that 👍 

I'll correct the launchpad data to match the new long names as well

**Comment by TheTrain2000** [comment]
Coolio, thanks for all the work you do on this project.
