### ISSUE TITLE
Roadster Data Not Updating (v4)

### ISSUE THREAD

**Issue by djtimca** [r-spacex/SpaceX-API#605]
I have noticed that the Roadster data doesn't seem to be updating on V4. 

When I compare the outputs of the V3 and V4 API endpoint they differ significantly and the updates seem to be much less frequent on V4. Is there something wrong with the data feed for V4?

Accessing via GET at: https://api.spacexdata.com/v4/roadster

**Comment by jakewmeyer** [comment]
Fixed a slight bug in the V4 updater, both appear to be in sync currently.
