### ISSUE TITLE
Querystrings don't work in V4 ?

### ISSUE THREAD

**Issue by vintaerj** [r-spacex/SpaceX-API#607]
Hello,

I don't know if it is the normal behaviour, but all query strings in every endpoints don't work in V4. 
Is it normal or I misuses the Api ?

Thanks

**Comment by jakewmeyer** [comment]
The querystrings used previously for v3 will not work with v4. The new v4 approach is to pass the params in the body of a POST request through the `/query` endpoints for each subject.

See the [V4 docs](https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/README.md) for more details
