### ISSUE TITLE
Japanese crew member

### ISSUE THREAD

**Issue by MattoDeg** [r-spacex/SpaceX-API#616]
I noticed that Soichi Noguchi has as agency NASA/NASDA/JAXA and Akihiko Hoshide has NASDA/JAXA. Shouldn't they both be only JAXA?

**Comment by jakewmeyer** [comment]
Not 100% sure on this one, but I'm fine with updating to JAXA only

**Comment by MattoDeg** [comment]
Oh ok now I figured it out better. Until 2003 JAXA didn't exist: instead there were NASDA and two other institutes that they were merged together to create JAXA. Noguchi initially was selected for NASDA and then passed to JAXA when it was created. Same for Hoshide.

**Comment by jakewmeyer** [comment]
Think it's worth mentioning the old ones?

**Comment by MattoDeg** [comment]
Let me think.

Maybe only for the astronauts that were selected under NASDA and then passed to JAXA. But they are flying on SpaceX mission in 2020 or later, and exists only JAXA, so they are no more NASDA.

So, no, it's not worth.
