### ISSUE TITLE
DART update info

### ISSUE THREAD

**Issue by MattoDeg** [r-spacex/SpaceX-API#618]
Booster, per [Spaceflightnow](https://twitter.com/SpaceflightNow/status/1330544871661334533?s=20), booster will be B1063, the one that has served Sentinel-6 mission. It will be (probably) its second flight. Orbit should be an heliocentric one and manufacturer should be APL, the Applied Physics Laboratory at Johns Hopkins University. It will be launched from Vandenberg Air Force Base.

Please don't close this issue until launch has occured, so it will be possible to comment and have everything here.

**Comment by jakewmeyer** [comment]
Updated
