### ISSUE TITLE
Turksat 5A update info

### ISSUE THREAD

**Issue by MattoDeg** [r-spacex/SpaceX-API#619]
This launch should have a launch window of 4 hours and 2 minutes (14520 seconds).

Please don't close this issue until launch has occured, so it will be possible to comment and have everything here.

**Comment by jakewmeyer** [comment]
Updated

**Comment by MattoDeg** [comment]
Thank you.

**Comment by MattoDeg** [comment]
Seems that ASDS will be JRTI and it is expected to depart today or tomorrow (EDT time).

**Comment by MattoDeg** [comment]
JRTI has departed, towed by Finn Falgout.

**Comment by MattoDeg** [comment]
Finn Falgout had a problem and has been replaced by Tug Hawk.

**Comment by jakewmeyer** [comment]
Updated

**Comment by MattoDeg** [comment]
JRTI has already departed. Previously reentered due to the delay of mission due to mission assurance reasons.

**Comment by MattoDeg** [comment]
Per the [hazardous area](https://twitter.com/Raul74Cz/status/1346131292119838732?s=20), launch is set to to 2021-01-07 01:23Z to 2021-01-07 06:20Z. Therefore, window is 4 hours, 57 minutes and 0 seconds or 17.820 seconds.

**Comment by MattoDeg** [comment]
Launch is now set to 2021-01-08 01:23Z to 2021-01-08 06:20Z. Same window of 17820 seconds. Backup date on 2021-01-09 at the same hour.

**Comment by jakewmeyer** [comment]
Updated

**Comment by MattoDeg** [comment]
Ms. Tree and Ms. Chief both departed to fairing landing zone.

**Comment by jakewmeyer** [comment]
Updated

**Comment by MattoDeg** [comment]
Both fairing halves are reused. One on GPS SV III 03 and the other on ANASIS-II.

**Comment by spacexdash** [comment]
Not sure where you normally get mission patches from but this source updated the other day [here](https://www.elonx.net/spacex-mission-patches/).
