### ISSUE TITLE
Wiki from Past Launches and eventually the other still outdated

### ISSUE THREAD

**Issue by rickspm** [r-spacex/SpaceX-API#62]
The example snippets of the Wiki section still outdated. Even though it says v2 already but the code snippet still displaying the outdated "rocket" object.

**Comment by jakewmeyer** [comment]
Which wiki page is showing outdated data?

**Comment by rickspm** [comment]
Past Launches the last snippet.

**Comment by jakewmeyer** [comment]
Sample response looks correct to me? Screenshot maybe?

**Comment by rickspm** [comment]
I am sorry. I was still using the v1 version and I thought I had it updated. On v1 the rocket object is a single object. It's everything good.
