### ISSUE TITLE
New app using this Api

### ISSUE THREAD

**Issue by alexmaryin** [r-spacex/SpaceX-API#625]
Hi!
Please add my contributing app for android to list of known Apps / UI clients
My repository is [SpaceX Times](https://github.com/alexmaryin/spacextimes)
My name is Alex maryin, Russia, Ulyanovsk

Kind regards!

**Comment by jakewmeyer** [comment]
Best way to get it added is a pull request from you 👍 

Thanks!

**Comment by alexmaryin** [comment]
@jakewmeyer Ok, thank you)
