### ISSUE TITLE
Starlink 16, 17 TBD flag should be true

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#628]
They're currently slated for tomorrow, but I believe the dates haven't been officially set, and both of their models currently say  `tbd: true`.  I believe both should be `false`

**Comment by jakewmeyer** [comment]
Issue #490 should apply to this and #629 as well

**Comment by timisenman** [comment]
Closing, thank you @jakewmeyer

**Comment by timisenman** [comment]
Sorry, re-opening this until it's in the DB.

**Comment by timisenman** [comment]
No longer relevant
