### ISSUE TITLE
CRS-13 launch date

### ISSUE THREAD

**Issue by petrosh** [r-spacex/SpaceX-API#63]
Scheduled for `2017-12-08T13:20:00-04:00`.

How do you deal with standard time? Right now EST = UTC-5

**Comment by jakewmeyer** [comment]
Updated

**Comment by jakewmeyer** [comment]
Currently local time should be adjusted for daylight savings, but not for UTC and Unix time

**Comment by petrosh** [comment]
Ok thanks, so `launch_date_local` is always given in DST, not standard time (EDT not EST, PDT not PST, ...).
Out of curiosity do you use a snippet for the other launch times? like
```js
new Date('2017-12-08T13:20:00-05:00').toISOString().split('.')[0]+"Z" // "2017-12-08T18:20:00Z"
new Date('2017-12-08T13:20:00-05:00').getTime() / 1000 // 1512757200
```

**Comment by jakewmeyer** [comment]
I should start using a script like that to calculate it  🤷‍♂️
