### ISSUE TITLE
Upcoming Launch

### ISSUE THREAD

**Issue by ChopsKingsland** [r-spacex/SpaceX-API#633]
I'm using the [next launch url](https://api.spacexdata.com/v4/launches/next), and it is just showing a launch for 01-01-2021... How can this be fixed?

**Comment by jakewmeyer** [comment]
See this bit in the [docs](https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/README.md#launch-date-faqs) for more details.

In this case, the launch was slated for `2021 Jan`, so the date is only valid up to `2021-01`
