### ISSUE TITLE
Regex Support

### ISSUE THREAD

**Issue by spacexdash** [r-spacex/SpaceX-API#637]
Hi -

Not sure if i am doing something wrong, but i am trying to run basic regex against the http API but i am not getting results where i would expect to. I have a few examples of what i have tried below. All queries return 0 results Would you be able to take a look?

```
POST https://api.spacexdata.com/v4/cores/query
{"query":{"serial":{"$regex":"/B10/"},"options":{}}}

POST https://api.spacexdata.com/v4/cores/query
{"query":{"serial":{"$regex":"B10"},"options":{}}}

POST https://api.spacexdata.com/v4/cores/query
{"query":{"serial":"/B10/"},"options":{}}}
```

Ideally, i'd just like to use $search but i get text index errors. I imagine, you may need to do some parsing to look for $regex entries and convert them to new RegexExp() - but i haven't had a chance to look at the code.

This would be useful across all services to allow for better apps to be built.

Thanks for the awesome API you and the community have built here!

**Comment by jakewmeyer** [comment]
Pretty close, this got me for a bit too. The following should work as expected.

```json
{
  "query": {
    "serial": {
      "$regex": "B10"
    }
  }
}
```

Doesn't need the `//` surrounding it, since it's not a regex literal

**Comment by spacexdash** [comment]
Ah you're right - thank you. Same as my second example. I put this down to me probably searching "b10". Apologies.
