### ISSUE TITLE
List of known Apps / UI clients addition

### ISSUE THREAD

**Issue by tipenehughes** [r-spacex/SpaceX-API#647]
Hi,

First off thanks so much to you all for building this API. Such an amazing and in depth resource!

I built a web app using this API and wanted to let you know so it can be added to the list of known apps.

Live site: [https://spacex-project.netlify.app/](https://spacex-project.netlify.app/)
Github: [https://github.com/tipenehughes/space-x-app)](https://github.com/tipenehughes/space-x-app)

If you have any questions or concerns, feel free to reach out.

Thanks!

**Comment by jakewmeyer** [comment]
Best way is to open a PR with the addition [here](https://github.com/r-spacex/SpaceX-API/blob/master/docs/apps.md), thanks!
