### ISSUE TITLE
Incorrect patches on some launches

### ISSUE THREAD

**Issue by quadrplax** [r-spacex/SpaceX-API#648]
A few launches are using the patch made by the customer (e.g. NASA) instead of SpaceX. All SpaceX patches are listed in high resolution here for reference: https://www.elonx.net/spacex-mission-patches/

Patches that are incorrect:
- Crew 1
- GPS III SV03 (correct patch but physical stitching instead of flat graphic)
- CRS 21
- AMOS 6

**Comment by jakewmeyer** [comment]
All updated 👍 

Thanks for the tip about that site, been looking for a good resource, thanks!

**Comment by quadrplax** [comment]
Works great! Yeah, the way I found that page was by searching on Google Images for the GPS III SV03 patch, which I couldn't find anywhere else in graphic form. Also I had no idea the AMOS-6 patch was released before.
