### ISSUE TITLE
Coordinates on upcoming launches

### ISSUE THREAD

**Issue by ChopsKingsland** [r-spacex/SpaceX-API#654]
Is there a possibility that the launchpad coordinates can be added to the upcoming launches, so 2 API pages don't have to be requested?

**Comment by jakewmeyer** [comment]
The following route + body should work for this

```
POST https://api.spacexdata.com/v4/launches/query
```` 

```json
{
    "options": {
        "populate": {
            "path": "launchpad",
            "select": ["latitude", "longitude"]
        }
    }
}
```

**Comment by ChopsKingsland** [comment]
I am only using get requests, so is there a way to get it via a GET request?

**Comment by jakewmeyer** [comment]
Not currently, but it's something that could be added
