### ISSUE TITLE
V4 https://api.spacexdata.com/v4/launches/1 details is not working!

### ISSUE THREAD

**Issue by jams032** [r-spacex/SpaceX-API#658]
Hi, i was testing the api. Version 3 works fine. Version 4 also working fine. But i have found a scenario in version 4. 

https://api.spacexdata.com/v4/launches these works but the details 

https://api.spacexdata.com/v4/launches/1 

parameter with (rocket number) is not working. 

Could you please check ?

**Comment by PatrykWojcieszak** [comment]
I assume you're passed flight number but you need to pass the id of the launch for example: 5eb87cd9ffd86e000604b32a.

**Comment by jams032** [comment]
@PatrykWojcieszak oh.. 

Previous version 3 used this , right https://api.spacexdata.com/v3/launches/{flightNumber}` 

Now you expect rocket id, right ?

**Comment by PatrykWojcieszak** [comment]
@jams032 you need to use id of the launch you want to get data of. The URL looks like this:
URL : https://api.spacexdata.com/v4/launches/:id
URL Parameters : id=[string] where id is the ID of the launch

Check docs for getting single launch: [Single launch](https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/launches/one.md) 
or to query launches: [Query launches](https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/launches/query.md)

**Comment by jams032** [comment]
https://api.spacexdata.com/v4/launches/5e9d0d95eda69973a809d1ec

Do you mean this to access for single launch? I can't access this.

But i can access this : https://api.spacexdata.com/v4/rockets/5e9d0d95eda69973a809d1ec 

Please, correct me if am doing any wrong.

**Comment by PatrykWojcieszak** [comment]
@jams032 If you want to get data of specific launch you need to use this URL https://api.spacexdata.com/v4/launches/:id.
But you need to use launch id not rocket id.
