### ISSUE TITLE
Typo in WIKI

### ISSUE THREAD

**Issue by binarygary** [r-spacex/SpaceX-API#66]
On https://github.com/r-spacex/SpaceX-API/wiki/Upcoming-Launches the word combination is misspelled.

`All upcoming launches can be filtered though any **conbination** of the following querystrings`

I looked to see if there was a way to edit the wiki to fix it, but it doesn't appear it's publically editable.

**Comment by jakewmeyer** [comment]
Typo should be corrected now, Also updated the wiki permissions to allow for public edits. Thanks! 👍

**Comment by binarygary** [comment]
Thanks!
Love the API, nice work.
