### ISSUE TITLE
V3 API is throwing 500 Internal Server Error

### ISSUE THREAD

**Issue by ghousemohamed** [r-spacex/SpaceX-API#660]
When I do a GET request for https://api.spacexdata.com/v3/launches, I'm getting `{"error": "internal server error"}`

This is happening for all routes in V3 I believe.

**Comment by dpletzke** [comment]
oddly enough [missions seems to be working](https://api.spacexdata.com/v3/missions), but yea same issue here

**Comment by jakewmeyer** [comment]
Seems to be related to the small outage we had yesterday, and V3 didn't recovery correctly. Should be fixed now.

As a side note, V3 is deprecated at this point, and no longer receives data updates. For the latest updates you should migrate to V4.

**Comment by ghousemohamed** [comment]
@jakewmeyer Seems like V3 is down again
