### ISSUE TITLE
Get to know if a static fire has been performed

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#667]
For a couple months now, SpaceX has decided to skip static fires on a couple missions now, mainly Starlink ones.
Would it be nice to know inside a launch if the static fire has been performed or not?

I'd like to know if this information could be extracted from the static fire field already, check if `upcoming == false` and `static_fire_date` is `null`.

**Comment by jakewmeyer** [comment]
As it exists, if the static fire fields are null, no static fire took place.

**Comment by jesusrp98** [comment]
OK that makes sense, thanks for the reply!
