### ISSUE TITLE
API rate limit reached

### ISSUE THREAD

**Issue by cyonder** [r-spacex/SpaceX-API#67]
I am having a problem with the API. I haven't reached the request level. Although I see "API rate limit reached" message. Waited a night, I still have the same problem.

**Comment by jakewmeyer** [comment]
Taking a look

**Comment by cyonder** [comment]
I am not sure if it's caching. I don't know how to check that. Although, I cleared cashes, cookies and still have the same error. Tried other computers and it's still the same.

**Comment by jakewmeyer** [comment]
Interesting. I went ahead and removed the rate limit for the time being. Been looking for a more robust solution anyways, this one wasn't cutting it.

So this should solve the current problem, and I'll look into a better solution going forward 👍

**Comment by cyonder** [comment]
Okay, thank you for your help and the API 👍

**Comment by jhpratt** [comment]
@jakewmeyer Was anyone actually hitting the rate limit before? Assuming you kept track of that.

**Comment by jakewmeyer** [comment]
@jhpratt Wasn't keeping track of it previously, but just from peeking at the traffic logs every so often, it's not even close to hitting that limit. 

Originally put in place just in case someone wanted to spam the hell out of it for some reason.
