### ISSUE TITLE
Updating `success_rate_pct` on rockets and docs issue

### ISSUE THREAD

**Issue by trasparente** [r-spacex/SpaceX-API#671]
Could `launches.js` job, update `success_rate_pct` on rockets table too?

(Unrelated) [`v4/landpads/update.md`](https://github.com/r-spacex/SpaceX-API/blob/master/docs/v4/landpads/update.md) still refer to cores...

Thanks :+1:

**Comment by jakewmeyer** [comment]
It definitely should, I'll add it to the queue 👍

**Comment by jakewmeyer** [comment]
@trasparente Added this, so it'll update automatically going forward 👍
