### ISSUE TITLE
Retrieve specific launch using id via query path?

### ISSUE THREAD

**Issue by stanifert** [r-spacex/SpaceX-API#673]
I'm a novice with mongoDB querying, but is it possible to retrieve a single launch with a given id via the POST query path?

Something like:

```
{
      "query": {
          "id": "5eb87d4dffd86e000604b38e"
      },
      "options": {...}
}
```

or 

```
{
     "query": {
         "$text": {
             "$search":  "5eb87d4dffd86e000604b38e"
         }
     },
     "options": {...}
}
```

or
```
{
     "query": {
         "$text": {
             "$eq": "5eb87d4dffd86e000604b38e"
         }
     },
     "options": {...}
}
```
The use case is wanting to populate all objects for a given launch ( i.e. rocket, cores, capsules, payloads, crew, etc). via the populate parameters. Thanks!

**Comment by stanifert** [comment]
I suppose I could accomplish this by just searching for the name of the launch, but that feels less safe than using the id.

**Comment by jakewmeyer** [comment]
Looks like a slight bug potentially. The underlying mongo document uses the field `_id` instead of `id`. The mongo library we use converts this field to `id` when fetching a launch but doesn't seem to for queries. I'll take a closer look.

For the time being, this works as expected:
```json
{
  "query": {
    "_id": "5eb87d4dffd86e000604b38e"
  }
}
```

**Comment by stanifert** [comment]
Awesome! Thanks @jakewmeyer!
