### ISSUE TITLE
Endpoints returning wrong data

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#68]
Hi Jake,

I've noticed a couple of changes in the returndata of the api endpoints:

- **GET** https://api.spacexdata.com/v2/rockets/[rocketId] now returns an array of length 0 instead of the direct object.
- **GET** https://api.spacexdata.com/v2/capsules/[capsuleId] returns an empty object.

**Comment by jakewmeyer** [comment]
Should be resolved now, capsule was missing an `await` statement, and I made an error when refactoring the rocket endpoints.

[https://api.spacexdata.com/v2/rockets/falcon9](https://api.spacexdata.com/v2/rockets/falcon9)

[https://api.spacexdata.com/v2/capsules/dragon2](https://api.spacexdata.com/v2/capsules/dragon2)
