### ISSUE TITLE
API Down?

### ISSUE THREAD

**Issue by MattoDeg** [r-spacex/SpaceX-API#687]
I'm trying to test the new fairing route using stage.spacexdata.com but it's not working. @jakewmeyer did you disable it or is it a temporary down?

**Comment by MattoDeg** [comment]
Ok nevermind resolved. Eveything works, maybe it was a temporary down.

**Comment by MattoDeg** [comment]
Still down:(

**Comment by jakewmeyer** [comment]
Apologies for the outages, had some issues with the server, should be fixed now

**Comment by MattoDeg** [comment]
Thanks, checked some minutes ago and worked!
