### ISSUE TITLE
Request for object relation

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#69]
Hi @jakewmeyer, was just wondering, would it be possible to query capsule parts and core parts via capsule id as well? That'd be very useful for connecting all together!

So instead of querying the api with this:
`https://api.spacexdata.com/v2/parts/caps?type=Dragon 1.1`

We could query like this, returning an array of caps or cores for this main type:
`https://api.spacexdata.com/v2/parts/caps/dragon1`
`https://api.spacexdata.com/v2/parts/cores/dragon1`

Or, instead of the above, send a small array of subtypes in the response object:
`https://api.spacexdata.com/v2/capsules/dragon1` returns:
```
{
    "id": "dragon1",
    "caps": ["Dragon 1.0", "Dragon 1.1", ...],
    "cores": ["B0004", "B0005", ...],
    ...
}
```

I'd appreciate the effort!

**Comment by jakewmeyer** [comment]
First option should be no problem, Don't really know how to aggregate the data to form the second example.

**Comment by jeroenboumans** [comment]
Perhaps a search param, like the following could to the trick:
`https://api.spacexdata.com/v2/parts/caps?capsule=dragon1`
`https://api.spacexdata.com/v2/parts/cores?capsule=dragon1`

I've checked the database and I think it can be done by adding `capsule_id` to the capsule objects and core-objects. A `...parts/caps?capsule=dragon1` query can then select all capsules/cores containing this `capsule_id`. This seems like a one-to-many relationship. Correct me if I'm wrong :)

**Comment by jakewmeyer** [comment]
I think I understand now, makes sense to add it to caps. What about cores though?

**Comment by jeroenboumans** [comment]
Whoops, I wasn't aware about the cores entity and what it meant in the context of the rocket. I know now that it's all about the 1st stage? Since these aren't necessarily linked to a specific type of rocket but more to a build, the cores endpoint I specified above can be ignored. Sorry ;-)

**Comment by jakewmeyer** [comment]
Changes are live, I'll update the wiki shortly

[https://api.spacexdata.com/v2/parts/caps?capsule_id=dragon1](https://api.spacexdata.com/v2/parts/caps?capsule_id=dragon1)

[https://api.spacexdata.com/v2/parts/caps?capsule_id=dragon2](https://api.spacexdata.com/v2/parts/caps?capsule_id=dragon2)

**Comment by jeroenboumans** [comment]
Thanks Jake!
