### ISSUE TITLE
Starship High altitude flight tests

### ISSUE THREAD

**Issue by RoyalCrown** [r-spacex/SpaceX-API#696]
Hi, awesome API !!! Is any option how add Starship SN HOP tests to Launches category or adding new category as Events. Only my idea, thank you very much for your really hard work, love this API...

**Comment by ChopsKingsland** [comment]
Same here, I wish I could add a parameter to the 'upcoming launches' URL to also have it list SN tests/hops as well as normal SpaceX rocket launches

**Comment by jakewmeyer** [comment]
Not currently, but [Launch Library v2](https://thespacedevs.com/) does track these

For example, https://ll.thespacedevs.com/2.2.0/launch/73ae8553-cc90-46e9-9a01-70a712493856/?format=json
