### ISSUE TITLE
Launches not updating (Upcoming is still Starlink 20)

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#706]
Hey folks, 

It appears the DB isn't updating after yesterday's launch. I think this is the second time the upcoming launches haven't updated immediately after a launch. Did something change in the update schedule, or does this have to do with the new version? 

Let me know if there's anything we need to do on our ends to get the latest that we're not aware of.

Thanks!
Tim

**Comment by timisenman** [comment]
Seems fixed now

**Comment by jakewmeyer** [comment]
Nothing on your end, just missed the upcoming field as I updated data for the launch last night. 🙃
