### ISSUE TITLE
What is deemed a "success" for launch?

### ISSUE THREAD

**Issue by MCKapur** [r-spacex/SpaceX-API#71]
Eg. for tomorrow's launch, does it mean that it doesn't explode while trying to take off, or does it mean that it fails to make it into heliocentric orbit?

**Comment by jakewmeyer** [comment]
Generally for it to be considered a success, it must be a complete success, all the way to orbit. All the SpaceX produced parts must work nominally to be considered a success. 

We could add better granularity by adding success fields to the payload/capsule, and core. This could give a better picture when the launch success isn't 100% black and white.
