### ISSUE TITLE
Update NET

### ISSUE THREAD

**Issue by petrosh** [r-spacex/SpaceX-API#72]
- Paz `2018-02-10` > [`2018-02-16 1422 UTC, 0622 PST`](https://forum.nasaspaceflight.com/index.php?topic=44892.0)
- Hispasat `2018-02-14` > [`2018-02-22 0530 GMT (12:30 a.m. EST)`](https://spaceflightnow.com/launch-schedule/)

**Comment by jakewmeyer** [comment]
Updated

**Comment by petrosh** [comment]
Forgot `launch_date_unix`
- Paz `1518272520` > `1518790920`
- Hispasat `1518566400` > `1519277400`
