### ISSUE TITLE
Starlink 22 update info

### ISSUE THREAD

**Issue by Nekzuris** [r-spacex/SpaceX-API#720]
Launch has been delayed to 2021-03-24 08:58 GMT
https://twitter.com/SpaceflightNow/status/1373032583148224517

Questions:
- Is this the right place to post this?
- Who update this API?

**Comment by MattoDeg** [comment]
About question number 1, yes, it's the right place. Question 2: i think something is pickedup automatically from r/SpaceX manifest launch and something else is updated by @jakewmeyer.

Anyway, OCISLY, towed by Finn Falgout, Go Quest and new Ship Shelia Bordelon (which has to be added to /ships) departed.

Window, like all Starlink launches, is 0 (currently null).

Booster should be B1060 and this will be its fifth flight.

**Comment by Nekzuris** [comment]
Okay thanks, I was wondering because I couldn't find a guide on how to contribute to this dataset.

**Comment by MattoDeg** [comment]
Also to be added that one fairing half flew on Sentinel-6 and the other on a Starlink mission, but it isn't specified which one.

**Comment by MattoDeg** [comment]
Sources on Twitter say that the "Starlink" fairing flew on Starlink-19, but there's no official confermation.

Status is still set to `null`, but mission is a success. @jakewmeyer ping you just to be sure you receive notifications, hope everything is going well.

**Comment by MattoDeg** [comment]
Both fairing were succesfully recovered.

**Comment by jakewmeyer** [comment]
All is well, just been a busy few weeks. Should be up to date now 👍

**Comment by MattoDeg** [comment]
Fine, that's the most important thing (that you are fine and healthy) :) Thanks as usual

**Comment by MattoDeg** [comment]
You can close this issue.
