### ISSUE TITLE
Rocket info in v4?

### ISSUE THREAD

**Issue by BernStrom** [r-spacex/SpaceX-API#721]
Hey folks,

Is the rocket data such as the `rocket_id`, `rocket_name` and `rocket_type` from the previous v3 no longer available in v4? The data I get from the current version only returns something like this: `"rocket": "5e9d0d95eda69955f709d1eb"`. 

Previous response in v3 returns: 
`rocket: { "rocket_id": "falcon1", "rocket_name": "Falcon 1", "rocket_type": "Merlin A" }`

Couldn't find any mentioned of this so I raised an issue. If this was already been addressed, please redirect me and feel free to close this issue.

Cheers,
Bern

**Comment by 18iteration** [comment]
You have to use the rocket api link and add that cryptic value (5d358af....) to the end of the link
[Could've found this yourself when you would've read the docs](https://api.spacexdata.com/v4/rockets/:id)

**Comment by BernStrom** [comment]
Cheers, @18iteration 

I did eventually found it through reading the docs but forgotten to updated it here that I did. Should've read more thoroughly first before posting it here as an issue. Rookie mistake... 😅 

Still, thanks for redirecting me to the specific link in the docs :)

Gonna go ahead and close this now.
