### ISSUE TITLE
Latest and Next Launch have the same info?

### ISSUE THREAD

**Issue by 18iteration** [r-spacex/SpaceX-API#726]
I don't understand the difference between the "**latest**" and "**next**" launch.
They both seem to return 1:1 the same response/string.

From my understand/assumption, I would say that **latest** is supposed to be the last/previous undertaken launch (regardless whether the launch was a success or exploded, fact is it happened), and next is the upcoming launch.
**Latest <- Past
Next <- Future**

Can someone explain to me as to why next and latest return the same string and if that behavior is correct, how I can get the last/previous launch without using the all-previous launches api (Too many results affects performance, when I just need the latest/previous) ?

**Comment by MattoDeg** [comment]
No, they aren't the same: /latest gives you Starlink-21 and next gives you correctly Starlink-22. They are similar because payload is the same, but if you look carefully you get different booster values, for example.
