### ISSUE TITLE
Capsule "dragon" and "last_update" properties

### ISSUE THREAD

**Issue by persello** [r-spacex/SpaceX-API#728]
Hello,
From the documentation of v4, I see that capsules should have a `"dragon"` UUID property, and I can't see it when accessing `https://api.spacexdata.com/v4/capsules`.

I suppose that it should report the UUID of the corresponding Dragon model.

Also, let me know if you need a separate issue, but I noticed that the `"last_update"` property has some outdated values such as:
> Currently in construction for use in DM-2

when referred to capsule `5e9e2c5df359184b793b2674`.

**Comment by MattoDeg** [comment]
UUID is the id.

Agree about updating last_update field. Maybe @jakewmeyer can do something.

**Comment by persello** [comment]
I'm not talking about the capsule ID itself, but about a documented `"dragon"` field that I think should point to a Dragon model ID.

**Comment by MattoDeg** [comment]
Oh ok now I understand. You're right, maybe it should be updated and point to Cargo Dragon or Crew Dragon based on /capsules items. But also /dragons should be updated by adding Cargo Dragon V2, which first flew on CRS-21 last December.

**Comment by jakewmeyer** [comment]
1. I'll take a look at the capsule updater, the scraper is likely broken for that field.

2. You're right, according to the schema it should have that UUID, somehow that didn't make it into the schema for v4. Should be an easy add, good catch!
