### ISSUE TITLE
Is the API down?

### ISSUE THREAD

**Issue by stanifert** [r-spacex/SpaceX-API#731]
Making any call to `https://api.spacexdata.com/v4` results in a `523: Origin is unreachable` error.
@jakewmeyer

**Comment by jakewmeyer** [comment]
See https://status.spacexdata.com/

**Comment by timisenman** [comment]
Excellent resource! Thanks as always @jakewmeyer

**Comment by stanifert** [comment]
Thank you @jakewmeyer!
