### ISSUE TITLE
Starling 24/25 showing as ‘01/04/21’

### ISSUE THREAD

**Issue by ChopsKingsland** [r-spacex/SpaceX-API#743]
Could this be because there is no confirmed date yet? Is it possible for them to be removed until there is a date?

![image](https://user-images.githubusercontent.com/18499854/114284869-cf3beb00-9a4a-11eb-9ede-65493a834d81.jpeg)

**Comment by MattoDeg** [comment]
Date_precision is set to month, so it means that Starlink 24 and 25 should launch in April, but there's no fixed date as of today.

**Comment by jakewmeyer** [comment]
See https://github.com/r-spacex/SpaceX-API/tree/master/docs/v4#launch-date-faqs

**Comment by ChopsKingsland** [comment]
Sorry, didn't see that. Is there anyway to hide the ones where the date precision is set to month?

**Comment by xsorifc28** [comment]
When sorted by `flight_number`, these show up in the correct order. 
But when sorted by date, it is incorrect.
I assume the launch date is not known, thus defaulting to April 1st, which has passed. 

If the launch is expected in April, should the dates be set to end of April?

**Comment by jakewmeyer** [comment]
@ChopsKingsland 

`POST` to `https://api.spacexdata.com/v4/launches/query` with the body:

```json
{
    "query": {
        "upcoming": true,
        "date_precision": {
          "$ne": "month"
        }
    },
    "options": {
        "sort": {
            "flight_number": "asc"
        } 
    }
}
```

Should get you what you're looking for 👍

**Comment by ChopsKingsland** [comment]
Thanks, it works better now, as Crew-2 has been moved in front of the starlink ones, so my app isn't always showing t+
