### ISSUE TITLE
New app to go on app page

### ISSUE THREAD

**Issue by ChopsKingsland** [r-spacex/SpaceX-API#748]
I recently have released an app that uses the r-spacex api, and was wondering if it could be added to the Apps list? The link is: https://apps.apple.com/gb/app/spacextra/id1559360281 

Thanks!

**Comment by Kartikkumargujarati** [comment]
@ChopsKingsland Please follow the quick links in the docs page to submit an MR.
https://github.com/r-spacex/SpaceX-API/blob/master/docs/apps.md

**Comment by ChopsKingsland** [comment]
@jakewmeyer I have created a [PR](https://github.com/r-spacex/SpaceX-API/pull/784)
