### ISSUE TITLE
Add data validation for all requests

### ISSUE THREAD

**Issue by rafaelramalho19** [r-spacex/SpaceX-API#75]
Just found out that the `launches/upcoming` route is showing a "test" launch
https://cl.ly/3S2E3y0K041m/Image%202018-02-15%20at%202.26.24%20PM.png

Was this supposed to happen? 🐛

**Comment by jeroenboumans** [comment]
I'm not seeing this in my API responses. Probably just an API test document that was added to the mongodb.

**Comment by rafaelramalho19** [comment]
Shouldn't this be filtered automatically in the json response?

**Comment by jakewmeyer** [comment]
Added this to verify that mongo document ID's would transfer correctly. Was live  for maybe a minute or two at most.

**Comment by rafaelramalho19** [comment]
Should we add a validation method to every JSON response that removes the possibility of an invalid payload being sent?

**Comment by jakewmeyer** [comment]
We could, but I see that potentially causing at least 2 problems. 

1. The amount of validation required for each request might slow down the response time significantly, although we could try it to measure the impact.

2. If bad data is entered, all data is no longer accessible to people using the endpoints affected.

Currently the tests have extensive validation of the data, and the continuous integration runs cron job tests daily.

**Comment by rafaelramalho19** [comment]
Regarding your points:
1. Is possible to automatically exclude wrong data from the database? This could have a smaller performance impact
2. If the bad data is entered, only the bad data entry will be removed. So I don't see a problem here :)

**Comment by jakewmeyer** [comment]
Currently can't exclude bad data on the database end, since we're editing the database directly.

The better solution is probably validating the json response against some pre-set schema and omitting what isn't predefined, like you suggested earlier.

**Comment by rafaelramalho19** [comment]
I would suggest using [Joi](https://github.com/hapijs/joi). Had a great experience with it in the past.

**Comment by jakewmeyer** [comment]
Quick update on this issue:

Started implementing the validation for all requests, but the problem of removing the invalid fields still remains. With Joi it just returns the original value passed into the validation, not just the valid fields. This doesn't give a mechanism to remove the invalid fields from appearing.

So unless that can be implemented, I think I'll leave the validation to the currently written tests, which already provide a significant source of validation, with the only downside being that potentially invalid data might still make it to the end user.

**Comment by jakewmeyer** [comment]
Closing for now, since no solution is available
