### ISSUE TITLE
C206 shows as not reused on Crew 2

### ISSUE THREAD

**Issue by kj7rrv** [r-spacex/SpaceX-API#750]
![Screenshot_20210416-120336](https://user-images.githubusercontent.com/58444735/115071986-d3816180-9eab-11eb-83ca-12e512ddf5a3.png)

**Comment by jakewmeyer** [comment]
Updated, thanks!

**Comment by kj7rrv** [comment]
It's fixed now. Tysm!On Apr 16, 2021 12:54, Jake Meyer ***@***.***> wrote:
Updated, thanks!
