### ISSUE TITLE
Cannot receive core details

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#76]
Hi there @jakewmeyer, I've noticed it is not possible retreiving core data whenever the name contains spaces. A good example is the very first launch. It's **Merlin 1A**.1 core does not respond any data when calling the api endpoint. I've tried both calls below:

`GET https://api.spacexdata.com/v2/parts/cores/Merlin1A`
`GET https://api.spacexdata.com/v2/parts/cores/Merlin%201A`

Maybe it would be better to use other formats for the core-IDs within the returned launch core-data and the detailed core data returned by the endpoints above?

**Comment by jakewmeyer** [comment]
Likely because none of the cores have Merlin in them. Pretty sure only Falcon 9 cores are listed currently.

**Comment by jakewmeyer** [comment]
Went and added the Falcon 1 cores.

Since they don't have unique serials, I used the following for the 5 flights:

`Merlin 1A`
`Merlin 2A`
`Merlin 1C`
`Merlin 2C`
`Merlin 3C`

I'll update the launches with these serials as well
