### ISSUE TITLE
Boats location

### ISSUE THREAD

**Issue by persello** [r-spacex/SpaceX-API#771]
I noticed that all the ships in the `ships` endpoint are missing latitude/longitude/course information.
Are these fields supposed to be null for future development or only currently unavailable?

I also noticed that the ASDS barges have valid coordinates under the `landpads` endpoint, but right now, during the launch of Starlink-25, the OCISLY ASDS (which is involved in the booster recovery), still has the coordinates of Port Canaveral. Is this meant to show the home port position of the ASDS?

**Comment by jakewmeyer** [comment]
Pretty sure the barges don't use [AIS](https://en.wikipedia.org/wiki/Automatic_identification_system), so those coordinates should represent the home port. Went ahead and fixed those coords.

As far as the ships go, previously we were scraping the [Marine Traffic](https://www.marinetraffic.com/) pages to grab coords, speed, course, etc... but they switched to a SPA, so the scraper would need to run a headless browser to grab everything. Just haven't gotten around to rewriting it yet 🙃 . 

The other issue is the only public data available is from ground based AIS stations on the coast, and the range is only about ~40 NM off the coast. Most of the landing locations are 100-200NM off the coast, so the data kinda falls off after that point anyway. Only solution around that is paying for API access to a satellite AIS provider, but those run about $500+ a month for access 😆

**Comment by persello** [comment]
That's understandable, and definitely not cheap.

In my application (it's still in TestFlight beta, that's why I didn't add it to the clients list), I show a map with some points of interest for every launch, and at this point it's _definitely_ cheaper to add a little disclaimer about location updates. I understand that getting the live location for all the droneships and support ships is not easy, and still, it would have made little sense (in my case) to show that information in the context of a **past** launch.

---

As a suggestion for an eventual future version, it would be really useful to have a pair of fields (lat/lon, maybe even time) that keep track of the location of the droneship at the time of a core's landing. I have found a map that could be useful for something like this, and it seems to be constantly updated, but I have no idea about how coordinates could be extracted from it (in general, I have literally zero experience in backend development).

 [This](https://www.google.com/maps/d/viewer?mid=1wvgFIPuOmI8da9EIB88tHo9vamo&ll=30.297696698261085%2C-84.54485316937146&z=4) is the map I'm talking about, maybe you already know it and use it for other data. It seems quite accurate and it has a long changelog that shows constant updates. It also has lots of other useful data, such as hazard areas, splashdown points...

I leave this issue open for those who don't know about the broken scraper, feel free to close it if you prefer.
