### ISSUE TITLE
API Unresponsive

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#774]
Seeing this response `Operation `launches.findOne()` buffering timed out after 10000ms` from the launches endpoint `https://api.spacexdata.com/v4/launches/latest`

Wanted to give a heads up because I don't see the issue caught in the API status page (https://status.spacexdata.com)

**Comment by TNelen** [comment]
I'm getting a 502 response since 10 minutes ago. Might be related.

**Comment by jakewmeyer** [comment]
Looking into it

**Comment by jakewmeyer** [comment]
Looks like there's some emergency maintenance going on: https://status.vultr.com/#DFW

Not much I can do currently, I'll keep posting updates as I see them

**Comment by jakewmeyer** [comment]
Issue appears to have resolved according to Vultr, let me know if you're still having issues

**Comment by TNelen** [comment]
It's resolved. Thanks for the update!

**Comment by joseywoermann** [comment]
I'm getting a 502 error since ~ 2 minutes ago.

**Comment by joseywoermann** [comment]
> 
> 
> I'm getting a 502 error since ~ 2 minutes ago (9 pm CEST; 7 pm UTC). It was working before.

It's working again.

**Comment by sanjayrjs16** [comment]
I am randomly  getting the CORS access issue(Blocked by browser), sometimes occurs, sometimes not. Was working fine till yesterday. Anything related to above issue ?

**Comment by jakewmeyer** [comment]
There's some ongoing issue I'm working on debugging, not sure if it's related to the incident this morning.

@sanjayrjs16 CORS should be wide open, so it might be related to the issues today

**Comment by timisenman** [comment]
Awesome, thanks for the quick action. Let me know when/if the the issue can be closed.

**Comment by jakewmeyer** [comment]
Should be good to close 👍
