### ISSUE TITLE
New App to add to the list

### ISSUE THREAD

**Issue by TNelen** [r-spacex/SpaceX-API#776]
Hi team!

I've created a new Android app using the SpaceX-API. Would it be possible to add it to the list?

https://play.google.com/store/apps/details?id=com.magnetar.spacexlauncher

Feel free to check it out and let me know what you think!

The app is created in Flutter, the code of this project is open-source and available here.
https://github.com/TNelen/SpacexLaunchApp

Many thanks in advance!

![promo2](https://user-images.githubusercontent.com/37212860/117500197-95440300-af7c-11eb-8eab-2ad404ec1072.png)

**Comment by jakewmeyer** [comment]
Sure! Easiest way to add it is through a PR, or I can manually add it if needed.

**Comment by Kartikkumargujarati** [comment]
@TNelen Follow the quick links on the docs page to submit an MR.
https://github.com/r-spacex/SpaceX-API/blob/master/docs/apps.md
