### ISSUE TITLE
V3 API is currently down

### ISSUE THREAD

**Issue by abijithpradeep** [r-spacex/SpaceX-API#795]
![spacex V3 down](https://user-images.githubusercontent.com/22325449/118952879-f1922400-b979-11eb-9e6d-aae7dbfbbdc1.png)

Hi folks, Although, the [status check page](https://status.spacexdata.com/) says its operational, the [version 3 API](https://api.spacexdata.com/v3/launches) is currently not responding. I have tried on multiple devices to confirm.

GET request on the API is giving a 502 Bad Gateway status.

**Comment by adelinyshka** [comment]
Hi
I have the same problem and 502 Bad Gateway status for all get requests to V3 API
![image](https://user-images.githubusercontent.com/35169516/118984801-8a2ea100-b986-11eb-8075-574445586d8f.png)

**Comment by jakewmeyer** [comment]
Looks like it was related to this MongoDB Atlas upgrade to the root cert:

 https://docs.atlas.mongodb.com/reference/faq/security/#which-certificate-authority-signs-mongodb-atlas-cluster-tls-certificates-
https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html

The upgrade caused some kind of hangup in the container, just had to be restarted.

Should be good now 👍

**Comment by abijithpradeep** [comment]
Yeah, Its good now. Thanks

**Comment by abijithpradeep** [comment]
![spacex api down again](https://user-images.githubusercontent.com/22325449/119602344-92fcf800-be08-11eb-8cbe-c64de7c25159.png)

V3 API is down once again. Please look into it.
