### ISSUE TITLE
Query with data range

### ISSUE THREAD

**Issue by BobDeKort** [r-spacex/SpaceX-API#80]
I am having trouble using the start and end parameters to get launches in the past year.
What format of dates is used to send the request?

What I tried just returned all the launches:
 * https://api.spacexdata.com/v2/launches?start=1509392040&end=1520314380
 * https://api.spacexdata.com/v2/launches?start=23/03/2017&end=23/03/2018
 * https://api.spacexdata.com/v2/launches?start=01-03-2017&end=01-03-2018
 * https://api.spacexdata.com/v2/launches?start=2018-03-06T05:33:00Z&end=2018-01-31T21:25:00Z

Thank you!

**Comment by jhpratt** [comment]
Start and end parameters expect YYYY-MM-DD, unless something has changed that I'm not aware of.

**Comment by jakewmeyer** [comment]
Should be YYYY-MM-DD with no time currently like @jhpratt  mentioned, since we're nowhere near having multiple launches in a 24 hour period.

Also the params are **start** and **final** instead of **end**.

[https://api.spacexdata.com/v2/launches?start=2017-01-03&final=2018-01-03](https://api.spacexdata.com/v2/launches?start=2017-01-03&final=2018-01-03)

**Comment by jakewmeyer** [comment]
Working on a better solution for this. It should be able to accept any date format, instead of forcing the user into a single format.

Also adding support for the **end** keyword in addition to **final** since **end** is more intuitive

**Comment by jhpratt** [comment]
moment.js should be able to parse any sensible format, and probably automatically sets the time of day to 0:00. Certainly something worth looking into.

**Comment by jakewmeyer** [comment]
Initially went with moment.js, but kept getting deprecation warnings for parsing dates not in ISO or RFC2822 format. From my testing, Date.parse works perfectly well for the majority of possible formats.

@BobDeKort As of now, you can now use the **end** keyword, and the API should accept most reasonable date formats, looks like all of your links now work except the one formatted as DD/MM/YYYY

Any valid Javascript date format should work 👍 
[https://www.w3schools.com/js/js_date_formats.asp](https://www.w3schools.com/js/js_date_formats.asp)
