### ISSUE TITLE
Payload and Roadster orbit information differences

### ISSUE THREAD

**Issue by persello** [r-spacex/SpaceX-API#807]
Hello, by looking at the payload information for the "Falcon Heavy Test Flight" launch, I noticed some strange values:

```json
"mass_kg": 1350,
"mass_lbs": 2976.2,
"orbit": "HCO",
"reference_system": "heliocentric",
"regime": null,
"longitude": null,
"semi_major_axis_km": 9943.766,
"eccentricity": 0.3404246,
"periapsis_km": 180.528,
"apoapsis_km": 6950.733,
"inclination_deg": 29.0185,
"period_min": 164.469,
"lifespan_years": 3500000,
"epoch": "2018-02-06T22:36:19.000Z",
"mean_motion": 8.75540848,
"raan": 287.358,
"arg_of_pericenter": 180.027,
"mean_anomaly": 180.584,
```

I'm not an expert about orbital physics, but the periapsis, apoapsis and period seem to be too short. At least, they are very different from those available in the `/roadster` endpoint. Is this data wrong or it's related to the first part of the launch, while the roadster was still in a near orbit? Am I wrongly interpreting these values?

In the meantime, should I ignore the `/payload` endpoint data for this specific launch, and refer to the `/roadster` endpoint data instead?

**Comment by jakewmeyer** [comment]
NORAD doesn't track objects out of earth's orbit, so this is the reason for the discrepancy. The roadster specific orbit is tracked using [JPL HORIZONS](https://ssd.jpl.nasa.gov/?horizons), which tracks objects farther away. So the `/roadster` orbit is the more accurate of the two.
