### ISSUE TITLE
Landing attempts informations

### ISSUE THREAD

**Issue by mdcarter** [r-spacex/SpaceX-API#81]
The flight for Bangabandhu-1 is supposed to be landing on OCISLY but there's no way using the API to have this informations right now.
Maybe landing_type and landing_vehicle could be filled even in upcoming launches ?

**Comment by jakewmeyer** [comment]
Should be updated 👍 

Currently everything starts as null, and gets filled in as information becomes available.

**Comment by mdcarter** [comment]
Oh okay so it was only a data problem, I see.
Sorry for the ticket 😅 Thanks !
