### ISSUE TITLE
Launchpad query with HomeAssistant with V4

### ISSUE THREAD

**Issue by DarKOrange75** [r-spacex/SpaceX-API#820]
Hi all,

I was using V3 with home assistant to get the full name of the next launchpad. But unfortunately this has been broken with V4. Anyone has an idea on how to use V4 with home assistant to get the next launchpad name?

Thank you for your help!

**Comment by jakewmeyer** [comment]
What's the exact route you're using in V3?

The V4 launchpad endpoints still have the `full_name` prop

**Comment by DarKOrange75** [comment]
- platform: rest
    name: SpaceX
    json_attributes:
      - mission_name
      - launch_site
      - rocket
      - details
    value_template: '{{ value_json[0]["launch_date_unix"] }}'
    resource: 'https://api.spacexdata.com/v3/launches/upcoming?limit=1&offset=0'

**Comment by jakewmeyer** [comment]
Not as familiar with how that particular plugin works, but it's also possible to get this in a single API call:

`POST https://api.spacexdata.com/v4/launches/query`

Body:

```json
{
    "query": {
        "upcoming": true
    },
    "options": {
        "select": {
            "launchpad": 1
        },
        "populate": {
            "path": "launchpad",
            "select": "full_name"
        },
        "sort": {
            "date_utc": "asc"
        },
        "limit": 1
    }
}
```

Returns:

```json
{
    "docs": [
        {
            "launchpad": {
                "full_name": "Cape Canaveral Space Force Station Space Launch Complex 40",
                "id": "5e9e4501f509094ba4566f84"
            },
            "id": "5fe3af6db3467846b3242160"
        }
    ],
    "totalDocs": 15,
    "offset": 0,
    "limit": 1,
    "totalPages": 15,
    "page": 1,
    "pagingCounter": 1,
    "hasPrevPage": false,
    "hasNextPage": true,
    "prevPage": null,
    "nextPage": 2
}
```

If you need all the info about the launch, feel free to remove those `select` props from the body.

**Comment by DarKOrange75** [comment]
Thank you for trying to help me. Unfortunately I don't know how to make a working sensor out of that.
It is not a plug-in, it is a native integration in Home Assistant designed to query rest APIs

https://www.home-assistant.io/integrations/sensor.rest/
