### ISSUE TITLE
What's your problem？

### ISSUE THREAD

**Issue by MalavitaC** [r-spacex/SpaceX-API#821]
What is the use of this if?

`if (ctx.request.method !== 'GET' || ctx.request.method !== 'POST')`

[Line 62](https://github1s.com/r-spacex/SpaceX-API/blob/master/middleware/cache.js)

**Comment by jakewmeyer** [comment]
This prevents the cache middleware from being used with a PUT, PATCH, DELETE, etc... because those should not be cached.

**Comment by MalavitaC** [comment]
Are you **sure**? @jakewmeyer 
Let's **try** to run
``` js
const method = 'GET'
if (method !== 'GET' || method !== 'POST'){
  console.log(method)
}
//output GET
```
``` js
const method = 'POST'
if (method !== 'GET' || method !== 'POST'){
  console.log(method)
}
//output POST
```
``` js
const method = 'PUT'
if (method !== 'GET' || method !== 'POST'){
  console.log(method)
}
//output PUT
```
``` js
const method = 'PATCH'
if (method !== 'GET' || method !== 'POST'){
  console.log(method)
}
//output PATCH
```

**Comment by jakewmeyer** [comment]
Whoops, that's definitely wrong. Prior to V4 this condition returned early, but looks like I reversed the flow without updating the condition. 

Thanks for reporting it! I'll get a fix in shortly 👍
