### ISSUE TITLE
Launchpad images?

### ISSUE THREAD

**Issue by pavles6** [r-spacex/SpaceX-API#822]
Hey, any chances that in the near future we would be able to get launchpad images when querying launchpads?

**Comment by jakewmeyer** [comment]
Sure! Happy to add them, I'll gather some for this thread over the weekend 👍

**Comment by pavles6** [comment]
Awesome, I'm currently coding an web app that maps variety of data from this api. I'll share it here when 1.0 version will be released and deployed :)

**Comment by jakewmeyer** [comment]
What I have so far:

[CCSFS SLC 40](https://i.imgur.com/9oEMXwa.png)
[KSC LC 39A](https://i.imgur.com/1jwU0Pk.png)
[VAFB SLC 4E](https://i.imgur.com/asp5L08.png)
[STLS](https://i.imgur.com/ZzTTC5p.png)
[Kwajalein Atoll](https://i.imgur.com/GGPgsVs.png)
[VAFB SLC 3W](https://i.imgur.com/7uXe1Kv.png)

**Comment by pavles6** [comment]
Cool, there's also a good pic of [OCSILY](https://www.flickr.com/photos/spacex/19128420045) I've found on Flickr. License says it's free to resize and re-distribute as long as you reference it :)

**Comment by jesusrp98** [comment]
Hey this feature is cool! Any news on that?

**Comment by jakewmeyer** [comment]
Images have been added to launchpads + landpads
