### ISSUE TITLE
Orphaned Payload

### ISSUE THREAD

**Issue by jdineen21** [r-spacex/SpaceX-API#828]
Hi big fan of the project, it looks to me like a payload with id [5fe3c02fb3467846b324218f](https://api.spacexdata.com/v4/payloads/5fe3c02fb3467846b324218f) appears to have no valid launch associated with it.

Not found when visiting its associated [launch](https://api.spacexdata.com/v4/launches/5fe3afaeb3467846b3242163)

**Comment by jakewmeyer** [comment]
Ah, that was from a postponed launch, should be removed now 👍
