### ISSUE TITLE
Update crew format

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#842]
@jakewmeyer are there any updates towards the implementation of the new crew format detailed in #621?

**Comment by jakewmeyer** [comment]
Hoping to get this done over the weekend. Need to version the launches endpoint first, then I'll add the backwards compatible translation bit for v4. 

So after this change people will need to bump their api routes to `https://api.spacexdata.com/v5` for launches only to see the update. Also going to add a version alias `https://api.spacexdata.com/latest` version for those that like to live dangerously 😆.

**Comment by jakewmeyer** [comment]
New crew format is live under `https://api.spacexdata.com/v5/launches`, and all roles should be added at this point.
