### ISSUE TITLE
Small fix SES-12

### ISSUE THREAD

**Issue by OlympusNSP** [r-spacex/SpaceX-API#85]
Again:
"core_serial": "B1040.2"
to 
"core_serial": "B1040"

Update:
And CRS-15:
"core_serial": "B1045",
"flight": 2,
"block": 4,
"reused": true

And, of course, Falcon Heavy side booster landing expected, "landing_type": "RTLS", "landing_vehicle": "LZ-1" (or "LZ-?", or leave null), and "block": 5.

**Comment by jakewmeyer** [comment]
Updated 👍
