### ISSUE TITLE
V4 API not support query string like 'order' or 'limit' ... WHY?

### ISSUE THREAD

**Issue by MarioRover** [r-spacex/SpaceX-API#852]
https://api.spacexdata.com/v4/launches/past?order=desc&limit=3
I request this api in Postman app, and server response all launch without order desc and limit item ...

**Comment by jakewmeyer** [comment]
I recommend using the dedicated query endpoint

```http
POST https://api.spacexdata.com/v4/query
```

Body:

```json
{
	"query": {
		"upcoming": false
	},
	"options": {
		"sort": {
			"flight_number": "desc"
		},
		"limit": 3
	}
}
```

**Comment by MarioRover** [comment]
> I recommend using the dedicated query endpoint
> 
> ```httpspec
> POST https://api.spacexdata.com/v4/query
> ```
> 
> Body:
> 
> ```json
> {
> 	"query": {
> 		"upcoming": false
> 	},
> 	"options": {
> 		"sort": {
> 			"flight_number": "desc"
> 		},
> 		"limit": 3
> 	}
> }
> ```
