### ISSUE TITLE
Error on post to launches/query

### ISSUE THREAD

**Issue by Fedannie** [r-spacex/SpaceX-API#858]
Hey,
I'm getting an error "Cannot read property 'replace' of undefined" for every post request to the "api.spacexdata.com/v4/launches/query" if the request contains "populate" option. Yesterday everything worked fine, I suppose the cause lies in the last commits. Please, take a look

**Comment by jakewmeyer** [comment]
Is this still an issue? If so, send the exact request you're trying to make, thanks!
