### ISSUE TITLE
Flight 34 (Amos-6) - "land_success" is false, should be null

### ISSUE THREAD

**Issue by jclishman** [r-spacex/SpaceX-API#86]
Would make more sense seeing as no landing was attempted

**Comment by jclishman** [comment]
Looking closer, it seems that a lot of missions have `land_success` set to false when there wasn't a landing attempt in the first place. Flights 2, 5, 6, 7, 8, 9, 10, 12, 13, 16, 17, 21, 23, 37, 40, 44, 56, 57, 58, and 59.

**Comment by jakewmeyer** [comment]
Null might be the better option, so it doesn't cause confusion when trying to tell if a landing was attempted at all.

**Comment by jclishman** [comment]
Exactly. If I want to get a count of how many landing attempts there have been, I only need to use something like this:

```
if core["land_success"] is not None:

	if core["land_success"]:
		successful_landings += 1

	landings_attempted += 1
```

**Comment by jakewmeyer** [comment]
Everything should be corrected, Thanks for the suggestion 👍
