### ISSUE TITLE
Difference between Upcoming and All Launches?

### ISSUE THREAD

**Issue by 18iteration** [r-spacex/SpaceX-API#863]
Really love this API and I will keep it short to steal as little time as possible.

I want to fetch both the past+upcoming launches, which promptly made me choose the v4.../launches/ endpoint but now, after testing the /upcoming endpoint, I notice a discrepancy.

The information provided after the past launches in the /launches endpoint don't match with the information listed under the /upcoming endpoint.

May someone be kind enough to clear up the confusion? 

### (1st Window: /past, 2nd Window: /upcoming, 3rd Window: /launches)
![Screenshot_3](https://user-images.githubusercontent.com/45468984/126913588-0a475f6e-ad43-4519-9ded-553e8de25452.png)

**Comment by jakewmeyer** [comment]
@18iteration Definitely a bug, looks like I missed adding a default sort for `/launches`, hence the weird ordering. Should have a fix out shortly.
