### ISSUE TITLE
How to convert the code?

### ISSUE THREAD

**Issue by Randore** [r-spacex/SpaceX-API#866]
Hi,

Can someone please explain - how to convert or use this code to show string or converted data for the following.

`"rocket": "5e9d0d95eda69973a809d1ec",`

In older version v3, we have location, failed status and more but how to add these in v4 and v5

Thanks in advance.

**Comment by tsensei** [comment]
You can either post a query for populating this field or make another get request 
`https://api.spacexdata.com/v4/rockets/${rocket_id}` 
Like so, where rocket is the one you provided

**Comment by tsensei** [comment]
> Hi,
> 
> Can someone please explain - how to convert or use this code to show string or converted data for the following.
> 
> `"rocket": "5e9d0d95eda69973a809d1ec",`
> 
> In older version v3, we have location, failed status and more but how to add these in v4 and v5
> 
> Thanks in advance.

You can either post a query for populating this field or make another get request
`https://api.spacexdata.com/v4/rockets/${rocket_id}`
Like so, where rocket is the one you provided

**Comment by jakewmeyer** [comment]
Easiest is to use the populate property to expand the UUID into the full object. For example, for launches:

```http
POST https://api.spacexdata.com/v5/launches/query
```

Body:

```json
{
  "query": {},
  "options": {
    "populate": [
      "rocket"
    ]
  }
}
```

**Comment by Randore** [comment]
Thank you all, I will try the solutions.
