### ISSUE TITLE
Company and history endpoint not present on `v5`

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#869]
Both 'company' and 'history' endpoint are not available through the `v5` version of the API.
- `https://api.spacexdata.com/v5/company/`
- `https://api.spacexdata.com/v5/history/`

**Comment by jakewmeyer** [comment]
Going forward, grouped routes (`/launches`, `/cores`, etc...) will be individually versioned. Because the only schema change was in the `/launches` endpoint the only v5 endpoint is launches currently.
