### ISSUE TITLE
Launches query

### ISSUE THREAD

**Issue by Prathapkarumanchi** [r-spacex/SpaceX-API#871]
Hi, can someone please help me with the following.

1. Launches `https://api.spacexdata.com/v4/launches`
2. Upcoming `https://api.spacexdata.com/v4/launches/upcoming`
3.  Success:   ?
4. Failed launches: ?

I tried these two queries for last 2 but not getting proper data 

```
https://api.spacexdata.com/v4/launches/query?options=success
https://api.spacexdata.com/v4/launches/query?options=failures
```

Thanks in advance

**Comment by tsensei** [comment]
Firstly, queries are done using post

And you do these this way 

`POST  https://api.spacexdata.com/v5/launches/query`

In body:
For successful launches

`{
  "query":{
    "success":{
      "$eq" : true
    }
  }
}`

For failed launches

`
{
  "query":{
    "success":{
      "$eq" : false
    }
  }
}
`
