### ISSUE TITLE
Unable to fetch details for one launch

### ISSUE THREAD

**Issue by jskubick** [r-spacex/SpaceX-API#875]
I'm attempting to get a list of upcoming launches, then fetch the details for a specific launch from that list by id.

According to the docs, the following query gets upcoming launches (and in fact, works):

[https://api.spacexdata.com/v5/launches/upcoming](https://api.spacexdata.com/v5/launches/upcoming)

So far, so good... when I fetched the URL in Firefox right now, it returned the JSON results and nicely formatted them. 

Launch #1 in the list ("Polar Starlink-1") has id: "60e3bf0d73359e1e20335c37"

OK, so now I need to fetch the details for that one launch.

According to the documentation at [https://github.com/r-spacex/SpaceX-API/blob/master/docs/launches/v5/one.md](https://github.com/r-spacex/SpaceX-API/blob/master/docs/launches/v5/one.md) , the URL is https://api.spacexdata.com/v5/launches/:id, and the method is GET.

However, none of the following URLs work (I didn't expect most of them to work, but tried the variations "just in case"):

[https://api.spacexdata.com/v5/launches/:60e3bf0d73359e1e20335c37](https://api.spacexdata.com/v5/launches/:60e3bf0d73359e1e20335c37)

[https://api.spacexdata.com/v5/launches/:id=60e3bf0d73359e1e20335c37](https://api.spacexdata.com/v5/launches/:id=60e3bf0d73359e1e20335c37)

[
https://api.spacexdata.com/v5/launches/:id="60e3bf0d73359e1e20335c37"](
https://api.spacexdata.com/v5/launches/:id="60e3bf0d73359e1e20335c37")

[https://api.spacexdata.com/v5/launches/:[60e3bf0d73359e1e20335c37]](https://api.spacexdata.com/v5/launches/:[60e3bf0d73359e1e20335c37])

[https://api.spacexdata.com/v5/launches/:id=[60e3bf0d73359e1e20335c37]](https://api.spacexdata.com/v5/launches/:id=[60e3bf0d73359e1e20335c37])

[https://api.spacexdata.com/v5/launches/:id=[%2260e3bf0d73359e1e20335c37%22]](https://api.spacexdata.com/v5/launches/:id=[%2260e3bf0d73359e1e20335c37%22])

Any idea what I'm doing wrong? Is the "id" parameter at the end of the list _not_ the 'id' I should be passing to v5/launches? Am I formatting it incorrectly? Or am I doing something completely and fundamentally wrong?

**Comment by myankura** [comment]
For those URLs that you say aren't working for you all you need to do is tack the Id of the launch you want at the end.
https://api.spacexdata.com/v5/launches/60e3bf0d73359e1e20335c37
