### ISSUE TITLE
API Offline - 502 Bad Gateway Error

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#876]
Seems like it started within the hour. 

Only scope I've looked into is the Launches endpoint.

**Comment by Pedro-0550** [comment]
I tested on all endpoints and all of them are not working, its probally down, v3 works fine tho.

**Comment by timisenman** [comment]
Appreciate the confirmation

**Comment by jakewmeyer** [comment]
Should be back up now, looking into what happened

**Comment by sorenhoyer** [comment]
Over the last couple of days this has happened quite a lot (v4)
