### ISSUE TITLE
SpaceX company history & events

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#89]
**This is an API feature request originated in #1** 

Extending the API with company history and important events (referencing blogposts or news posts perhaps) of SpaceX could be interesting. An overview of events for the company can be gound here in the [Making History](http://www.spacex.com/about#block-block-11) section.

A company Event model could contain data like: _title_, _event date_ (yyyy-mm-dd or other desired formats like the [lauches](https://github.com/r-spacex/SpaceX-API/wiki/Launches)), _description_, _original blog url/reddit url_ about the event. All sortable by date (ASC/DESC) and probably groupable by year like the timetable on the provided link above. Maybe add categories, or vehicles IDs concerned to the event used for filtering.

Possible endpoint entity name: ~~**events**~~ **milestones** or **history**

- `/v2/info/history` returning all history for now
- `/v2/info/history?year=2018` returning events for a specific date/year
- `/v2/info/history?year=2018&order=asc` returning events for a specific date/year ordered (asc or desc)
- `/v2/info/history?rocketid=falcon9` returning all events for a specific rockettype

Just some quick endpoints I'm thinking of.
Looking forward to extend my application with this data so it can go beta! :) 👍

**Comment by jakewmeyer** [comment]
Aren't most of the important events launches though? Seems like a good amount of overlap, but with a clearer way of finding the important ones.

**Comment by jeroenboumans** [comment]
@jakewmeyer I think they can be considered milestones. There sometimes is a launch event linked with the milestone. Maybe add that to the data model as well?

**Comment by jakewmeyer** [comment]
Sample model
```json
{
    "title": "First Dragon Reflight",
    "event_date_utc": "2017-06-03T21:07:00Z",
    "flight_number": 41,
    "details": "This Dragon resupply mission represented the first reflight of a commercial spacecraft to and from the International Space Station.",
    "links": {
        "reddit": "https://www.reddit.com/r/spacex/comments/6ektkt/welcome_to_the_rspacex_crs11_official_launch/",
        "spaceflightnow": "https://spaceflightnow.com/2017/06/03/reused-dragon-cargo-capsule-launched-on-journey-to-space-station/",
        "wikipedia": "https://en.wikipedia.org/wiki/SpaceX_CRS-11"
    }
}
```

**Comment by jakewmeyer** [comment]
Also noticed the history page on the spacex website hasn't been updated since December. Are we going to start determining milestones? 😆

**Comment by jeroenboumans** [comment]
Thanks for the heads up @jakewmeyer. Well... keep it **history** then ;) Looking forward implementing the data! Cheers! 👍

**Comment by jakewmeyer** [comment]
Started working on the data, and there's lots of missing info before 2014

**Comment by jeroenboumans** [comment]
@jakewmeyer that would be a nice addition for the launches. I like it when model data is connected through the whole API. If we extend the launches endpoint, would it still be possible to filter the launches by the fact they're milestones or not? For example: 
- Return all milestone launches
`/v2/launches?milestone=true`
- Return all milestone launches of 2017
`/v2/launches?milestone=true&launch_year=2017`

I also see some milestones outside of the launch milestones. In the setup above, is there still a way to receive these from the API as well. Or maybe use a setup like:
- Return all milestones (the model format like posted above)
`/v2/milestones` 
`/v2/milestones?year=2017` 
- Return detailed information about the given milestone. This can always be extended further in the future.
`/v2/milestones?id=X` 
- Return the milestone launches. Basic data will be returned here like _title_, _description_, _milestone_id_ & _date_ (the model format like posted above)
`/v2/launches?milestone=true`

**Comment by jakewmeyer** [comment]
Decided to keep the history separate. Date is done, getting the endpoint and sorting methods done next

**Comment by jakewmeyer** [comment]
History endpoints are live. Still need to add 2018 data. Currently you can search by flight number using `flight_number` or a date range using `start` and `end`. 

[https://api.spacexdata.com/v2/info/history?start=2008-08-28&end=2009-05-28](https://api.spacexdata.com/v2/info/history?start=2008-08-28&end=2009-05-28)

[https://api.spacexdata.com/v2/info/history?flight_number=14](https://api.spacexdata.com/v2/info/history?flight_number=14)

**Comment by jakewmeyer** [comment]
2018 data added
