### ISSUE TITLE
Unable to search for launch, rocket by name

### ISSUE THREAD

**Issue by pHoeniX-svg** [r-spacex/SpaceX-API#892]
Hello, please how do I query for a launch, rocket etc., by name using an input field?

**Comment by aimanafzal** [comment]
@pHoeniX-svg You can query by id 
Example: https://api.spacexdata.com/v4/rockets/5e9d0d95eda69974db09d1ed
https://api.spacexdata.com/v4/rockets/{{id}}

**Comment by jakewmeyer** [comment]
@pHoeniX-svg What kind of input? Is it a filter on any field?

**Comment by pHoeniX-svg** [comment]
@aimanafzal I already know about querying by id. I want to query by name
@jakewmeyer Yeah. I want to a user to be able to filter the results by name of launch, rocket etc. From what I've read in the docs after posting the question, it seems like a POST request. I would like to how I can query by name with a limit of maybe 20 results per page. Thanks

**Comment by pHoeniX-svg** [comment]
also, do I need to install mongoose-paginate in my application??

**Comment by jakewmeyer** [comment]
Don't need to install mongoose-paginate, it's more as a reference to what the API is using under the hood.

To query the name of a launch:

```
POST https://api.spacexdata.com/v5/launches/query
```

Body:

```json
{
	"query": {
		"name": "CRS-23"
	}
}
```

**Comment by jakewmeyer** [comment]
Name of a rocket is similar:

```
POST https://api.spacexdata.com/v4/rockets/query
```

Body:

```json
{
  "query": {
    "name": "Falcon 9"
  }
}
```

**Comment by pHoeniX-svg** [comment]
@jakewmeyer Thanks for assisting me with this. I'm a newbie dev and this is my first project with an API. It has been a wonderful process and I'm really glad to have someone who's patient enough to answer my questions. I appreciate that and I look forward to seeing what more I can do with this API.
