### ISSUE TITLE
Can't figure out how to use GET request for a single rocket/launchpad/etc.

### ISSUE THREAD

**Issue by dhdylan** [r-spacex/SpaceX-API#901]
Every time I try to use the get request URL, I either get all of the launchpads or rockets returned, or I get a 404.

I've tried two different URL's for the get request since I wasn't sure if I had the syntax wrong or something.

I get the 404 code if I use "https://api.spacexdata.com/v4/launchpads/:id" as the url, which I imagine is because ".../launchpads/:id?id=xxxxx..." is not the correct syntax.
This is what my code looks like for that:

```
import requests

upcomingLaunchesURL = "https://api.spacexdata.com/v4/launches/upcoming"
launchPadGetURL = "https://api.spacexdata.com/v4/launchpads/:id"
rocketGetURL = "https://api.spacexdata.com/v4/rockets/"

upcomingLaunches = requests.get(upcomingLaunchesURL).json()

launchpadID = upcomingLaunches[0]["launchpad"]

launchpadResponse = requests.get(url=launchPadGetURL, params={'id': launchpadID})

```

All the other variables are correct there. `launchpadID` returns the correct value and it is a string.

-------------------------------------------------------------------------------------------------------------------

On the other hand, if I use the proper syntax (or so I would be led to believe), instead of returning the launchpad or rocket corresponding to the ID that I passed in, I get all of the rockets/launchpads returned as if I was using the "all" URL.

My code in this case is the exact same thing, just with the different URL like so:

```
import requests

upcomingLaunchesURL = "https://api.spacexdata.com/v4/launches/upcoming"
launchPadGetURL = "https://api.spacexdata.com/v4/launchpads/"
rocketGetURL = "https://api.spacexdata.com/v4/rockets/"

upcomingLaunches = requests.get(upcomingLaunchesURL).json()

launchpadID = upcomingLaunches[0]["launchpad"]

launchpadResponse = requests.get(url=launchPadGetURL, params={'id': launchpadID})
```

i've even looked at the response objects, and the urls that are showing up seem to look just right. For example when I use the above code - which returns 200, but gives me all of the launchpads instead of one - the url it's using is "https://api.spacexdata.com/v4/launchpads/?id=5e9e4502f509094188566f88"

Shouldn't this be giving me just one JSON object for that id? What am I doing wrong?

**Comment by iNoles** [comment]
in https://api.spacexdata.com/v4/rockets, you find id fields for a value. 

one of them is https://api.spacexdata.com/v4/rockets/5e9d0d95eda69955f709d1eb

**Comment by jakewmeyer** [comment]
For your specific example, the correct url would be [https://api.spacexdata.com/v4/launchpads/5e9e4502f509094188566f88](https://api.spacexdata.com/v4/launchpads/5e9e4502f509094188566f88)

**Comment by dhdylan** [comment]
Okay, I’ve gotten it working by just appending the is onto the url like you’ve done there. I was using the “parameters” argument which the API wasn’t responding to.
Perhaps this should be noted somewhere in the documentation for clarification purposes. For python users at least.
Thanks.
