### ISSUE TITLE
v4 broken link in postman docs

### ISSUE THREAD

**Issue by Simperfy** [r-spacex/SpaceX-API#902]
1. Visit https://docs.spacexdata.com/
2. Clicking the hyperlink v4 points to [github 404 page](https://github.com/r-spacex/SpaceX-API/tree/master/docs/v4)

![image](https://user-images.githubusercontent.com/28738855/133574360-44d4b979-813c-405a-85be-1762c8f880d1.png)
![image](https://user-images.githubusercontent.com/28738855/133574466-8dbc8610-edf5-4b46-8cbf-2afff200109a.png)

**Comment by jakewmeyer** [comment]
Updated 👍

**Comment by Simperfy** [comment]
All good, thanks.
