### ISSUE TITLE
Add BFR to the list of rockets

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#93]
As the title of the issue says it all: can BFR be added to the list of rockets or are there any reasons this can/is not be done just yet?

**Comment by jakewmeyer** [comment]
We could add it, but most of the data would be missing

**Comment by jakewmeyer** [comment]
BFR data is in, gathered as much info as I could. Still a few fields missing, but it's a start 👍

**Comment by jeroenboumans** [comment]
Thanks @jakewmeyer !
