### ISSUE TITLE
[V4] Select a single launchpad by its id with /query endpoint returns all

### ISSUE THREAD

**Issue by JaviRuiz314** [r-spacex/SpaceX-API#938]
Hey guys, maybe it is because I am doing something wrong but while trying to retrieve a launchpad info and its launches with an inner join by a given launchpad id I found that the POST url https://api.spacexdata.com/v4/launchpads/query with the body:

```
{
  "query": {
      "id": "5e9e4501f5090910d4566f83"
  }
}
```

returns all the launchpads instead of only one. Am I doing something wrong? I tried also with $eq operator and while, with other fields works, it doesn't for the id, which seemed odd to me.

Thanks a lot.

**Comment by jakewmeyer** [comment]
This is a bit of  weird one, because under the hood Mongo stores the `id` field as `_id`, so the query needs to be like the following:

```json
{
	"query": {
		"_id": "5e9e4501f5090910d4566f83"
	}
}
```

I'll add a note about this in the query guide, since it's non-intuitive to the user

**Comment by JaviRuiz314** [comment]
Oh I see, yes, that works wonders. Thanks a lot for the quick response!
