### ISSUE TITLE
The /info/history returns invalid dates.

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#94]
Some of the history events returned from https://api.spacexdata.com/v2/info/history contains invalid dates:
- 2014-09-00T00:00:00Z (day as 00?)
- 2008-12-00T00:00:00Z (same as above)

In the result, C#'s DateTime.Parse throws exceptions when trying to parse these strings during JSON deserialization. I have workaround by replacing 00T with 01T but it would be good to fix it in the database.

**Comment by jakewmeyer** [comment]
Gotcha. Working on a fix

**Comment by jakewmeyer** [comment]
Fixed

**Comment by Tearth** [comment]
Thanx for your fix, but I think there is still problem. Now, if I see correctly, dates from the first post have still 00 day but hour set as 01 which not solve the problem:

 - 2008-12-00T01:00:00Z instead of 2008-12-01T00:00:00Z (for example)
 - 2014-09-00T01:00:00Z instead of 2014-01-01T00:00:00Z

**Comment by jakewmeyer** [comment]
Found the correct dates. Should be good now

**Comment by Tearth** [comment]
Now everything works fine, thanx!

**Comment by jeroenboumans** [comment]
@jakewmeyer  Would it be possible to add the `launch_date_unix` to the model like the launches have?
