### ISSUE TITLE
Ugly wikipedia-like brackets in JRTI details.

### ISSUE THREAD

**Issue by pislagz** [r-spacex/SpaceX-API#941]
### Playing with data i noticed an ugly pair of brackets in details of JRTI. Highlighted in the image.

> ... The booster successfully landed on the deck; however, a lockout collet failed to engage on one of the legs causing the rocket to tip over, exploding on impact with the deck.**[23]** ...

I just assume it shouldn't be there, probably some wikipedia remains aint it?

![image](https://user-images.githubusercontent.com/77860645/139962253-a59ffa45-b4f5-4c76-a0e4-956d6fc50b6c.png)

**Comment by jakewmeyer** [comment]
Yep, definitely some leftover wiki brackets. This should be resolved too 👍

**Comment by pislagz** [comment]
Neat!
