### ISSUE TITLE
Adding new app to the List of known Apps / UI clients

### ISSUE THREAD

**Issue by TrifiAmanallah** [r-spacex/SpaceX-API#942]
Hi,

We deployed a new android app that makes use of the Spacex-Api. Can an you add it to the list ?
Here are the info:
> Name: Elon Musk Tracker
> Playstore: https://play.google.com/store/apps/details?id=com.ingenuity.elonmusktracker
> Type: Android app
> Creator: https://github.com/TrifiAmanallah
> Repo: Closed source
> Info: Elon musk related news, tweets and companies tracker

Thanks

**Comment by jakewmeyer** [comment]
Easiest way is to submit a PR with the update [here](https://github.com/r-spacex/SpaceX-API/blob/master/docs/apps.md)
