### ISSUE TITLE
Incorrect info on C208 capsule

### ISSUE THREAD

**Issue by AlbericTrancart** [r-spacex/SpaceX-API#957]
In [the payloads endpoint](https://api.spacexdata.com/v4/payloads), C208 capsule is flagged as reused for CRS-21 but [it was a new capsule](https://en.wikipedia.org/wiki/Cargo_Dragon_C208).

![image](https://user-images.githubusercontent.com/6317823/141690320-044d969a-b280-4e3b-84de-95fc1501e155.png)

**Comment by jakewmeyer** [comment]
Fixed! 👍
