### ISSUE TITLE
Question: using local mongodb instance - cannot import the data

### ISSUE THREAD

**Issue by alshapton** [r-spacex/SpaceX-API#96]
Ive got the code running, and a mongo instance, however i cant import the sample data 

Can anyone point me in the right direction pls ? Ive spent a week on this now and I am frustrated :-|

Cheers

Andrew

PS - ANY help is appreciated :-)

**Comment by jakewmeyer** [comment]
[mongorestore](https://docs.mongodb.com/manual/reference/program/mongorestore/#bin.mongorestore) is the tool used to import the data. The data was exported using [mongodump](https://docs.mongodb.com/manual/reference/program/mongodump/) and contains all the collections, indexes, and documents.

In your shell of choice, run the following:
```shell
mongorestore --gzip --archive=path/to/database/backup --db=spacex-api
```
This command defaults to the mongo instance running on localhost with no password. If you have authentication set up, you'll need to add it to the command per the mongorestore instructions

**Comment by alshapton** [comment]
Thanks
