### ISSUE TITLE
Date inconsistency in /parts/caps

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#97]
Every capsule data returned by https://api.spacexdata.com/v2/parts/caps contains original_launch fields with some date. The problem is inconsistency format of it because every capsule except C113 contains only date or "TBD" which is ok.

C113 contains both date and time which causes some difficulties when I want to write smart method which filter capsules by passed date in argument, now it's a bit problem because I don't know if I should send original_launch with time or not.

Proposed solutions:
 * short: remove time from original_launch in C113 capsule
 * long: add time to every capsule

Part of the response with mentioned capsule:

```json
{
  "capsule_serial":"C113",
  "capsule_id":"dragon1",
  "status":"active",
  "original_launch":"2017-08-14T16:31:00Z",
  "missions":[  
     "SpaceX CRS-12"
  ],
  "landings":1,
  "type":"Dragon 1.1",
  "details":"The last newly manufactured Dragon 1"
}
```

Thanx for your work!

**Comment by jakewmeyer** [comment]
All of them should have time, I'll make the changes shortly

**Comment by jakewmeyer** [comment]
Core fixes done 👍
