### ISSUE TITLE
Next Starlink launch update

### ISSUE THREAD

**Issue by trasparente** [r-spacex/SpaceX-API#971]
Next Starlink launch 139 seems to be scheduled **Wed Dec 01, 2021 23:20 UTC**
and ASOG is departed
:+1: Thanks

**Comment by timisenman** [comment]
I'd be very grateful if this launch could also be changed to { "tbd": false }

**Comment by timisenman** [comment]
@jakewmeyer Is there documentation anywhere regarding how to make changes to the wiki? I've tried in the past, but always failed.

**Comment by jakewmeyer** [comment]
Updated, @timisenman Not 100% sure, best bet would be to reach out to the r/SpaceX mods, they should be able to point you in the right direction.

**Comment by timisenman** [comment]
@jakewmeyer Thanks, Jake. Will take a look.

**Comment by trasparente** [comment]
New launch time is `6:12 p.m. EST` and landpad `5e9e3033383ecb075134e7cd` still missing.

Thanks Jake :heart:
