### ISSUE TITLE
Filter asds_landings in /parts/cores not work

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#98]
Some of the cores retrieved from https://api.spacexdata.com/v2/parts/cores have asds_landings field set to 1 or 2. Wiki [says](https://github.com/r-spacex/SpaceX-API/wiki/Core-Details), that I can request cores with the specified value, but when I call on example:
 * https://api.spacexdata.com/v2/parts/cores?asds_landings=1
or
 * https://api.spacexdata.com/v2/parts/cores?asds_landings=2

Then we have empty list. 9 cores have asds_landings set to 1 and two cores set to 2, so I think that API should return something more.

Thanx!

**Comment by jakewmeyer** [comment]
Easy typo fix. Changes live

**Comment by Tearth** [comment]
Thanx!
