### ISSUE TITLE
Starlink G4-4 not in upcoming launches

### ISSUE THREAD

**Issue by jdarpinian** [r-spacex/SpaceX-API#987]
The December 17 launch of Starlink Group 4-4 is not present in the upcoming launches returned by the API. But I see it listed on r/SpaceX's sidebar. I assumed that the sidebar was updated based on the API, but I guess not?

**Comment by timisenman** [comment]
Was coming here to ping about this too. It appears that SpaceX added a Starlink mission into their manifest kind of last minute. It's within 24 hours, so would appreciate some intervention to get the DB updated. Paging the Deus ex Machina @jakewmeyer 🙏

**Comment by jakewmeyer** [comment]
Trying to find any details about this launch, not seeing anything on SpaceX social media. Subreddit created a launch thread, but then removed it too?

**Comment by jdarpinian** [comment]
My source is Celestrak which has TLEs for the launch which are sourced from SpaceX official launch data posted (non-publicly) to space-track.org.

**Comment by jdarpinian** [comment]
See https://twitter.com/TSKelso/status/1470940418523099139?s=20
